-- Hand-edited (not atlas's DROP+recreate): add account_type + provider as
-- sort-key dimensions to "attribute_metrics_summaries" NON-destructively.
-- ADD COLUMN and MODIFY ORDER BY must be one ALTER statement — ClickHouse only
-- lets MODIFY ORDER BY extend the key with columns added in the same ALTER.
-- Existing aggregates are preserved (no DROP TABLE).
ALTER TABLE `attribute_metrics_summaries`
  ADD COLUMN `account_type` String,
  ADD COLUMN `provider` String,
  MODIFY ORDER BY (`gram_project_id`, `time_bucket`, `department_name`, `job_title`, `employee_type`, `division_name`, `cost_center_name`, `user_email`, `model`, `hook_source`, `roles`, `groups`, `account_type`, `provider`);
ALTER TABLE `trace_summaries` ADD COLUMN `account_type` SimpleAggregateFunction(max, String);
ALTER TABLE `trace_summaries` ADD COLUMN `provider` SimpleAggregateFunction(max, String);
-- Drop "attribute_metrics_summaries_mv" view
DROP VIEW `attribute_metrics_summaries_mv`;
-- Create "attribute_metrics_summaries_mv" view
CREATE MATERIALIZED VIEW `attribute_metrics_summaries_mv` TO `attribute_metrics_summaries` AS WITH toUnixTimestamp64Nano(toDateTime64('2026-06-20 00:00:00', 9, 'UTC')) AS attribute_metrics_cutoff_unix_nano SELECT gram_project_id, toStartOfHour(fromUnixTimestamp64Nano(time_unix_nano)) AS time_bucket, toString(attributes.user.attributes.department_name) AS department_name, toString(attributes.user.attributes.job_title) AS job_title, toString(attributes.user.attributes.employee_type) AS employee_type, toString(attributes.user.attributes.division_name) AS division_name, toString(attributes.user.attributes.cost_center_name) AS cost_center_name, user_email AS user_email, toString(attributes.gen_ai.response.model) AS model, hook_source, arraySort(JSONExtract(ifNull(toJSONString(attributes.user.roles), '[]'), 'Array(String)')) AS roles, arraySort(JSONExtract(ifNull(toJSONString(attributes.user.groups), '[]'), 'Array(String)')) AS groups, uniqExactIfState(toString(attributes.gen_ai.conversation.id), toString(attributes.gen_ai.conversation.id) != '') AS total_chats, sumIfState(toInt64OrZero(toString(attributes.gen_ai.usage.input_tokens)), toString(attributes.gen_ai.usage.input_tokens) != '') AS total_input_tokens, sumIfState(toInt64OrZero(toString(attributes.gen_ai.usage.output_tokens)), toString(attributes.gen_ai.usage.output_tokens) != '') AS total_output_tokens, sumIfState(toInt64OrZero(toString(attributes.gen_ai.usage.total_tokens)), toString(attributes.gen_ai.usage.total_tokens) != '') AS total_tokens, sumIfState(toInt64OrZero(toString(attributes.gen_ai.usage.cache_read.input_tokens)), toString(attributes.gen_ai.usage.cache_read.input_tokens) != '') AS cache_read_input_tokens, sumIfState(toInt64OrZero(toString(attributes.gen_ai.usage.cache_creation.input_tokens)), toString(attributes.gen_ai.usage.cache_creation.input_tokens) != '') AS cache_creation_input_tokens, sumIfState(toFloat64OrZero(toString(attributes.gen_ai.usage.cost)), toString(attributes.gen_ai.usage.cost) != '') AS total_cost, countIfState((toString(attributes.gram.tool.name) != '') AND (toString(attributes.gram.tool.name) NOT IN ('claude-code', 'codex', 'cursor')) AND (toString(attributes.gram.hook.event) IN ('PostToolUse', 'PostToolUseFailure'))) AS total_tool_calls, account_type, provider FROM telemetry_logs WHERE (time_unix_nano >= attribute_metrics_cutoff_unix_nano) AND (startsWith(gram_urn, 'claude-code:usage') OR startsWith(gram_urn, 'codex:usage') OR startsWith(gram_urn, 'cursor:usage') OR ((toString(attributes.gen_ai.operation.name) = 'chat') AND (toString(attributes.gen_ai.usage.cost) != '')) OR ((toString(attributes.gram.tool.name) != '') AND (toString(attributes.gram.tool.name) NOT IN ('claude-code', 'codex', 'cursor')))) GROUP BY gram_project_id, time_bucket, department_name, job_title, employee_type, division_name, cost_center_name, user_email, model, hook_source, roles, groups, account_type, provider;
-- Drop "trace_summaries_mv" view
DROP VIEW `trace_summaries_mv`;
-- Create "trace_summaries_mv" view
CREATE MATERIALIZED VIEW `trace_summaries_mv` TO `trace_summaries` AS SELECT trace_id, gram_project_id, any(gram_deployment_id) AS gram_deployment_id, any(gram_function_id) AS gram_function_id, any(gram_urn) AS gram_urn, any(tool_name) AS tool_name, any(tool_source) AS tool_source, any(event_source) AS event_source, any(user_email) AS user_email, any(hook_source) AS hook_source, any(skill_name) AS skill_name, anyIf(toolset_slug, toolset_slug != '') AS toolset_slug, anyIf(external_user_id, external_user_id != '') AS external_user_id, anyIf(user_id, user_id != '') AS user_id, anyIf(toString(attributes.gram.mcp.match), toString(attributes.gram.mcp.match) != '') AS mcp_match, anyIf(toString(attributes.gram.mcp.server_url), toString(attributes.gram.mcp.server_url) != '') AS mcp_server_url, min(time_unix_nano) AS start_time_unix_nano, toUInt64(count(*)) AS log_count, anyIfState(toInt32OrNull(toString(attributes.http.response.status_code)), toString(attributes.http.response.status_code) != '') AS http_status_code, max(if(toString(attributes.gen_ai.tool.call.result) != '', 1, 0)) AS has_result, max(if(toString(attributes.gram.hook.error) != '', 1, 0)) AS has_error, max(if(toString(attributes.gram.hook.block_reason) != '', 1, 0)) AS has_block, anyIf(toString(attributes.gram.hook.block_reason), toString(attributes.gram.hook.block_reason) != '') AS block_reason, anyIf(account_type, account_type != '') AS account_type, anyIf(provider, provider != '') AS provider FROM telemetry_logs WHERE (trace_id IS NOT NULL) AND (trace_id != '') AND (NOT startsWith(telemetry_logs.gram_urn, 'urn:uuid:')) GROUP BY trace_id, gram_project_id;
