-- Create "agent_events" table
CREATE TABLE `gram`.`agent_events` (
  `organization_id` String COMMENT 'Organization the record belongs to, from the provenance stamped at the ingest edge.' CODEC(ZSTD(1)),
  `project_id` String COMMENT 'Project the record was ingested under, from the provenance stamped at the ingest edge.' CODEC(ZSTD(1)),
  `occurred_at_unix_nano` Int64 COMMENT 'Producer event time as Unix time (ns). What every query window filters on.' CODEC(Delta(8), ZSTD(1)),
  `observed_at_unix_nano` Int64 COMMENT 'Unix time (ns) when the record reached the ingest edge. Orders competing observations of the same fact.' CODEC(Delta(8), ZSTD(1)),
  `record_id` String COMMENT 'One delivery key, resolved at ingest: the publisher record id for log-derived records, the span identity for span-derived ones. Readers de-duplicate on this and never branch on how a record arrived.' CODEC(ZSTD(1)),
  `session_id` String COMMENT 'Agent session the record belongs to, as extracted by the dialect. Rows sharing a session_id are the same session by definition. Empty when the producer states none.' CODEC(ZSTD(1)),
  `turn_id` String COMMENT 'Turn within the session, when the producer states one. Populated unevenly across producers.' CODEC(ZSTD(1)),
  `event_id` String COMMENT 'Natural identity of the subject (the message, the tool call), shared across observations of it by design. A minted id when the producer states none.' CODEC(ZSTD(1)),
  `event_type` LowCardinality(String) COMMENT 'Canonical event type assigned by the dialect. Says which kind of thing event_id names. Empty for records no dialect classified.',
  `raw_event_name` String COMMENT 'The producer own name for the event. For a span-derived row this is the span name. Kept so an unclassified record stays reclassifiable.' CODEC(ZSTD(1)),
  `source` LowCardinality(String) COMMENT 'Canonicalized producer surface derived from resource service.name at write time (e.g. claude-code, litellm). Empty when not stated.',
  `provider` LowCardinality(String) COMMENT 'Model provider the record concerns (e.g. anthropic, openai). Empty when not stated.',
  `surface` LowCardinality(String) COMMENT 'Agent surface the activity happened on (e.g. claude-code, codex, cursor). Empty when not stated.',
  `user_id` String COMMENT 'Producer-stated user id. Empty when not stated.' CODEC(ZSTD(1)),
  `user_email` String COMMENT 'Producer-stated user email. Empty when not stated.' CODEC(ZSTD(1)),
  `external_user_id` String COMMENT 'User id in the provider own account system. Empty when not stated.' CODEC(ZSTD(1)),
  `account_type` LowCardinality(String) COMMENT 'Resolved account type. Empty until attribution runs in this pipeline.',
  `billing_mode` LowCardinality(String) COMMENT 'Resolved billing mode. Empty until attribution runs in this pipeline.',
  `external_org_id` String COMMENT 'Organization id in the provider own account system. Empty when not resolved.' CODEC(ZSTD(1)),
  `device_id` String COMMENT 'Device the activity came from, when the device agent reported one. Empty otherwise.' CODEC(ZSTD(1)),
  `department_name` String COMMENT 'Directory department of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `division_name` String COMMENT 'Directory division of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `job_title` String COMMENT 'Directory job title of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `employee_type` String COMMENT 'Directory employee type of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `cost_center_name` String COMMENT 'Directory cost center of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `roles` Array(String) COMMENT 'Directory roles of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `groups` Array(String) COMMENT 'Directory groups of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `model` String COMMENT 'Model named by the record. Empty when not stated.' CODEC(ZSTD(1)),
  `query_source` LowCardinality(String) COMMENT 'Where the request originated inside the agent (e.g. user_prompt, tool_result). Empty when not stated.',
  `skill_name` String COMMENT 'Skill invoked, when the record says so. Empty otherwise.' CODEC(ZSTD(1)),
  `agent_name` String COMMENT 'Sub-agent name, when the record says so. Empty otherwise.' CODEC(ZSTD(1)),
  `mcp_server_name` String COMMENT 'MCP server involved, when the record says so. Empty otherwise.' CODEC(ZSTD(1)),
  `mcp_tool_name` String COMMENT 'MCP tool involved, when the record says so. Empty otherwise.' CODEC(ZSTD(1)),
  `tool_name` String COMMENT 'Tool the record concerns, when the record says so. Empty otherwise.' CODEC(ZSTD(1)),
  `text` String COMMENT 'The record in words. Empty where the producer put everything in attributes, in which case raw_event_name is the readable headline.' CODEC(ZSTD(1)),
  `outcome` LowCardinality(String) COMMENT 'Agent-vocabulary outcome: ok | error | empty when not stated. Not a protocol status code.',
  `outcome_message` String COMMENT 'Producer-stated message accompanying an error outcome. Empty otherwise.' CODEC(ZSTD(1)),
  `duration_nano` Int64 COMMENT 'Duration in nanoseconds when the producer states one (span duration, tool call duration). 0 when not stated.' CODEC(Delta(8), ZSTD(1)),
  `input_content` String COMMENT 'Normalized input message JSON. Empty when the record carries none.' CODEC(ZSTD(1)),
  `output_content` String COMMENT 'Normalized output message JSON. Empty when the record carries none.' CODEC(ZSTD(1)),
  `input_tokens` Int64 COMMENT 'Input tokens stated on the record. 0 when not stated.',
  `output_tokens` Int64 COMMENT 'Output tokens stated on the record. 0 when not stated.',
  `cache_read_tokens` Int64 COMMENT 'Cache read tokens stated on the record. 0 when not stated.',
  `cache_write_tokens` Int64 COMMENT 'Cache write tokens stated on the record. 0 when not stated.',
  `cost_usd` Float64 COMMENT 'Cost in USD stated on the record. 0 when not stated.',
  `attributes` JSON COMMENT 'Record attributes verbatim, including Gram enrichments. Anything not typed above survives here.' CODEC(ZSTD(1)),
  `resource_attributes` JSON COMMENT 'Attributes of the resource that produced the record.' CODEC(ZSTD(1)),
  `scope_attributes` JSON COMMENT 'Instrumentation scope attributes.' CODEC(ZSTD(1))
) ENGINE = MergeTree
PRIMARY KEY (`organization_id`, `project_id`, `occurred_at_unix_nano`, `event_type`, `event_id`) ORDER BY (`organization_id`, `project_id`, `occurred_at_unix_nano`, `event_type`, `event_id`) PARTITION BY (toYYYYMMDD(fromUnixTimestamp64Nano(occurred_at_unix_nano))) TTL fromUnixTimestamp64Nano(occurred_at_unix_nano) + toIntervalDay(90) SETTINGS index_granularity = 8192 COMMENT 'One row per observed agent occurrence, resolved by the ingest dialects into agent vocabulary rather than the shape it arrived in. Rows sharing a session_id belong to the same agent session. Append-only: every observation is retained so the lineage of a fact stays queryable, and de-duplication is performed at read time. The queryable surface is defined by the semantic layer, not by this table.';
-- Create "agent_metrics" table
CREATE TABLE `gram`.`agent_metrics` (
  `organization_id` String COMMENT 'Organization the data point belongs to, from the provenance stamped at the ingest edge.' CODEC(ZSTD(1)),
  `project_id` String COMMENT 'Project the data point was ingested under, from the provenance stamped at the ingest edge.' CODEC(ZSTD(1)),
  `occurred_at_unix_nano` Int64 COMMENT 'The data point own time as Unix time (ns). What every query window filters on.' CODEC(Delta(8), ZSTD(1)),
  `observed_at_unix_nano` Int64 COMMENT 'Unix time (ns) when the data point reached the ingest edge. The ReplacingMergeTree version column.' CODEC(Delta(8), ZSTD(1)),
  `window_start_unix_nano` Int64 COMMENT 'Start of the interval the data point covers, as Unix time (ns). Equals occurred_at_unix_nano for point observations.' CODEC(Delta(8), ZSTD(1)),
  `window_end_unix_nano` Int64 COMMENT 'End of the interval the data point covers, as Unix time (ns). Equals occurred_at_unix_nano for point observations.' CODEC(Delta(8), ZSTD(1)),
  `grain` LowCardinality(String) COMMENT 'Producer native reporting grain: turn | session | minute | hour | day | point. Gates rollup eligibility.',
  `temporality` LowCardinality(String) COMMENT 'OTLP aggregation temporality: delta | cumulative | unspecified. Without it a reader cannot know whether sum() over a set of rows is valid.',
  `is_monotonic` UInt8 COMMENT '1 when the producer declares the series monotonic, else 0.',
  `metric_id` String COMMENT 'Content-derived fingerprint over the OTel identifying set (resource attributes, scope, metric name, unit, data point type, temporality, monotonicity, point attributes) plus the point timestamps. Value is excluded on purpose so a replay reproduces the same fingerprint.' CODEC(ZSTD(1)),
  `metric_name` String COMMENT 'The producer own metric name, verbatim.' CODEC(ZSTD(1)),
  `canonical_metric` LowCardinality(String) COMMENT 'The dialect canonical name for the measure. Discriminating point attributes fold in here, so claude_code.token.usage with type=input becomes its own canonical metric.',
  `value` Float64 COMMENT 'The measured value. One column rather than an int/double pair because Float64 is exact to 2^53 and the OTel spec says the numeric representation is not identifying.',
  `unit` LowCardinality(String) COMMENT 'Unit as declared by the producer. Empty when not declared.',
  `session_id` String COMMENT 'Agent session the data point is attributable to. Empty for feeds that report without one.' CODEC(ZSTD(1)),
  `turn_id` String COMMENT 'Turn within the session, when the producer states one.' CODEC(ZSTD(1)),
  `user_id` String COMMENT 'Producer-stated user id. Empty when not stated.' CODEC(ZSTD(1)),
  `user_email` String COMMENT 'Producer-stated user email. Empty when not stated.' CODEC(ZSTD(1)),
  `external_user_id` String COMMENT 'User id in the provider own account system. Empty when not stated.' CODEC(ZSTD(1)),
  `model` String COMMENT 'Model the measurement concerns. Empty when not stated.' CODEC(ZSTD(1)),
  `query_source` LowCardinality(String) COMMENT 'Where the request originated inside the agent. Empty when not stated.',
  `skill_name` String COMMENT 'Skill invoked, when stated. Empty otherwise.' CODEC(ZSTD(1)),
  `agent_name` String COMMENT 'Sub-agent name, when stated. Empty otherwise.' CODEC(ZSTD(1)),
  `mcp_server_name` String COMMENT 'MCP server involved, when stated. Empty otherwise.' CODEC(ZSTD(1)),
  `mcp_tool_name` String COMMENT 'MCP tool involved, when stated. Empty otherwise.' CODEC(ZSTD(1)),
  `source` LowCardinality(String) COMMENT 'Canonicalized producer surface derived from resource service.name at write time. Empty when not stated.',
  `provider` LowCardinality(String) COMMENT 'Model provider the measurement concerns. Empty when not stated.',
  `surface` LowCardinality(String) COMMENT 'Agent surface the activity happened on. Empty when not stated.',
  `account_type` LowCardinality(String) COMMENT 'Resolved account type. Empty until attribution runs in this pipeline.',
  `billing_mode` LowCardinality(String) COMMENT 'Resolved billing mode. Empty until attribution runs in this pipeline.',
  `external_org_id` String COMMENT 'Organization id in the provider own account system. Empty when not resolved.' CODEC(ZSTD(1)),
  `device_id` String COMMENT 'Device the activity came from, when the device agent reported one. Empty otherwise.' CODEC(ZSTD(1)),
  `department_name` String COMMENT 'Directory department of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `division_name` String COMMENT 'Directory division of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `job_title` String COMMENT 'Directory job title of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `employee_type` String COMMENT 'Directory employee type of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `cost_center_name` String COMMENT 'Directory cost center of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `roles` Array(String) COMMENT 'Directory roles of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `groups` Array(String) COMMENT 'Directory groups of the user at ingest time. Empty when not enriched.' CODEC(ZSTD(1)),
  `attributes` JSON COMMENT 'Data point attributes verbatim, including Gram enrichments.' CODEC(ZSTD(1)),
  `resource_attributes` JSON COMMENT 'Attributes of the resource that produced the data point.' CODEC(ZSTD(1)),
  `scope_attributes` JSON COMMENT 'Instrumentation scope attributes.' CODEC(ZSTD(1))
) ENGINE = ReplacingMergeTree(observed_at_unix_nano)
PRIMARY KEY (`organization_id`, `project_id`, `occurred_at_unix_nano`, `canonical_metric`, `metric_id`) ORDER BY (`organization_id`, `project_id`, `occurred_at_unix_nano`, `canonical_metric`, `metric_id`) PARTITION BY (toYYYYMM(fromUnixTimestamp64Nano(occurred_at_unix_nano))) TTL fromUnixTimestamp64Nano(occurred_at_unix_nano) + toIntervalDay(730) SETTINGS index_granularity = 8192 COMMENT 'One row per measurement data point per measure, at the producer native grain. Carries a full dimension repeat so no join is required. Retained beyond agent_events so billing can read historical cycles. Replacing collapses only on background merges, so a reader must de-duplicate on metric_id (FINAL or LIMIT 1 BY) and never sum raw rows.';
