ALTER TABLE `gram`.`agent_events`
  COMMENT COLUMN `skill_name` 'Skill family (skill_*). Skill invoked, when the record says so. Empty otherwise. Deprecated in favour of name. Still filled on api_request, where it describes the request rather than the subject, until a skill event type exists to carry name.',
  COMMENT COLUMN `agent_name` 'Agent family (agent_*). Sub-agent name, when the record says so. Empty otherwise. Deprecated in favour of name. Still filled on api_request, where it describes the request rather than the subject, until an agent event type exists to carry name.',
  COMMENT COLUMN `mcp_server_name` 'MCP family (mcp_*). MCP server involved, when the record says so. Empty otherwise.',
  COMMENT COLUMN `mcp_tool_name` 'MCP family (mcp_*). MCP tool involved, when the record says so. Empty otherwise. Deprecated in favour of name, which carries the tool on tool_call, tool_call_result and tool_decision whether or not it is an MCP tool.',
  COMMENT COLUMN `tool_name` 'Tool family (tool_*), for tools that are not MCP. Tool the record concerns, when the record says so. Empty otherwise. Deprecated in favour of name, which carries the tool on tool_call, tool_call_result and tool_decision whether or not it is an MCP tool.',
  COMMENT COLUMN `input_content` 'Deprecated with no replacement, decided 2026-10-07: text carries the words and attributes carries the structure. Nothing reads it, and the writer stops filling it once the column enrichers land. Was the normalized input message JSON.',
  COMMENT COLUMN `output_content` 'Deprecated with no replacement, decided 2026-10-07: text carries the words and attributes carries the structure. Nothing reads it, and the writer stops filling it once the column enrichers land. Was the normalized output message JSON.',
  ADD COLUMN `name` String COMMENT 'Name of the subject of the event, the generic pair to event_id: the tool on tool_call, tool_call_result and tool_decision (MCP or not), the skill on skill events and the agent on sub-agent events once those exist. Empty on prompt and api_* types, and when not stated. Replaces the per-family tool_name, mcp_tool_name, skill_name and agent_name columns.' CODEC(ZSTD(1)) AFTER `raw_event_name`;
