ALTER TABLE `gram`.`billing_meter_readings_by_time`
  DROP COLUMN `account_type`,
  DROP COLUMN `hook_hostname`,
  DROP COLUMN `hook_source`,
  DROP COLUMN `message_link_reason`,
  DROP COLUMN `message_link_status`,
  DROP COLUMN `message_type`,
  DROP COLUMN `message_user_id`,
  DROP COLUMN `request_path`,
  DROP COLUMN `risk_policy_link_reason`,
  DROP COLUMN `risk_policy_link_status`,
  DROP COLUMN `risk_policy_version`,
  DROP COLUMN `scan_execution_path`,
  DROP COLUMN `workload_source`;
