/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d6e9620bd841
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { agentsGet } from "../funcs/agentsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type AgentsGetQueryData = components.AgentResponseOutput;

export function prefetchAgentsGet(
  queryClient: QueryClient,
  client$: GramCore,
  request: operations.GetAgentResponseRequest,
  security?: operations.GetAgentResponseSecurity | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAgentsGetQuery(
      client$,
      request,
      security,
      options,
    ),
  });
}

export function buildAgentsGetQuery(
  client$: GramCore,
  request: operations.GetAgentResponseRequest,
  security?: operations.GetAgentResponseSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<AgentsGetQueryData>;
} {
  return {
    queryKey: queryKeyAgentsGet({
      responseId: request.responseId,
      gramKey: request.gramKey,
      gramProject: request.gramProject,
    }),
    queryFn: async function agentsGetQueryFn(ctx): Promise<AgentsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(agentsGet(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAgentsGet(
  parameters: {
    responseId: string;
    gramKey?: string | undefined;
    gramProject?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "agents", "get", parameters];
}
