/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { projectsCreate } from "../funcs/projectsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CreateProjectMutationVariables = {
  request: operations.CreateProjectRequest;
  security?: operations.CreateProjectSecurity | undefined;
  options?: RequestOptions;
};

export type CreateProjectMutationData = components.CreateProjectResult;

/**
 * createProject projects
 *
 * @remarks
 * Create a new project.
 */
export function useCreateProjectMutation(
  options?: MutationHookOptions<
    CreateProjectMutationData,
    Error,
    CreateProjectMutationVariables
  >,
): UseMutationResult<
  CreateProjectMutationData,
  Error,
  CreateProjectMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildCreateProjectMutation(client, options),
    ...options,
  });
}

export function mutationKeyCreateProject(): MutationKey {
  return ["@gram/client", "projects", "create"];
}

export function buildCreateProjectMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CreateProjectMutationVariables,
  ) => Promise<CreateProjectMutationData>;
} {
  return {
    mutationKey: mutationKeyCreateProject(),
    mutationFn: function createProjectMutationFn({
      request,
      security,
      options,
    }): Promise<CreateProjectMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(projectsCreate(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}
