/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { toolsetsDiscardDraft } from "../funcs/toolsetsDiscardDraft.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type DiscardDraftMutationVariables = {
  request: operations.DiscardDraftRequest;
  security?: operations.DiscardDraftSecurity | undefined;
  options?: RequestOptions;
};

export type DiscardDraftMutationData = components.Toolset;

/**
 * discardDraft toolsets
 *
 * @remarks
 * Discard any pending draft changes for a toolset.
 */
export function useDiscardDraftMutation(
  options?: MutationHookOptions<
    DiscardDraftMutationData,
    Error,
    DiscardDraftMutationVariables
  >,
): UseMutationResult<
  DiscardDraftMutationData,
  Error,
  DiscardDraftMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildDiscardDraftMutation(client, options),
    ...options,
  });
}

export function mutationKeyDiscardDraft(): MutationKey {
  return ["@gram/client", "toolsets", "discardDraft"];
}

export function buildDiscardDraftMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: DiscardDraftMutationVariables,
  ) => Promise<DiscardDraftMutationData>;
} {
  return {
    mutationKey: mutationKeyDiscardDraft(),
    mutationFn: function discardDraftMutationFn({
      request,
      security,
      options,
    }): Promise<DiscardDraftMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(toolsetsDiscardDraft(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}
