/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useGramContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildGetTunnelledMcpServerQuery,
  GetTunnelledMcpServerQueryData,
  prefetchGetTunnelledMcpServer,
  queryKeyGetTunnelledMcpServer,
} from "./getTunnelledMcpServer.core.js";
export {
  buildGetTunnelledMcpServerQuery,
  type GetTunnelledMcpServerQueryData,
  prefetchGetTunnelledMcpServer,
  queryKeyGetTunnelledMcpServer,
};

export type GetTunnelledMcpServerQueryError =
  | errors.ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * getServer tunnelledMcp
 *
 * @remarks
 * Get a tunnelled MCP server by ID
 */
export function useGetTunnelledMcpServer(
  request: operations.GetTunnelledMcpServerRequest,
  security?: operations.GetTunnelledMcpServerSecurity | undefined,
  options?: QueryHookOptions<
    GetTunnelledMcpServerQueryData,
    GetTunnelledMcpServerQueryError
  >,
): UseQueryResult<
  GetTunnelledMcpServerQueryData,
  GetTunnelledMcpServerQueryError
> {
  const client = useGramContext();
  return useQuery({
    ...buildGetTunnelledMcpServerQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * getServer tunnelledMcp
 *
 * @remarks
 * Get a tunnelled MCP server by ID
 */
export function useGetTunnelledMcpServerSuspense(
  request: operations.GetTunnelledMcpServerRequest,
  security?: operations.GetTunnelledMcpServerSecurity | undefined,
  options?: SuspenseQueryHookOptions<
    GetTunnelledMcpServerQueryData,
    GetTunnelledMcpServerQueryError
  >,
): UseSuspenseQueryResult<
  GetTunnelledMcpServerQueryData,
  GetTunnelledMcpServerQueryError
> {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildGetTunnelledMcpServerQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function setGetTunnelledMcpServerData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      id: string;
      gramSession?: string | undefined;
      gramKey?: string | undefined;
      gramProject?: string | undefined;
    },
  ],
  data: GetTunnelledMcpServerQueryData,
): GetTunnelledMcpServerQueryData | undefined {
  const key = queryKeyGetTunnelledMcpServer(...queryKeyBase);

  return client.setQueryData<GetTunnelledMcpServerQueryData>(key, data);
}

export function invalidateGetTunnelledMcpServer(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      id: string;
      gramSession?: string | undefined;
      gramKey?: string | undefined;
      gramProject?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "tunnelledMcp", "getServer", ...queryKeyBase],
  });
}

export function invalidateAllGetTunnelledMcpServer(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "tunnelledMcp", "getServer"],
  });
}
