/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as operations from "../models/operations/index.js";
import { useGramContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildListAllowedOriginsQuery,
  ListAllowedOriginsQueryData,
  prefetchListAllowedOrigins,
  queryKeyListAllowedOrigins,
} from "./listAllowedOrigins.core.js";
export {
  buildListAllowedOriginsQuery,
  type ListAllowedOriginsQueryData,
  prefetchListAllowedOrigins,
  queryKeyListAllowedOrigins,
};

/**
 * listAllowedOrigins projects
 *
 * @remarks
 * List allowed origins for a project.
 */
export function useListAllowedOrigins(
  request?: operations.ListAllowedOriginsRequest | undefined,
  security?: operations.ListAllowedOriginsSecurity | undefined,
  options?: QueryHookOptions<ListAllowedOriginsQueryData>,
): UseQueryResult<ListAllowedOriginsQueryData, Error> {
  const client = useGramContext();
  return useQuery({
    ...buildListAllowedOriginsQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * listAllowedOrigins projects
 *
 * @remarks
 * List allowed origins for a project.
 */
export function useListAllowedOriginsSuspense(
  request?: operations.ListAllowedOriginsRequest | undefined,
  security?: operations.ListAllowedOriginsSecurity | undefined,
  options?: SuspenseQueryHookOptions<ListAllowedOriginsQueryData>,
): UseSuspenseQueryResult<ListAllowedOriginsQueryData, Error> {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildListAllowedOriginsQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function setListAllowedOriginsData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      gramKey?: string | undefined;
      gramSession?: string | undefined;
      gramProject?: string | undefined;
    },
  ],
  data: ListAllowedOriginsQueryData,
): ListAllowedOriginsQueryData | undefined {
  const key = queryKeyListAllowedOrigins(...queryKeyBase);

  return client.setQueryData<ListAllowedOriginsQueryData>(key, data);
}

export function invalidateListAllowedOrigins(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      gramKey?: string | undefined;
      gramSession?: string | undefined;
      gramProject?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gram/client",
      "projects",
      "listAllowedOrigins",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllListAllowedOrigins(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "projects", "listAllowedOrigins"],
  });
}
