/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { assistantsListMessages } from "../funcs/assistantsListMessages.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ListAssistantMessagesQueryData = components.ListMessagesResult;

export function prefetchListAssistantMessages(
  queryClient: QueryClient,
  client$: GramCore,
  request: operations.ListAssistantMessagesRequest,
  security?: operations.ListAssistantMessagesSecurity | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildListAssistantMessagesQuery(
      client$,
      request,
      security,
      options,
    ),
  });
}

export function buildListAssistantMessagesQuery(
  client$: GramCore,
  request: operations.ListAssistantMessagesRequest,
  security?: operations.ListAssistantMessagesSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ListAssistantMessagesQueryData>;
} {
  return {
    queryKey: queryKeyListAssistantMessages({
      chatId: request.chatId,
      afterSeq: request.afterSeq,
      gramSession: request.gramSession,
      gramProject: request.gramProject,
    }),
    queryFn: async function listAssistantMessagesQueryFn(
      ctx,
    ): Promise<ListAssistantMessagesQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(assistantsListMessages(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyListAssistantMessages(
  parameters: {
    chatId: string;
    afterSeq?: number | undefined;
    gramSession?: string | undefined;
    gramProject?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "assistants", "listMessages", parameters];
}
