/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3876b12fa949
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { chatLoad } from "../funcs/chatLoad.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type LoadChatQueryData = components.Chat;

/**
 * loadChat chat
 *
 * @remarks
 * Load a chat by its ID
 */
export function useLoadChat(
  request: operations.LoadChatRequest,
  security?: operations.LoadChatSecurity | undefined,
  options?: QueryHookOptions<LoadChatQueryData>,
): UseQueryResult<LoadChatQueryData, Error> {
  const client = useGramContext();
  return useQuery({
    ...buildLoadChatQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * loadChat chat
 *
 * @remarks
 * Load a chat by its ID
 */
export function useLoadChatSuspense(
  request: operations.LoadChatRequest,
  security?: operations.LoadChatSecurity | undefined,
  options?: SuspenseQueryHookOptions<LoadChatQueryData>,
): UseSuspenseQueryResult<LoadChatQueryData, Error> {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildLoadChatQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function prefetchLoadChat(
  queryClient: QueryClient,
  client$: GramCore,
  request: operations.LoadChatRequest,
  security?: operations.LoadChatSecurity | undefined,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildLoadChatQuery(
      client$,
      request,
      security,
    ),
  });
}

export function setLoadChatData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      id: string;
      gramSession?: string | undefined;
      gramProject?: string | undefined;
      gramChatSession?: string | undefined;
    },
  ],
  data: LoadChatQueryData,
): LoadChatQueryData | undefined {
  const key = queryKeyLoadChat(...queryKeyBase);

  return client.setQueryData<LoadChatQueryData>(key, data);
}

export function invalidateLoadChat(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      id: string;
      gramSession?: string | undefined;
      gramProject?: string | undefined;
      gramChatSession?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "chat", "load", ...queryKeyBase],
  });
}

export function invalidateAllLoadChat(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "chat", "load"],
  });
}

export function buildLoadChatQuery(
  client$: GramCore,
  request: operations.LoadChatRequest,
  security?: operations.LoadChatSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<LoadChatQueryData>;
} {
  return {
    queryKey: queryKeyLoadChat({
      id: request.id,
      gramSession: request.gramSession,
      gramProject: request.gramProject,
      gramChatSession: request.gramChatSession,
    }),
    queryFn: async function loadChatQueryFn(ctx): Promise<LoadChatQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(chatLoad(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyLoadChat(
  parameters: {
    id: string;
    gramSession?: string | undefined;
    gramProject?: string | undefined;
    gramChatSession?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "chat", "load", parameters];
}
