/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useGramContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPolicyBypassesQuery,
  PolicyBypassesQueryData,
  prefetchPolicyBypasses,
  queryKeyPolicyBypasses,
} from "./policyBypasses.core.js";
export {
  buildPolicyBypassesQuery,
  type PolicyBypassesQueryData,
  prefetchPolicyBypasses,
  queryKeyPolicyBypasses,
};

export type PolicyBypassesQueryError =
  | errors.ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * listBypasses policyaccess
 *
 * @remarks
 * List active risk-policy bypass grants.
 */
export function usePolicyBypasses(
  request?: operations.ListPolicyBypassesRequest | undefined,
  security?: operations.ListPolicyBypassesSecurity | undefined,
  options?: QueryHookOptions<PolicyBypassesQueryData, PolicyBypassesQueryError>,
): UseQueryResult<PolicyBypassesQueryData, PolicyBypassesQueryError> {
  const client = useGramContext();
  return useQuery({
    ...buildPolicyBypassesQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * listBypasses policyaccess
 *
 * @remarks
 * List active risk-policy bypass grants.
 */
export function usePolicyBypassesSuspense(
  request?: operations.ListPolicyBypassesRequest | undefined,
  security?: operations.ListPolicyBypassesSecurity | undefined,
  options?: SuspenseQueryHookOptions<
    PolicyBypassesQueryData,
    PolicyBypassesQueryError
  >,
): UseSuspenseQueryResult<PolicyBypassesQueryData, PolicyBypassesQueryError> {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildPolicyBypassesQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function setPolicyBypassesData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      gramKey?: string | undefined;
      gramSession?: string | undefined;
    },
  ],
  data: PolicyBypassesQueryData,
): PolicyBypassesQueryData | undefined {
  const key = queryKeyPolicyBypasses(...queryKeyBase);

  return client.setQueryData<PolicyBypassesQueryData>(key, data);
}

export function invalidatePolicyBypasses(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      gramKey?: string | undefined;
      gramSession?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "policyaccess", "listBypasses", ...queryKeyBase],
  });
}

export function invalidateAllPolicyBypasses(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "policyaccess", "listBypasses"],
  });
}
