/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d0fb725b3bc4
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { toolsetsGetBySlug } from "../funcs/toolsetsGetBySlug.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type ToolsetQueryData = components.Toolset;

/**
 * getToolset toolsets
 *
 * @remarks
 * Get detailed information about a toolset including full HTTP tool definitions
 */
export function useToolset(
  request: operations.GetToolsetRequest,
  security?: operations.GetToolsetSecurity | undefined,
  options?: QueryHookOptions<ToolsetQueryData>,
): UseQueryResult<ToolsetQueryData, Error> {
  const client = useGramContext();
  return useQuery({
    ...buildToolsetQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

/**
 * getToolset toolsets
 *
 * @remarks
 * Get detailed information about a toolset including full HTTP tool definitions
 */
export function useToolsetSuspense(
  request: operations.GetToolsetRequest,
  security?: operations.GetToolsetSecurity | undefined,
  options?: SuspenseQueryHookOptions<ToolsetQueryData>,
): UseSuspenseQueryResult<ToolsetQueryData, Error> {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildToolsetQuery(
      client,
      request,
      security,
      options,
    ),
    ...options,
  });
}

export function prefetchToolset(
  queryClient: QueryClient,
  client$: GramCore,
  request: operations.GetToolsetRequest,
  security?: operations.GetToolsetSecurity | undefined,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildToolsetQuery(
      client$,
      request,
      security,
    ),
  });
}

export function setToolsetData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      slug: string;
      gramSession?: string | undefined;
      gramKey?: string | undefined;
      gramProject?: string | undefined;
    },
  ],
  data: ToolsetQueryData,
): ToolsetQueryData | undefined {
  const key = queryKeyToolset(...queryKeyBase);

  return client.setQueryData<ToolsetQueryData>(key, data);
}

export function invalidateToolset(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      slug: string;
      gramSession?: string | undefined;
      gramKey?: string | undefined;
      gramProject?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "toolsets", "getBySlug", ...queryKeyBase],
  });
}

export function invalidateAllToolset(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "toolsets", "getBySlug"],
  });
}

export function buildToolsetQuery(
  client$: GramCore,
  request: operations.GetToolsetRequest,
  security?: operations.GetToolsetSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<ToolsetQueryData>;
} {
  return {
    queryKey: queryKeyToolset({
      slug: request.slug,
      gramSession: request.gramSession,
      gramKey: request.gramKey,
      gramProject: request.gramProject,
    }),
    queryFn: async function toolsetQueryFn(ctx): Promise<ToolsetQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(toolsetsGetBySlug(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyToolset(
  parameters: {
    slug: string;
    gramSession?: string | undefined;
    gramKey?: string | undefined;
    gramProject?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "toolsets", "getBySlug", parameters];
}
