// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Plugin struct {
	ID             uuid.UUID
	OrganizationID string
	ProjectID      uuid.UUID
	Name           string
	Slug           string
	Description    pgtype.Text
	// Marks the fallback plugin new servers land in when not explicitly routed to a named plugin. At most one true per project (see plugins_project_id_is_default_key).
	IsDefault pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Deleted   bool
}

type RolePluginAssociation struct {
	ID                        uuid.UUID
	RoleProvisioningSettingID uuid.NullUUID
	ProjectID                 uuid.NullUUID
	PluginID                  uuid.NullUUID
	IsCurrent                 bool
	RetiredAt                 pgtype.Timestamptz
	LastAutomaticName         pgtype.Text
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type RoleProvisioningSetting struct {
	ID             uuid.UUID
	OrganizationID pgtype.Text
	RoleUrn        string
	Enabled        bool
	ProjectID      uuid.NullUUID
	LastAttemptAt  pgtype.Timestamptz
	LastErrorCode  pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
