/**
 * Search terms for each global settings page, keyed by the org route's `url`.
 * The settings search matches these as well as page titles, so "SAML",
 * "retention" or "invoice" land on the page that holds that setting. Add a
 * term here whenever a setting is added to one of these pages.
 */
export const SETTINGS_SEARCH_TERMS: Record<string, string[]> = {
  projects: [
    "Create project",
    "Rename project",
    "Delete project",
    "Favorite projects",
    "Workspace",
  ],
  billing: [
    "Plan",
    "Subscription",
    "Invoice",
    "Payment method",
    "Credit card",
    "Upgrade",
    "Spend",
    "Spend cap",
    "Usage",
    "Billing cycle",
    "Session storage",
    "Risk scans",
    "MCP gateway usage",
  ],
  team: [
    "Invite member",
    "Invite",
    "Users",
    "Seats",
    "Remove member",
    "Teammates",
  ],
  access: [
    "Roles",
    "Permissions",
    "RBAC",
    "Custom role",
    "Scopes",
    "Grants",
    "Access challenges",
    "Denied requests",
  ],
  identity: [
    "SSO",
    "Single sign-on",
    "SAML",
    "OIDC",
    "Identity provider",
    "IdP",
    "Directory sync",
    "SCIM",
    "Okta",
    "Microsoft Entra",
    "Azure AD",
    "Google Workspace",
    "Domain verification",
    "Slack workspace",
  ],
  domains: [
    "Custom domain",
    "Domain",
    "DNS",
    "CNAME",
    "Private network",
    "Tailscale",
  ],
  "api-keys": ["API key", "Token", "Access token", "Credentials", "CLI key"],
  "encryption-keys": [
    "KMS",
    "BYOK",
    "Customer-managed keys",
    "Encryption",
    "Signing keys",
  ],
  "external-services": ["AWS", "External credentials", "KMS credentials"],
  "audit-logs": ["Audit trail", "Activity", "History", "Who changed"],
  "ai-integrations": [
    "Model provider",
    "LLM keys",
    "OpenAI",
    "Anthropic",
    "OpenRouter",
    "Claude",
    "Cursor",
    "Agent platforms",
  ],
  skills: ["SKILL.md", "Skill capture", "Organization skills"],
  "device-agent": [
    "Devices",
    "Laptops",
    "MDM",
    "Jamf",
    "Kandji",
    "Scan targets",
    "Endpoint",
  ],
  logs: [
    "Enable logs",
    "Retention",
    "Telemetry",
    "Tool traces",
    "Record tool I/O",
    "Upload skill content",
    "Agent session capture",
    "Fail open during outages",
    "Observability mode",
    "Hook browser sign-in",
  ],
  "data/event-feed": ["Events", "Stream", "Live feed"],
  "data/exports": ["Export", "SIEM", "S3", "Datadog", "Splunk"],
  webhooks: ["Webhook", "Notifications", "Callback URL", "Signing secret"],
  "platform-admin": ["Impersonate", "Staff", "Platform admin"],
  "platform-admin/rbac": ["RBAC override", "Grant override"],
  "platform-admin/onboarding": ["Enterprise onboarding", "Onboarding email"],
  "platform-admin/openrouter-keys": ["OpenRouter", "Upstream keys"],
};
