server:
  - 'go.mod'
  - 'go.sum'
  - 'server/**'

client:
  - 'client/**'
  - 'package.json'
  - 'pnpm-lock.yaml'
  - 'pnpm-workspace.yaml'
  - 'tsconfig.json'
  - 'sdks/typescript/**'

functions:
  - 'go.mod'
  - 'go.sum'
  - 'functions/**'

cli:
  - 'go.mod'
  - 'go.sum'
  - 'cli/**'
  - 'server/design/**'
  - 'server/gen/**'

tsframework:
  - 'ts-framework/**'

elements:
  - 'elements/**'

migrations:
  - 'go.mod'
  - 'go.sum'
  - 'server/migrations/**'
  - 'server/clickhouse/migrations/**'

plog:
  - 'go.mod'
  - 'go.sum'
  - 'plog/**'
