// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/speakeasy-api/gram/server/internal/tools/repo/models"
	"github.com/speakeasy-api/gram/server/internal/urn"
)

type Deployment struct {
	ID             uuid.UUID
	Seq            int64
	UserID         string
	ProjectID      uuid.UUID
	OrganizationID string
	IdempotencyKey string
	ClonedFrom     uuid.NullUUID
	GithubRepo     pgtype.Text
	GithubPr       pgtype.Text
	GithubSha      pgtype.Text
	ExternalID     pgtype.Text
	ExternalUrl    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type DeploymentsFunction struct {
	ID            uuid.UUID
	DeploymentID  uuid.UUID
	AssetID       uuid.UUID
	Name          string
	Slug          string
	Runtime       string
	RunnerVersion pgtype.Text
}

type DeploymentsOpenapiv3Asset struct {
	ID           uuid.UUID
	DeploymentID uuid.UUID
	AssetID      uuid.UUID
	Name         string
	Slug         string
}

type FunctionResourceDefinition struct {
	ID           uuid.UUID
	ResourceUrn  urn.Resource
	ProjectID    uuid.UUID
	DeploymentID uuid.UUID
	FunctionID   uuid.UUID
	Runtime      string
	Name         string
	Description  string
	Uri          string
	Title        pgtype.Text
	MimeType     pgtype.Text
	Variables    []byte
	Meta         []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Deleted      bool
}

type FunctionToolDefinition struct {
	ID              uuid.UUID
	ToolUrn         urn.Tool
	ProjectID       uuid.UUID
	DeploymentID    uuid.UUID
	FunctionID      uuid.UUID
	Runtime         string
	Name            string
	Description     string
	InputSchema     []byte
	Variables       []byte
	AuthInput       []byte
	Meta            []byte
	ReadOnlyHint    pgtype.Bool
	DestructiveHint pgtype.Bool
	IdempotentHint  pgtype.Bool
	OpenWorldHint   pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Deleted         bool
}

type HttpSecurity struct {
	ID                  uuid.UUID
	DeploymentID        uuid.UUID
	ProjectID           uuid.NullUUID
	Openapiv3DocumentID uuid.NullUUID
	Key                 string
	Type                pgtype.Text
	Name                pgtype.Text
	InPlacement         pgtype.Text
	Scheme              pgtype.Text
	BearerFormat        pgtype.Text
	OauthTypes          []string
	OauthFlows          []byte
	EnvVariables        []string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	Deleted             bool
}

type HttpToolDefinition struct {
	ID                  uuid.UUID
	ToolUrn             urn.Tool
	ProjectID           uuid.UUID
	DeploymentID        uuid.UUID
	Openapiv3DocumentID uuid.NullUUID
	Confirm             pgtype.Text
	ConfirmPrompt       pgtype.Text
	Summarizer          pgtype.Text
	Name                string
	UntruncatedName     pgtype.Text
	Summary             string
	Description         string
	Openapiv3Operation  pgtype.Text
	Tags                []string
	XGram               pgtype.Bool
	OriginalName        pgtype.Text
	OriginalSummary     pgtype.Text
	OriginalDescription pgtype.Text
	ServerEnvVar        string
	DefaultServerUrl    pgtype.Text
	Security            []byte
	HttpMethod          string
	Path                string
	SchemaVersion       string
	Schema              []byte
	HeaderSettings      []byte
	QuerySettings       []byte
	PathSettings        []byte
	RequestContentType  pgtype.Text
	ResponseFilter      *models.ResponseFilter
	ReadOnlyHint        pgtype.Bool
	DestructiveHint     pgtype.Bool
	IdempotentHint      pgtype.Bool
	OpenWorldHint       pgtype.Bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	Deleted             bool
}

type PackageVersion struct {
	ID           uuid.UUID
	PackageID    uuid.UUID
	DeploymentID uuid.UUID
	Visibility   string
	Major        int64
	Minor        int64
	Patch        int64
	Prerelease   pgtype.Text
	Build        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Deleted      bool
}
