/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { adminGetRegistryOktaCandidates } from "../funcs/adminGetRegistryOktaCandidates.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AdminRegistryOktaCandidates } from "../models/components/adminregistryoktacandidates.js";
import { AdminGetRegistryOktaCandidatesRequest } from "../models/operations/admingetregistryoktacandidates.js";
import { unwrapAsync } from "../types/fp.js";
export type AdminGetRegistryOktaCandidatesQueryData =
  AdminRegistryOktaCandidates;

export function prefetchAdminGetRegistryOktaCandidates(
  queryClient: QueryClient,
  client$: GramCore,
  request: AdminGetRegistryOktaCandidatesRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAdminGetRegistryOktaCandidatesQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildAdminGetRegistryOktaCandidatesQuery(
  client$: GramCore,
  request: AdminGetRegistryOktaCandidatesRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AdminGetRegistryOktaCandidatesQueryData>;
} {
  return {
    queryKey: queryKeyAdminGetRegistryOktaCandidates({ id: request.id }),
    queryFn: async function adminGetRegistryOktaCandidatesQueryFn(
      ctx,
    ): Promise<AdminGetRegistryOktaCandidatesQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(adminGetRegistryOktaCandidates(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAdminGetRegistryOktaCandidates(
  parameters: { id: string },
): QueryKey {
  return [
    "@gram/admin-client",
    "admin",
    "getRegistryOktaCandidates",
    parameters,
  ];
}
