/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { adminSaveRegistryEntry } from "../funcs/adminSaveRegistryEntry.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AdminRegistryEntry } from "../models/components/adminregistryentry.js";
import { SaveRegistryEntryRequestBody } from "../models/components/saveregistryentryrequestbody.js";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { ServiceError } from "../models/errors/serviceerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AdminSaveRegistryEntryMutationVariables = {
  request: SaveRegistryEntryRequestBody;
  options?: RequestOptions;
};

export type AdminSaveRegistryEntryMutationData = AdminRegistryEntry;

export type AdminSaveRegistryEntryMutationError =
  | ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * saveRegistryEntry admin
 *
 * @remarks
 * Staff-only registry administration.
 */
export function useAdminSaveRegistryEntryMutation(
  options?: MutationHookOptions<
    AdminSaveRegistryEntryMutationData,
    AdminSaveRegistryEntryMutationError,
    AdminSaveRegistryEntryMutationVariables
  >,
): UseMutationResult<
  AdminSaveRegistryEntryMutationData,
  AdminSaveRegistryEntryMutationError,
  AdminSaveRegistryEntryMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildAdminSaveRegistryEntryMutation(client, options),
    ...options,
  });
}

export function mutationKeyAdminSaveRegistryEntry(): MutationKey {
  return ["@gram/admin-client", "admin", "saveRegistryEntry"];
}

export function buildAdminSaveRegistryEntryMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AdminSaveRegistryEntryMutationVariables,
  ) => Promise<AdminSaveRegistryEntryMutationData>;
} {
  return {
    mutationKey: mutationKeyAdminSaveRegistryEntry(),
    mutationFn: function adminSaveRegistryEntryMutationFn({
      request,
      options,
    }): Promise<AdminSaveRegistryEntryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(adminSaveRegistryEntry(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
