/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { adminAdminListUsers } from "../funcs/adminAdminListUsers.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AdminListUsersResult } from "../models/components/adminlistusersresult.js";
import { AdminListUsersRequest } from "../models/operations/adminlistusers.js";
import { unwrapAsync } from "../types/fp.js";
export type AdminAdminListUsersQueryData = AdminListUsersResult;

export function prefetchAdminAdminListUsers(
  queryClient: QueryClient,
  client$: GramCore,
  request?: AdminListUsersRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAdminAdminListUsersQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildAdminAdminListUsersQuery(
  client$: GramCore,
  request?: AdminListUsersRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AdminAdminListUsersQueryData>;
} {
  return {
    queryKey: queryKeyAdminAdminListUsers({
      q: request?.q,
      page: request?.page,
      limit: request?.limit,
    }),
    queryFn: async function adminAdminListUsersQueryFn(
      ctx,
    ): Promise<AdminAdminListUsersQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(adminAdminListUsers(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAdminAdminListUsers(
  parameters: {
    q?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
  },
): QueryKey {
  return ["@gram/admin-client", "admin", "adminListUsers", parameters];
}
