package:
  name: gram-runner
  version: 0.0.0
  epoch: 0
  description: 'Gram Functions runner'
  url: https://github.com/speakeasy-api/gram
  copyright:
    - attestation: Copyright 2025 Speakeasy Development, Inc.
      license: AGPL-3.0-or-later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  environment:
    GOMODCACHE: '/var/cache/melange' 

vars:
  version: dev
  commit: unset
  date: unset

pipeline:
  - uses: go/build
    with:
      modroot: ..
      packages: cmd/runner/main.go
      output: gram-runner
      extra-args: -trimpath
      ldflags: >-
        -s -w
        -X github.com/speakeasy-api/gram/functions/buildinfo.Version=${{ vars.version }}
        -X github.com/speakeasy-api/gram/functions/buildinfo.Commit=${{ vars.commit }}
        -X github.com/speakeasy-api/gram/functions/buildinfo.Date=${{ vars.date }}
