// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NetworkIngress struct {
	ID                   uuid.UUID
	OrganizationID       string
	Provider             string
	Hostname             string
	CredentialKind       string
	AuthKeyEnc           pgtype.Text
	OauthClientID        pgtype.Text
	OauthClientSecretEnc pgtype.Text
	Tags                 []string
	Enabled              bool
	PrivateNetworkOnly   bool
	IdentityRequired     bool
	Status               string
	NetworkName          pgtype.Text
	DnsName              pgtype.Text
	NodeID               pgtype.Text
	LastError            pgtype.Text
	LastSeenAt           pgtype.Timestamptz
	ConnectedSince       pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	Deleted              bool
}
