# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - dir: ./cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/speakeasy-api/gram/cli/internal/app.GitSHA={{.Commit}} -X github.com/speakeasy-api/gram/cli/internal/app.Version={{.Version}}"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: gram
    repository:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://app.getgram.ai
    description: The Gram CLI for interacting with the Gram Platform
    license: Apache-2.0
    test: |
      system "#{bin}/gram --version"

  - name: gram@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    repository:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://app.getgram.ai
    description: The Gram CLI for interacting with the Gram Platform
    license: Apache-2.0
    test: |
      system "#{bin}/gram --version"

# TODO: Implement Chocolateys release. Some transient 504 Gateway Timeouts can
# cause the entire release to fail and must be handled.
# chocolateys:
#   - name: gram
#     title: Gram CLI
#     authors: Speakeasy Inc
#     project_url: https://github.com/speakeasy-api/gram
#     url_template: "https://github.com/speakeasy-api/gram/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     copyright: 2025 Speakeasy, Inc
#     license_url: https://github.com/speakeasy-api/gram/blob/main/LICENSE
#     project_source_url: https://github.com/speakeasy-api/gram
#     docs_url: https://docs.getgram.ai
#     bug_tracker_url: https://github.com/speakeasy-api/gram/issues
#     tags: openapi api speakeasy gram tools agents llm client-libraries
#     summary: Everything you need to build powerful integrations for agents and LLMs.
#     description: |-
#       A command line interface for the Gram platform. Get started at https://docs.getgram.ai/
#       Bring the functionality of Gram into your development workflow. It can be run locally or in your CI/CD pipeline.
#     release_notes: "https://github.com/speakeasy-api/gram/releases/tag/v{{ .Version }}"
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://push.chocolatey.org/"
# winget:
#   - name: gram
#     publisher: Gram
#     short_description: Everything you need to build powerful integrations for agents and LLMs.
#     license_url: https://github.com/speakeasy-api/gram/blob/main/LICENSE
#     license: "elastic"
#     publisher_url: https://app.getgram.ai
#     publisher_support_url: https://github.com/speakeasy-api/gram/issues
#     homepage: https://app.getgram.ai
#     description: |-
#       A command line interface for the Gram platform. Get started at https://docs.getgram.ai/
#       Bring the functionality of Gram into your development workflow. It can be run locally or in your CI/CD pipeline.
#     copyright: 2025 Speakeasy, Inc
#     skip_upload: auto
#     release_notes: "https://github.com/speakeasy-api/gram/releases/tag/v{{ .Version }}"
#     release_notes_url: "https://github.com/speakeasy-api/gram/releases/tag/v{{ .Version }}"

#     repository:
#       owner: speakeasy-api
#       name: winget-pkgs
#       branch: "gram-{{.Version}}"
#       pull_request:
#         enabled: true
#         draft: false
#         base:
#           owner: microsoft
#           name: winget-pkgs
#           branch: main
