packages:
  - client/*
  - sdks/*
  - ts-framework/*
  - server
  - cli
  - functions
  - docs
  # These templates fail to build because they are templates and not actual projects, so we exclude them from the workspace.
  - "!ts-framework/create-function/gram-template-gram"
  - "!ts-framework/create-function/gram-template-mcp"

catalog:
  "@ai-sdk/openai": ^1.3.4
  "@tanstack/react-query": ^5.89.0
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9
  ai: ^4.0.52
  typescript: 5.9.2

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - bun
  - esbuild
  - sharp
