packages:
  - client/*
  - sdks/*
  - ts-framework/*
  - ts-framework/create-function/*
  - '!ts-framework/create-function/gram-template-*'
  - server
  - cli
  - functions
  - docs
  - evaluation

catalog:
  '@ai-sdk/openai': ^1.3.4
  '@modelcontextprotocol/sdk': ^1.20.1
  '@tanstack/react-query': ^5.90.10
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  ai: ^4.0.52
  typescript: 5.9.3

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@speakeasy-api/moonshine'

onlyBuiltDependencies:
  - bun
  - esbuild
  - sharp
