packages:
  - client/*
  - sdks/*
  - server

catalog:
  '@ai-sdk/openai': ^1.3.4
  '@tanstack/react-query': ^5.89.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  ai: ^4.0.52
  typescript: ^5.9.2

onlyBuiltDependencies:
  - bun
  - esbuild
