packages:
  - client/*
  - sdks/*

catalog:
  '@ai-sdk/openai': ^2.0.27
  '@tanstack/react-query': ^5.87.1
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  ai: ^5.0.37
  typescript: ^5.9.2

onlyBuiltDependencies:
  - bun
  - esbuild
