packages:
  - client/*
  - sdks/*
catalog:
  '@ai-sdk/openai': ^1.3.20
  '@tanstack/react-query': ^5.74.7
  typescript: ^5.8.3
  ai: ^4.3.10
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bun
  - esbuild
ignoredBuiltDependencies:
  - core-js
