packages:
  - client/*
  - sdks/*
  - ts-framework/*
  - ts-framework/create-function/*
  - server
  - cli
  - functions
  - docs

catalog:
  '@ai-sdk/openai': ^2.0.0
  '@ai-sdk/react': ^2.0.0
  '@ai-sdk/ui-utils': ^1.2.0
  '@modelcontextprotocol/sdk': ^1.20.1
  '@tanstack/react-query': ^5.89.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  ai: 5.0.66
  typescript: 5.9.2

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
- "@speakeasy-api/moonshine"

onlyBuiltDependencies:
  - bun
  - esbuild
  - sharp
