packages:
  - client/*
  - sdks/*
  - ts-framework/*
  - ts-framework/create-function/*
  - '!ts-framework/create-function/gram-template-*'
  - server
  - cli
  - functions
  - docs
  - evaluation
  - elements

catalog:
  '@ai-sdk/openai': ^2.0.0
  '@ai-sdk/react': ^2.0.118
  '@ai-sdk/ui-utils': ^1.2.0
  '@modelcontextprotocol/sdk': ^1.20.1
  '@tanstack/react-query': 5.90.10
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@assistant-ui/react': ^0.11.0
  ai: 5.0.66
  typescript: 5.9.3

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - 'react-router'
  - '@speakeasy-api/moonshine'
  - '@chromatic-com/storybook'

onlyBuiltDependencies:
  - bun
  - esbuild
  - sharp

overrides:
  glob@>=10.0 <10.5.0: 10.5.0
