#!/usr/bin/env bash

set -e

missing_tools=false
mise_installed=true
docker_installed=true

check_command() {
    local cmd=$1
    local var_name="${cmd}_installed"

    if ! command -v "$cmd" &> /dev/null; then
        missing_tools=true
        eval "$var_name=false"
    fi
}

check_command "mise"
check_command "docker"

if [ $missing_tools = true ]; then
    echo "# Missing tools:"

    if [ $mise_installed = false ]; then
      echo "## Mise:"
      echo "Install it from here: https://mise.jdx.dev/"
      echo "- Make sure to update your .zprofile (zsh), .profile (bash), ..."
      echo "- Additionaly enable completions for better DX: https://mise.jdx.dev/installing-mise.html#autocompletion"
    fi

    if [ $docker_installed = false ]; then
      echo "## Docker:"
      echo "Install docker: https://www.docker.com/"
    fi

    exit 1
fi

echo -e "\n⏳ Installing tools"
mise install

echo -e "\n⏳ Installing dependencies"
mise run install

echo -e "\n⏳ Updating VS Code and Cursor editor settings"
mise run install:vscode

echo -e "\n⏳ Starting infra"
mise infra:start

echo -e "\n⏳ Running migrations"
mise db:migrate

echo -e "\n✅ All set up!"
echo "Want me to start the server (\`mise w \"start:*\" --restart\`)?"
echo -n "[y/N] "
read -r answer
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
if [ "$answer" = "y" ]; then
  exec mise w "start:*" --restart
fi
