// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatAnalysisEvaluation struct {
	ID             uuid.UUID
	OrganizationID string
	ProjectID      uuid.UUID
	ChatID         uuid.UUID
	SessionID      string
	Judge          string
	ObservedAt     pgtype.Timestamptz
	State          string
	ReservedOn     pgtype.Date
	Attempts       int32
	LastError      pgtype.Text
	ScoredAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ChatAnalysisSetting struct {
	OrganizationID string
	Judge          string
	Enabled        bool
	DailyCap       int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
