edition = "2024";

package gram.authz.v1;

import "gcp/pubsub/v1/options.proto";

option go_package = "github.com/speakeasy-api/gram/infra/gen/gram/authz/v1;authzv1";

message ChallengeCHWriter {
  option (gcp.pubsub.v1.subscription) = {
    topic: "gram.authz.v1.Challenge"
    ack_deadline: {seconds: 60}
    retention: {
      seconds: 604800 /* 7 days */
    }
    retain_acked_messages: true
    retry_policy: {
      minimum_backoff: {seconds: 10}
      maximum_backoff: {seconds: 600}
    }
    dead_letter: {max_delivery_attempts: 10}
  };
}
