/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 432dce694cae
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { usageGetPeriodUsage } from "../funcs/usageGetPeriodUsage.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type GetPeriodUsageQueryData = components.PeriodUsage;

export function prefetchGetPeriodUsage(
  queryClient: QueryClient,
  client$: GramCore,
  request?: operations.GetPeriodUsageRequest | undefined,
  security?: operations.GetPeriodUsageSecurity | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildGetPeriodUsageQuery(
      client$,
      request,
      security,
      options,
    ),
  });
}

export function buildGetPeriodUsageQuery(
  client$: GramCore,
  request?: operations.GetPeriodUsageRequest | undefined,
  security?: operations.GetPeriodUsageSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<GetPeriodUsageQueryData>;
} {
  return {
    queryKey: queryKeyGetPeriodUsage({
      gramSession: request?.gramSession,
      gramProject: request?.gramProject,
    }),
    queryFn: async function getPeriodUsageQueryFn(
      ctx,
    ): Promise<GetPeriodUsageQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(usageGetPeriodUsage(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyGetPeriodUsage(
  parameters: {
    gramSession?: string | undefined;
    gramProject?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "usage", "getPeriodUsage", parameters];
}
