/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  ConfigureRoleProvisioningRequestBody,
  ConfigureRoleProvisioningRequestBody$Outbound,
  ConfigureRoleProvisioningRequestBody$outboundSchema,
} from "../components/configureroleprovisioningrequestbody.js";

export type ConfigureRoleProvisioningSecurity = {
  sessionHeaderGramSession?: string | undefined;
};

export type ConfigureRoleProvisioningRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  configureRoleProvisioningRequestBody: ConfigureRoleProvisioningRequestBody;
};

/** @internal */
export type ConfigureRoleProvisioningSecurity$Outbound = {
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const ConfigureRoleProvisioningSecurity$outboundSchema: z.ZodMiniType<
  ConfigureRoleProvisioningSecurity$Outbound,
  ConfigureRoleProvisioningSecurity
> = z.pipe(
  z.object({
    sessionHeaderGramSession: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function configureRoleProvisioningSecurityToJSON(
  configureRoleProvisioningSecurity: ConfigureRoleProvisioningSecurity,
): string {
  return JSON.stringify(
    ConfigureRoleProvisioningSecurity$outboundSchema.parse(
      configureRoleProvisioningSecurity,
    ),
  );
}

/** @internal */
export type ConfigureRoleProvisioningRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  ConfigureRoleProvisioningRequestBody:
    ConfigureRoleProvisioningRequestBody$Outbound;
};

/** @internal */
export const ConfigureRoleProvisioningRequest$outboundSchema: z.ZodMiniType<
  ConfigureRoleProvisioningRequest$Outbound,
  ConfigureRoleProvisioningRequest
> = z.pipe(
  z.object({
    gramSession: z.optional(z.string()),
    configureRoleProvisioningRequestBody:
      ConfigureRoleProvisioningRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      configureRoleProvisioningRequestBody:
        "ConfigureRoleProvisioningRequestBody",
    });
  }),
);

export function configureRoleProvisioningRequestToJSON(
  configureRoleProvisioningRequest: ConfigureRoleProvisioningRequest,
): string {
  return JSON.stringify(
    ConfigureRoleProvisioningRequest$outboundSchema.parse(
      configureRoleProvisioningRequest,
    ),
  );
}
