/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetWidgetPresetSecurity = {
  projectSlugHeaderGramProject?: string | undefined;
  sessionHeaderGramSession?: string | undefined;
};

export type GetWidgetPresetRequest = {
  /**
   * The page whose preset to get
   */
  page: string;
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
};

/** @internal */
export type GetWidgetPresetSecurity$Outbound = {
  "project_slug_header_Gram-Project"?: string | undefined;
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const GetWidgetPresetSecurity$outboundSchema: z.ZodMiniType<
  GetWidgetPresetSecurity$Outbound,
  GetWidgetPresetSecurity
> = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.optional(z.string()),
    sessionHeaderGramSession: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function getWidgetPresetSecurityToJSON(
  getWidgetPresetSecurity: GetWidgetPresetSecurity,
): string {
  return JSON.stringify(
    GetWidgetPresetSecurity$outboundSchema.parse(getWidgetPresetSecurity),
  );
}

/** @internal */
export type GetWidgetPresetRequest$Outbound = {
  page: string;
  "Gram-Session"?: string | undefined;
  "Gram-Project"?: string | undefined;
};

/** @internal */
export const GetWidgetPresetRequest$outboundSchema: z.ZodMiniType<
  GetWidgetPresetRequest$Outbound,
  GetWidgetPresetRequest
> = z.pipe(
  z.object({
    page: z.string(),
    gramSession: z.optional(z.string()),
    gramProject: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramProject: "Gram-Project",
    });
  }),
);

export function getWidgetPresetRequestToJSON(
  getWidgetPresetRequest: GetWidgetPresetRequest,
): string {
  return JSON.stringify(
    GetWidgetPresetRequest$outboundSchema.parse(getWidgetPresetRequest),
  );
}
