/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListOtelDestinationsSecurityOption1 = {
  projectSlugHeaderGramProject: string;
  sessionHeaderGramSession: string;
};

export type ListOtelDestinationsSecurityOption2 = {
  apikeyHeaderGramKey: string;
  projectSlugHeaderGramProject: string;
};

export type ListOtelDestinationsSecurity = {
  option1?: ListOtelDestinationsSecurityOption1 | undefined;
  option2?: ListOtelDestinationsSecurityOption2 | undefined;
};

export type ListOtelDestinationsRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * API Key header
   */
  gramKey?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
};

/** @internal */
export type ListOtelDestinationsSecurityOption1$Outbound = {
  "project_slug_header_Gram-Project": string;
  "session_header_Gram-Session": string;
};

/** @internal */
export const ListOtelDestinationsSecurityOption1$outboundSchema: z.ZodMiniType<
  ListOtelDestinationsSecurityOption1$Outbound,
  ListOtelDestinationsSecurityOption1
> = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.string(),
    sessionHeaderGramSession: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function listOtelDestinationsSecurityOption1ToJSON(
  listOtelDestinationsSecurityOption1: ListOtelDestinationsSecurityOption1,
): string {
  return JSON.stringify(
    ListOtelDestinationsSecurityOption1$outboundSchema.parse(
      listOtelDestinationsSecurityOption1,
    ),
  );
}

/** @internal */
export type ListOtelDestinationsSecurityOption2$Outbound = {
  "apikey_header_Gram-Key": string;
  "project_slug_header_Gram-Project": string;
};

/** @internal */
export const ListOtelDestinationsSecurityOption2$outboundSchema: z.ZodMiniType<
  ListOtelDestinationsSecurityOption2$Outbound,
  ListOtelDestinationsSecurityOption2
> = z.pipe(
  z.object({
    apikeyHeaderGramKey: z.string(),
    projectSlugHeaderGramProject: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      apikeyHeaderGramKey: "apikey_header_Gram-Key",
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
    });
  }),
);

export function listOtelDestinationsSecurityOption2ToJSON(
  listOtelDestinationsSecurityOption2: ListOtelDestinationsSecurityOption2,
): string {
  return JSON.stringify(
    ListOtelDestinationsSecurityOption2$outboundSchema.parse(
      listOtelDestinationsSecurityOption2,
    ),
  );
}

/** @internal */
export type ListOtelDestinationsSecurity$Outbound = {
  Option1?: ListOtelDestinationsSecurityOption1$Outbound | undefined;
  Option2?: ListOtelDestinationsSecurityOption2$Outbound | undefined;
};

/** @internal */
export const ListOtelDestinationsSecurity$outboundSchema: z.ZodMiniType<
  ListOtelDestinationsSecurity$Outbound,
  ListOtelDestinationsSecurity
> = z.pipe(
  z.object({
    option1: z.optional(
      z.lazy(() => ListOtelDestinationsSecurityOption1$outboundSchema),
    ),
    option2: z.optional(
      z.lazy(() => ListOtelDestinationsSecurityOption2$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      option1: "Option1",
      option2: "Option2",
    });
  }),
);

export function listOtelDestinationsSecurityToJSON(
  listOtelDestinationsSecurity: ListOtelDestinationsSecurity,
): string {
  return JSON.stringify(
    ListOtelDestinationsSecurity$outboundSchema.parse(
      listOtelDestinationsSecurity,
    ),
  );
}

/** @internal */
export type ListOtelDestinationsRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  "Gram-Key"?: string | undefined;
  "Gram-Project"?: string | undefined;
};

/** @internal */
export const ListOtelDestinationsRequest$outboundSchema: z.ZodMiniType<
  ListOtelDestinationsRequest$Outbound,
  ListOtelDestinationsRequest
> = z.pipe(
  z.object({
    gramSession: z.optional(z.string()),
    gramKey: z.optional(z.string()),
    gramProject: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramKey: "Gram-Key",
      gramProject: "Gram-Project",
    });
  }),
);

export function listOtelDestinationsRequestToJSON(
  listOtelDestinationsRequest: ListOtelDestinationsRequest,
): string {
  return JSON.stringify(
    ListOtelDestinationsRequest$outboundSchema.parse(
      listOtelDestinationsRequest,
    ),
  );
}
