/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  UpdateQueryRequestBody,
  UpdateQueryRequestBody$Outbound,
  UpdateQueryRequestBody$outboundSchema,
} from "../components/updatequeryrequestbody.js";

export type UpdateExploreQuerySecurity = {
  projectSlugHeaderGramProject?: string | undefined;
  sessionHeaderGramSession?: string | undefined;
};

export type UpdateExploreQueryRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
  updateQueryRequestBody: UpdateQueryRequestBody;
};

/** @internal */
export type UpdateExploreQuerySecurity$Outbound = {
  "project_slug_header_Gram-Project"?: string | undefined;
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const UpdateExploreQuerySecurity$outboundSchema: z.ZodMiniType<
  UpdateExploreQuerySecurity$Outbound,
  UpdateExploreQuerySecurity
> = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.optional(z.string()),
    sessionHeaderGramSession: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function updateExploreQuerySecurityToJSON(
  updateExploreQuerySecurity: UpdateExploreQuerySecurity,
): string {
  return JSON.stringify(
    UpdateExploreQuerySecurity$outboundSchema.parse(updateExploreQuerySecurity),
  );
}

/** @internal */
export type UpdateExploreQueryRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  "Gram-Project"?: string | undefined;
  UpdateQueryRequestBody: UpdateQueryRequestBody$Outbound;
};

/** @internal */
export const UpdateExploreQueryRequest$outboundSchema: z.ZodMiniType<
  UpdateExploreQueryRequest$Outbound,
  UpdateExploreQueryRequest
> = z.pipe(
  z.object({
    gramSession: z.optional(z.string()),
    gramProject: z.optional(z.string()),
    updateQueryRequestBody: UpdateQueryRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramProject: "Gram-Project",
      updateQueryRequestBody: "UpdateQueryRequestBody",
    });
  }),
);

export function updateExploreQueryRequestToJSON(
  updateExploreQueryRequest: UpdateExploreQueryRequest,
): string {
  return JSON.stringify(
    UpdateExploreQueryRequest$outboundSchema.parse(updateExploreQueryRequest),
  );
}
