// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-api/gram/responses/internal/utils"
)

// AllowedToolsParamType - The tool choice type. Always `allowed_tools`.
type AllowedToolsParamType string

const (
	AllowedToolsParamTypeAllowedTools AllowedToolsParamType = "allowed_tools"
)

func (e AllowedToolsParamType) ToPointer() *AllowedToolsParamType {
	return &e
}
func (e *AllowedToolsParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allowed_tools":
		*e = AllowedToolsParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AllowedToolsParamType: %v", v)
	}
}

type AllowedToolsParam struct {
	// The tool choice type. Always `allowed_tools`.
	Type *AllowedToolsParamType `default:"allowed_tools" json:"type"`
	// The list of tools that are permitted for this request.
	Tools []SpecificToolChoiceParam `json:"tools"`
	Mode  *ToolChoiceValueEnum      `json:"mode,omitzero"`
}

func (a AllowedToolsParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AllowedToolsParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AllowedToolsParam) GetType() *AllowedToolsParamType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AllowedToolsParam) GetTools() []SpecificToolChoiceParam {
	if a == nil {
		return []SpecificToolChoiceParam{}
	}
	return a.Tools
}

func (a *AllowedToolsParam) GetMode() *ToolChoiceValueEnum {
	if a == nil {
		return nil
	}
	return a.Mode
}
