// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-api/gram/responses/internal/utils"
)

// ResponseContentPartAddedStreamingEventType - The type of the event, always `response.content_part.added`.
type ResponseContentPartAddedStreamingEventType string

const (
	ResponseContentPartAddedStreamingEventTypeResponseContentPartAdded ResponseContentPartAddedStreamingEventType = "response.content_part.added"
)

func (e ResponseContentPartAddedStreamingEventType) ToPointer() *ResponseContentPartAddedStreamingEventType {
	return &e
}
func (e *ResponseContentPartAddedStreamingEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response.content_part.added":
		*e = ResponseContentPartAddedStreamingEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseContentPartAddedStreamingEventType: %v", v)
	}
}

type ResponseContentPartAddedStreamingEventPartType string

const (
	ResponseContentPartAddedStreamingEventPartTypeInputTextContent     ResponseContentPartAddedStreamingEventPartType = "InputTextContent"
	ResponseContentPartAddedStreamingEventPartTypeOutputTextContent    ResponseContentPartAddedStreamingEventPartType = "OutputTextContent"
	ResponseContentPartAddedStreamingEventPartTypeTextContent          ResponseContentPartAddedStreamingEventPartType = "TextContent"
	ResponseContentPartAddedStreamingEventPartTypeSummaryTextContent   ResponseContentPartAddedStreamingEventPartType = "SummaryTextContent"
	ResponseContentPartAddedStreamingEventPartTypeReasoningTextContent ResponseContentPartAddedStreamingEventPartType = "ReasoningTextContent"
	ResponseContentPartAddedStreamingEventPartTypeRefusalContent       ResponseContentPartAddedStreamingEventPartType = "RefusalContent"
	ResponseContentPartAddedStreamingEventPartTypeInputImageContent    ResponseContentPartAddedStreamingEventPartType = "InputImageContent"
	ResponseContentPartAddedStreamingEventPartTypeInputFileContent     ResponseContentPartAddedStreamingEventPartType = "InputFileContent"
)

// ResponseContentPartAddedStreamingEventPart - A content part that makes up an input or output item.
type ResponseContentPartAddedStreamingEventPart struct {
	InputTextContent     *InputTextContent     `queryParam:"inline" union:"member"`
	OutputTextContent    *OutputTextContent    `queryParam:"inline" union:"member"`
	TextContent          *TextContent          `queryParam:"inline" union:"member"`
	SummaryTextContent   *SummaryTextContent   `queryParam:"inline" union:"member"`
	ReasoningTextContent *ReasoningTextContent `queryParam:"inline" union:"member"`
	RefusalContent       *RefusalContent       `queryParam:"inline" union:"member"`
	InputImageContent    *InputImageContent    `queryParam:"inline" union:"member"`
	InputFileContent     *InputFileContent     `queryParam:"inline" union:"member"`

	Type ResponseContentPartAddedStreamingEventPartType
}

func CreateResponseContentPartAddedStreamingEventPartInputTextContent(inputTextContent InputTextContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeInputTextContent

	return ResponseContentPartAddedStreamingEventPart{
		InputTextContent: &inputTextContent,
		Type:             typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartOutputTextContent(outputTextContent OutputTextContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeOutputTextContent

	return ResponseContentPartAddedStreamingEventPart{
		OutputTextContent: &outputTextContent,
		Type:              typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartTextContent(textContent TextContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeTextContent

	return ResponseContentPartAddedStreamingEventPart{
		TextContent: &textContent,
		Type:        typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartSummaryTextContent(summaryTextContent SummaryTextContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeSummaryTextContent

	return ResponseContentPartAddedStreamingEventPart{
		SummaryTextContent: &summaryTextContent,
		Type:               typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartReasoningTextContent(reasoningTextContent ReasoningTextContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeReasoningTextContent

	return ResponseContentPartAddedStreamingEventPart{
		ReasoningTextContent: &reasoningTextContent,
		Type:                 typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartRefusalContent(refusalContent RefusalContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeRefusalContent

	return ResponseContentPartAddedStreamingEventPart{
		RefusalContent: &refusalContent,
		Type:           typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartInputImageContent(inputImageContent InputImageContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeInputImageContent

	return ResponseContentPartAddedStreamingEventPart{
		InputImageContent: &inputImageContent,
		Type:              typ,
	}
}

func CreateResponseContentPartAddedStreamingEventPartInputFileContent(inputFileContent InputFileContent) ResponseContentPartAddedStreamingEventPart {
	typ := ResponseContentPartAddedStreamingEventPartTypeInputFileContent

	return ResponseContentPartAddedStreamingEventPart{
		InputFileContent: &inputFileContent,
		Type:             typ,
	}
}

func (u *ResponseContentPartAddedStreamingEventPart) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var inputTextContent InputTextContent = InputTextContent{}
	if err := utils.UnmarshalJSON(data, &inputTextContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeInputTextContent,
			Value: &inputTextContent,
		})
	}

	var outputTextContent OutputTextContent = OutputTextContent{}
	if err := utils.UnmarshalJSON(data, &outputTextContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeOutputTextContent,
			Value: &outputTextContent,
		})
	}

	var textContent TextContent = TextContent{}
	if err := utils.UnmarshalJSON(data, &textContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeTextContent,
			Value: &textContent,
		})
	}

	var summaryTextContent SummaryTextContent = SummaryTextContent{}
	if err := utils.UnmarshalJSON(data, &summaryTextContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeSummaryTextContent,
			Value: &summaryTextContent,
		})
	}

	var reasoningTextContent ReasoningTextContent = ReasoningTextContent{}
	if err := utils.UnmarshalJSON(data, &reasoningTextContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeReasoningTextContent,
			Value: &reasoningTextContent,
		})
	}

	var refusalContent RefusalContent = RefusalContent{}
	if err := utils.UnmarshalJSON(data, &refusalContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeRefusalContent,
			Value: &refusalContent,
		})
	}

	var inputImageContent InputImageContent = InputImageContent{}
	if err := utils.UnmarshalJSON(data, &inputImageContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeInputImageContent,
			Value: &inputImageContent,
		})
	}

	var inputFileContent InputFileContent = InputFileContent{}
	if err := utils.UnmarshalJSON(data, &inputFileContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseContentPartAddedStreamingEventPartTypeInputFileContent,
			Value: &inputFileContent,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ResponseContentPartAddedStreamingEventPart", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ResponseContentPartAddedStreamingEventPart", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ResponseContentPartAddedStreamingEventPartType)
	switch best.Type {
	case ResponseContentPartAddedStreamingEventPartTypeInputTextContent:
		u.InputTextContent = best.Value.(*InputTextContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeOutputTextContent:
		u.OutputTextContent = best.Value.(*OutputTextContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeTextContent:
		u.TextContent = best.Value.(*TextContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeSummaryTextContent:
		u.SummaryTextContent = best.Value.(*SummaryTextContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeReasoningTextContent:
		u.ReasoningTextContent = best.Value.(*ReasoningTextContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeRefusalContent:
		u.RefusalContent = best.Value.(*RefusalContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeInputImageContent:
		u.InputImageContent = best.Value.(*InputImageContent)
		return nil
	case ResponseContentPartAddedStreamingEventPartTypeInputFileContent:
		u.InputFileContent = best.Value.(*InputFileContent)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ResponseContentPartAddedStreamingEventPart", string(data))
}

func (u ResponseContentPartAddedStreamingEventPart) MarshalJSON() ([]byte, error) {
	if u.InputTextContent != nil {
		return utils.MarshalJSON(u.InputTextContent, "", true)
	}

	if u.OutputTextContent != nil {
		return utils.MarshalJSON(u.OutputTextContent, "", true)
	}

	if u.TextContent != nil {
		return utils.MarshalJSON(u.TextContent, "", true)
	}

	if u.SummaryTextContent != nil {
		return utils.MarshalJSON(u.SummaryTextContent, "", true)
	}

	if u.ReasoningTextContent != nil {
		return utils.MarshalJSON(u.ReasoningTextContent, "", true)
	}

	if u.RefusalContent != nil {
		return utils.MarshalJSON(u.RefusalContent, "", true)
	}

	if u.InputImageContent != nil {
		return utils.MarshalJSON(u.InputImageContent, "", true)
	}

	if u.InputFileContent != nil {
		return utils.MarshalJSON(u.InputFileContent, "", true)
	}

	return nil, errors.New("could not marshal union type ResponseContentPartAddedStreamingEventPart: all fields are null")
}

// ResponseContentPartAddedStreamingEvent - A streaming event that indicated a content part was added.
type ResponseContentPartAddedStreamingEvent struct {
	// The type of the event, always `response.content_part.added`.
	Type *ResponseContentPartAddedStreamingEventType `default:"response.content_part.added" json:"type"`
	// The sequence number of the event that was emitted.
	SequenceNumber int64 `json:"sequence_number"`
	// The ID of the item that was updated.
	ItemID string `json:"item_id"`
	// The index of the output item that was updated.
	OutputIndex int64 `json:"output_index"`
	// The index of the content part that was added.
	ContentIndex int64 `json:"content_index"`
	// A content part that makes up an input or output item.
	Part ResponseContentPartAddedStreamingEventPart `json:"part"`
}

func (r ResponseContentPartAddedStreamingEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseContentPartAddedStreamingEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResponseContentPartAddedStreamingEvent) GetType() *ResponseContentPartAddedStreamingEventType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *ResponseContentPartAddedStreamingEvent) GetSequenceNumber() int64 {
	if r == nil {
		return 0
	}
	return r.SequenceNumber
}

func (r *ResponseContentPartAddedStreamingEvent) GetItemID() string {
	if r == nil {
		return ""
	}
	return r.ItemID
}

func (r *ResponseContentPartAddedStreamingEvent) GetOutputIndex() int64 {
	if r == nil {
		return 0
	}
	return r.OutputIndex
}

func (r *ResponseContentPartAddedStreamingEvent) GetContentIndex() int64 {
	if r == nil {
		return 0
	}
	return r.ContentIndex
}

func (r *ResponseContentPartAddedStreamingEvent) GetPart() ResponseContentPartAddedStreamingEventPart {
	if r == nil {
		return ResponseContentPartAddedStreamingEventPart{}
	}
	return r.Part
}
