#!/usr/bin/env bash

#MISE description="Configure rootless Podman (storage, network, API socket) for local development"
#MISE hide=true

set -euo pipefail

REPO_ROOT="${MISE_PROJECT_ROOT:-$(git rev-parse --show-toplevel)}"

uid="$(id -u)"

# --- Prerequisites ----------------------------------------------------------

if ! command -v podman >/dev/null 2>&1; then
    echo "❌ podman not found on PATH. Run 'mise install' first (podman is installed via mise.toml [tools])." >&2
    exit 1
fi

# Rootless podman needs setuid newuidmap/newgidmap plus subordinate id ranges
# for the current user. Root (cloud sandboxes) runs rootful and needs neither.
# ./zero performs this same check up front; repeated here so the task is safe
# to run standalone. This is the ONLY step that ever needs sudo, and it is
# printed — never executed.
if [ "$uid" -ne 0 ]; then
    missing=""
    command -v newuidmap >/dev/null 2>&1 && command -v newgidmap >/dev/null 2>&1 || missing="uidmap"
    grep -q "^$(id -un):" /etc/subuid 2>/dev/null || missing="$missing subuid"
    grep -q "^$(id -un):" /etc/subgid 2>/dev/null || missing="$missing subgid"

    if [ -n "$missing" ]; then
        cat >&2 << 'EOF'
❌ Rootless Podman needs a ONE-TIME host setup (requires sudo). Run:

    sudo apt-get update && sudo apt-get install -y uidmap
    sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 "$(id -un)"

then re-run ./zero. (If you previously ran podman on this machine, also run: podman system migrate)
EOF
        exit 1
    fi
fi

# --- Config file generation -------------------------------------------------

# The podman-static bundle ships its helper binaries (conmon, crun, netavark,
# aardvark-dns, pasta, fuse-overlayfs) under a versioned mise install prefix,
# so the generated config embeds that prefix and must be regenerated on
# version bumps — ./zero re-runs this task every session, which covers that.
podman_bin="$(mise which podman 2>/dev/null || command -v podman)"
PODMAN_PREFIX="$(dirname "$(dirname "$podman_bin")")"

if [ "$uid" -eq 0 ]; then
    # Rootful podman does not read ~/.config/containers. We are root, so
    # writing /etc/containers needs no escalation.
    conf_dir="/etc/containers"
else
    conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/containers"
fi
mkdir -p "$conf_dir"

# Writes $2 to $1 unless a file we did not generate is already there.
write_conf() {
    local path="$1" content="$2"
    if [ -f "$path" ] && ! head -n 1 "$path" | grep -qF "generated by gram zero"; then
        echo "⚠️  $path already exists and was not generated by gram zero; leaving it untouched." >&2
        return 0
    fi
    printf '%s\n' "$content" > "$path"
    echo "✅ Wrote $path"
}

write_conf "$conf_dir/containers.conf" "# generated by gram zero
[containers]

[engine]
cgroup_manager = \"cgroupfs\"
events_logger = \"file\"
runtime = \"crun\"
# REQUIRED: helper_binaries_dir does NOT cover conmon — without conmon_path
# podman fails with \"could not find a working conmon binary\".
conmon_path = [\"$PODMAN_PREFIX/lib/podman/conmon\"]
helper_binaries_dir = [\"$PODMAN_PREFIX/lib/podman\", \"$PODMAN_PREFIX/bin\"]

[engine.runtimes]
crun = [\"$PODMAN_PREFIX/bin/crun\"]

[network]
network_backend = \"netavark\"
default_rootless_network_cmd = \"pasta\""

# fuse-overlayfs when /dev/fuse exists (native overlay cannot nest on the
# sandbox's own overlayfs); slow-but-correct vfs otherwise.
if [ -e /dev/fuse ]; then
    write_conf "$conf_dir/storage.conf" "# generated by gram zero
[storage]
driver = \"overlay\"

[storage.options.overlay]
mount_program = \"$PODMAN_PREFIX/bin/fuse-overlayfs\""
else
    echo "⚠️  /dev/fuse not present: falling back to the vfs storage driver (slow)." >&2
    write_conf "$conf_dir/storage.conf" "# generated by gram zero
[storage]
driver = \"vfs\""
fi

# Required or short image names like redis:6.2-alpine fail to resolve.
write_conf "$conf_dir/registries.conf" '# generated by gram zero
unqualified-search-registries = ["docker.io"]'

# JSON cannot carry our generated-by header; only write when absent (any
# pre-existing policy means podman already works).
if [ ! -f "$conf_dir/policy.json" ]; then
    printf '%s\n' '{"default":[{"type":"insecureAcceptAnything"}]}' > "$conf_dir/policy.json"
    echo "✅ Wrote $conf_dir/policy.json"
fi

# --- Self-check, API socket, image pre-builds -------------------------------

if ! podman info > /dev/null; then
    echo "❌ 'podman info' failed — podman is installed but not functional with the generated config above." >&2
    exit 1
fi
echo "✅ podman is functional ($(podman info --format '{{.Store.GraphDriverName}} storage, rootless={{.Host.Security.Rootless}}'))"

compose_lib="$REPO_ROOT/local/lib/compose.sh"
if [ -f "$compose_lib" ]; then
    export GRAM_REPO_ROOT="$REPO_ROOT"
    # shellcheck source=/dev/null
    . "$compose_lib"
    ensure_podman_socket
    ensure_local_images
else
    echo "⚠️  $compose_lib not found; skipped API socket startup and local image pre-builds." >&2
fi
