/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
/** @internal */
export const FetchOpenAPIv3FromURLForm2$outboundSchema = z.object({
  url: z.string(),
});
export function fetchOpenAPIv3FromURLForm2ToJSON(fetchOpenAPIv3FromURLForm2) {
  return JSON.stringify(
    FetchOpenAPIv3FromURLForm2$outboundSchema.parse(fetchOpenAPIv3FromURLForm2),
  );
}
//# sourceMappingURL=fetchopenapiv3fromurlform2.js.map
