/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
/** @internal */
export const HookPromptData$outboundSchema = z.object({
  text: z.optional(z.string()),
});
export function hookPromptDataToJSON(hookPromptData) {
  return JSON.stringify(HookPromptData$outboundSchema.parse(hookPromptData));
}
//# sourceMappingURL=hookpromptdata.js.map
