/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { TeamInvite$inboundSchema } from "./teaminvite.js";
/** @internal */
export const InviteMemberResult$inboundSchema = z.object({
  invite: TeamInvite$inboundSchema,
});
export function inviteMemberResultFromJSON(jsonString) {
  return safeParse(
    jsonString,
    (x) => InviteMemberResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InviteMemberResult' from JSON`,
  );
}
//# sourceMappingURL=invitememberresult.js.map
