/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 384019b10974
 */
import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { PaginationResponse$inboundSchema } from "./paginationresponse.js";
import { ToolExecutionLog$inboundSchema } from "./toolexecutionlog.js";
/** @internal */
export const ListToolExecutionLogsResult$inboundSchema = z.object({
  logs: z.array(ToolExecutionLog$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});
export function listToolExecutionLogsResultFromJSON(jsonString) {
  return safeParse(
    jsonString,
    (x) => ListToolExecutionLogsResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListToolExecutionLogsResult' from JSON`,
  );
}
//# sourceMappingURL=listtoolexecutionlogsresult.js.map
