/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
/** @internal */
export const RevokeAllClientSessionsRequestBody$outboundSchema = z.pipe(z.object({
    clientId: z.string(),
}), z.transform((v) => {
    return remap$(v, {
        clientId: "client_id",
    });
}));
export function revokeAllClientSessionsRequestBodyToJSON(revokeAllClientSessionsRequestBody) {
    return JSON.stringify(RevokeAllClientSessionsRequestBody$outboundSchema.parse(revokeAllClientSessionsRequestBody));
}
//# sourceMappingURL=revokeallclientsessionsrequestbody.js.map