/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { assistantsCreate } from "../funcs/assistantsCreate.js";
import { assistantsDelete } from "../funcs/assistantsDelete.js";
import { assistantsEnsureManaged } from "../funcs/assistantsEnsureManaged.js";
import { assistantsGet } from "../funcs/assistantsGet.js";
import { assistantsGetManaged } from "../funcs/assistantsGetManaged.js";
import { assistantsList } from "../funcs/assistantsList.js";
import { assistantsSendMessage } from "../funcs/assistantsSendMessage.js";
import { assistantsUpdate } from "../funcs/assistantsUpdate.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class Assistants extends ClientSDK {
    /**
     * createAssistant assistants
     *
     * @remarks
     * Create an assistant.
     */
    async create(request, security, options) {
        return unwrapAsync(assistantsCreate(this, request, security, options));
    }
    /**
     * deleteAssistant assistants
     *
     * @remarks
     * Delete an assistant.
     */
    async delete(request, security, options) {
        return unwrapAsync(assistantsDelete(this, request, security, options));
    }
    /**
     * ensureManagedAssistant assistants
     *
     * @remarks
     * Get the project's built-in Project Assistant, provisioning it on first access. Idempotent — safe to call on every sidebar open.
     */
    async ensureManaged(request, security, options) {
        return unwrapAsync(assistantsEnsureManaged(this, request, security, options));
    }
    /**
     * getAssistant assistants
     *
     * @remarks
     * Get an assistant by ID.
     */
    async get(request, security, options) {
        return unwrapAsync(assistantsGet(this, request, security, options));
    }
    /**
     * getManagedAssistant assistants
     *
     * @remarks
     * Get the project's built-in Project Assistant if it exists. Returns 404 when no managed assistant has been provisioned yet — call ensureManagedAssistant to create one.
     */
    async getManaged(request, security, options) {
        return unwrapAsync(assistantsGetManaged(this, request, security, options));
    }
    /**
     * listAssistants assistants
     *
     * @remarks
     * List assistants for the current project.
     */
    async list(request, security, options) {
        return unwrapAsync(assistantsList(this, request, security, options));
    }
    /**
     * sendMessage assistants
     *
     * @remarks
     * Send a message from the dashboard to an assistant as the calling user. Continue an existing conversation by passing its chat_id (from listChats), or omit chat_id to start a new conversation — the server mints and returns a fresh chat id. The reply is delivered asynchronously; poll the chat service (loadChat) to read it.
     */
    async sendMessage(request, security, options) {
        return unwrapAsync(assistantsSendMessage(this, request, security, options));
    }
    /**
     * updateAssistant assistants
     *
     * @remarks
     * Update an assistant.
     */
    async update(request, security, options) {
        return unwrapAsync(assistantsUpdate(this, request, security, options));
    }
}
//# sourceMappingURL=assistants.js.map