import { ClientSDK } from "../lib/sdks.js";
import { Access } from "./access.js";
import { AdminRemoteSessions } from "./adminremotesessions.js";
import { Agent } from "./agent.js";
import { AiIntegrations } from "./aiintegrations.js";
import { Assets } from "./assets.js";
import { AssistantMemories } from "./assistantmemories.js";
import { Assistants } from "./assistants.js";
import { Auditlogs } from "./auditlogs.js";
import { Auth } from "./auth.js";
import { Chat } from "./chat.js";
import { ChatSessions } from "./chatsessions.js";
import { CliAuth } from "./cliauth.js";
import { Collections } from "./collections.js";
import { Deployments } from "./deployments.js";
import { Domains } from "./domains.js";
import { Environments } from "./environments.js";
import { External } from "./external.js";
import { ExternalCredentials } from "./externalcredentials.js";
import { Features } from "./features.js";
import { Hooks } from "./hooks.js";
import { HooksServerNames } from "./hooksservernames.js";
import { Instances } from "./instances.js";
import { Integrations } from "./integrations.js";
import { Keys } from "./keys.js";
import { McpEndpoints } from "./mcpendpoints.js";
import { McpMetadata } from "./mcpmetadata.js";
import { McpRegistries } from "./mcpregistries.js";
import { McpServers } from "./mcpservers.js";
import { OrganizationRemoteSessionClients } from "./organizationremotesessionclients.js";
import { OrganizationRemoteSessionIssuers } from "./organizationremotesessionissuers.js";
import { OrganizationRemoteSessions } from "./organizationremotesessions.js";
import { Organizations } from "./organizations.js";
import { OtelForwarding } from "./otelforwarding.js";
import { Packages } from "./packages.js";
import { Plugins } from "./plugins.js";
import { Projects } from "./projects.js";
import { RemoteMcp } from "./remotemcp.js";
import { RemoteSessionClients } from "./remotesessionclients.js";
import { RemoteSessionIssuers } from "./remotesessionissuers.js";
import { RemoteSessions } from "./remotesessions.js";
import { Resources } from "./resources.js";
import { Risk } from "./risk.js";
import { Telemetry } from "./telemetry.js";
import { Templates } from "./templates.js";
import { Tools } from "./tools.js";
import { Toolsets } from "./toolsets.js";
import { Triggers } from "./triggers.js";
import { TunneledMcp } from "./tunneledmcp.js";
import { Usage } from "./usage.js";
import { UserSessionClients } from "./usersessionclients.js";
import { UserSessionConsents } from "./usersessionconsents.js";
import { UserSessionIssuers } from "./usersessionissuers.js";
import { UserSessions } from "./usersessions.js";
import { Variations } from "./variations.js";
export declare class Gram extends ClientSDK {
  private _access?;
  get access(): Access;
  private _adminRemoteSessions?;
  get adminRemoteSessions(): AdminRemoteSessions;
  private _agent?;
  get agent(): Agent;
  private _aiIntegrations?;
  get aiIntegrations(): AiIntegrations;
  private _assets?;
  get assets(): Assets;
  private _assistantMemories?;
  get assistantMemories(): AssistantMemories;
  private _assistants?;
  get assistants(): Assistants;
  private _auditlogs?;
  get auditlogs(): Auditlogs;
  private _auth?;
  get auth(): Auth;
  private _chat?;
  get chat(): Chat;
  private _chatSessions?;
  get chatSessions(): ChatSessions;
  private _cliAuth?;
  get cliAuth(): CliAuth;
  private _collections?;
  get collections(): Collections;
  private _deployments?;
  get deployments(): Deployments;
  private _domains?;
  get domains(): Domains;
  private _environments?;
  get environments(): Environments;
  private _external?;
  get external(): External;
  private _externalCredentials?;
  get externalCredentials(): ExternalCredentials;
  private _hooks?;
  get hooks(): Hooks;
  private _hooksServerNames?;
  get hooksServerNames(): HooksServerNames;
  private _instances?;
  get instances(): Instances;
  private _integrations?;
  get integrations(): Integrations;
  private _keys?;
  get keys(): Keys;
  private _mcpEndpoints?;
  get mcpEndpoints(): McpEndpoints;
  private _mcpMetadata?;
  get mcpMetadata(): McpMetadata;
  private _mcpRegistries?;
  get mcpRegistries(): McpRegistries;
  private _mcpServers?;
  get mcpServers(): McpServers;
  private _organizationRemoteSessionClients?;
  get organizationRemoteSessionClients(): OrganizationRemoteSessionClients;
  private _organizationRemoteSessionIssuers?;
  get organizationRemoteSessionIssuers(): OrganizationRemoteSessionIssuers;
  private _organizationRemoteSessions?;
  get organizationRemoteSessions(): OrganizationRemoteSessions;
  private _organizations?;
  get organizations(): Organizations;
  private _otelForwarding?;
  get otelForwarding(): OtelForwarding;
  private _packages?;
  get packages(): Packages;
  private _plugins?;
  get plugins(): Plugins;
  private _features?;
  get features(): Features;
  private _projects?;
  get projects(): Projects;
  private _remoteMcp?;
  get remoteMcp(): RemoteMcp;
  private _remoteSessionClients?;
  get remoteSessionClients(): RemoteSessionClients;
  private _remoteSessionIssuers?;
  get remoteSessionIssuers(): RemoteSessionIssuers;
  private _remoteSessions?;
  get remoteSessions(): RemoteSessions;
  private _resources?;
  get resources(): Resources;
  private _risk?;
  get risk(): Risk;
  private _telemetry?;
  get telemetry(): Telemetry;
  private _templates?;
  get templates(): Templates;
  private _tools?;
  get tools(): Tools;
  private _toolsets?;
  get toolsets(): Toolsets;
  private _triggers?;
  get triggers(): Triggers;
  private _tunneledMcp?;
  get tunneledMcp(): TunneledMcp;
  private _usage?;
  get usage(): Usage;
  private _userSessionClients?;
  get userSessionClients(): UserSessionClients;
  private _userSessionConsents?;
  get userSessionConsents(): UserSessionConsents;
  private _userSessionIssuers?;
  get userSessionIssuers(): UserSessionIssuers;
  private _userSessions?;
  get userSessions(): UserSessions;
  private _variations?;
  get variations(): Variations;
}
//# sourceMappingURL=sdk.d.ts.map
