/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { variationsListGlobal } from "../funcs/variationsListGlobal.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { ListVariationsResult } from "../models/components/listvariationsresult.js";
import {
  ListGlobalVariationsRequest,
  ListGlobalVariationsSecurity,
} from "../models/operations/listglobalvariations.js";
import { unwrapAsync } from "../types/fp.js";
export type GlobalVariationsQueryData = ListVariationsResult;

export function prefetchGlobalVariations(
  queryClient: QueryClient,
  client$: GramCore,
  request?: ListGlobalVariationsRequest | undefined,
  security?: ListGlobalVariationsSecurity | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildGlobalVariationsQuery(
      client$,
      request,
      security,
      options,
    ),
  });
}

export function buildGlobalVariationsQuery(
  client$: GramCore,
  request?: ListGlobalVariationsRequest | undefined,
  security?: ListGlobalVariationsSecurity | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<GlobalVariationsQueryData>;
} {
  return {
    queryKey: queryKeyGlobalVariations({
      gramSession: request?.gramSession,
      gramKey: request?.gramKey,
      gramProject: request?.gramProject,
    }),
    queryFn: async function globalVariationsQueryFn(
      ctx,
    ): Promise<GlobalVariationsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(variationsListGlobal(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyGlobalVariations(
  parameters: {
    gramSession?: string | undefined;
    gramKey?: string | undefined;
    gramProject?: string | undefined;
  },
): QueryKey {
  return ["@gram/client", "variations", "listGlobal", parameters];
}
