/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { killswitchesListCapabilities } from "../funcs/killswitchesListCapabilities.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { KillswitchListCapabilitiesResult } from "../models/components/killswitchlistcapabilitiesresult.js";
import {
  KillswitchesListCapabilitiesRequest,
  KillswitchesListCapabilitiesSecurity,
} from "../models/operations/killswitcheslistcapabilities.js";
import { unwrapAsync } from "../types/fp.js";
export type KillswitchesListCapabilitiesQueryData =
  KillswitchListCapabilitiesResult;

export function prefetchKillswitchesListCapabilities(
  queryClient: QueryClient,
  client$: GramCore,
  security: KillswitchesListCapabilitiesSecurity,
  request?: KillswitchesListCapabilitiesRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildKillswitchesListCapabilitiesQuery(
      client$,
      security,
      request,
      options,
    ),
  });
}

export function buildKillswitchesListCapabilitiesQuery(
  client$: GramCore,
  security: KillswitchesListCapabilitiesSecurity,
  request?: KillswitchesListCapabilitiesRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<KillswitchesListCapabilitiesQueryData>;
} {
  return {
    queryKey: queryKeyKillswitchesListCapabilities({
      gramSession: request?.gramSession,
    }),
    queryFn: async function killswitchesListCapabilitiesQueryFn(
      ctx,
    ): Promise<KillswitchesListCapabilitiesQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(killswitchesListCapabilities(
        client$,
        security,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyKillswitchesListCapabilities(
  parameters: { gramSession?: string | undefined },
): QueryKey {
  return ["@gram/client", "killswitches", "listCapabilities", parameters];
}
