/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { tunneledMcpRotateServerKey } from "../funcs/tunneledMcpRotateServerKey.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { RotateTunneledMcpServerKeyResult } from "../models/components/rotatetunneledmcpserverkeyresult.js";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { ServiceError } from "../models/errors/serviceerror.js";
import {
  RotateTunneledMcpServerKeyRequest,
  RotateTunneledMcpServerKeySecurity,
} from "../models/operations/rotatetunneledmcpserverkey.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RotateTunneledMcpServerKeyMutationVariables = {
  request: RotateTunneledMcpServerKeyRequest;
  security?: RotateTunneledMcpServerKeySecurity | undefined;
  options?: RequestOptions;
};

export type RotateTunneledMcpServerKeyMutationData =
  RotateTunneledMcpServerKeyResult;

export type RotateTunneledMcpServerKeyMutationError =
  | ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * rotateServerKey tunneledMcp
 *
 * @remarks
 * Rotate a tunneled MCP server source key. Returns the new tunnel key once.
 */
export function useRotateTunneledMcpServerKeyMutation(
  options?: MutationHookOptions<
    RotateTunneledMcpServerKeyMutationData,
    RotateTunneledMcpServerKeyMutationError,
    RotateTunneledMcpServerKeyMutationVariables
  >,
): UseMutationResult<
  RotateTunneledMcpServerKeyMutationData,
  RotateTunneledMcpServerKeyMutationError,
  RotateTunneledMcpServerKeyMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildRotateTunneledMcpServerKeyMutation(client, options),
    ...options,
  });
}

export function mutationKeyRotateTunneledMcpServerKey(): MutationKey {
  return ["@gram/client", "tunneledMcp", "rotateServerKey"];
}

export function buildRotateTunneledMcpServerKeyMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RotateTunneledMcpServerKeyMutationVariables,
  ) => Promise<RotateTunneledMcpServerKeyMutationData>;
} {
  return {
    mutationKey: mutationKeyRotateTunneledMcpServerKey(),
    mutationFn: function rotateTunneledMcpServerKeyMutationFn({
      request,
      security,
      options,
    }): Promise<RotateTunneledMcpServerKeyMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(tunneledMcpRotateServerKey(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}
