/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { tunneledMcpUpdateServerHeader } from "../funcs/tunneledMcpUpdateServerHeader.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { TunneledMcpServerHeader } from "../models/components/tunneledmcpserverheader.js";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { ServiceError } from "../models/errors/serviceerror.js";
import {
  UpdateTunneledMcpServerHeaderRequest,
  UpdateTunneledMcpServerHeaderSecurity,
} from "../models/operations/updatetunneledmcpserverheader.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type UpdateTunneledMcpServerHeaderMutationVariables = {
  request: UpdateTunneledMcpServerHeaderRequest;
  security?: UpdateTunneledMcpServerHeaderSecurity | undefined;
  options?: RequestOptions;
};

export type UpdateTunneledMcpServerHeaderMutationData = TunneledMcpServerHeader;

export type UpdateTunneledMcpServerHeaderMutationError =
  | ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * updateServerHeader tunneledMcp
 *
 * @remarks
 * Update a tunneled MCP server header
 */
export function useUpdateTunneledMcpServerHeaderMutation(
  options?: MutationHookOptions<
    UpdateTunneledMcpServerHeaderMutationData,
    UpdateTunneledMcpServerHeaderMutationError,
    UpdateTunneledMcpServerHeaderMutationVariables
  >,
): UseMutationResult<
  UpdateTunneledMcpServerHeaderMutationData,
  UpdateTunneledMcpServerHeaderMutationError,
  UpdateTunneledMcpServerHeaderMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildUpdateTunneledMcpServerHeaderMutation(client, options),
    ...options,
  });
}

export function mutationKeyUpdateTunneledMcpServerHeader(): MutationKey {
  return ["@gram/client", "tunneledMcp", "updateServerHeader"];
}

export function buildUpdateTunneledMcpServerHeaderMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: UpdateTunneledMcpServerHeaderMutationVariables,
  ) => Promise<UpdateTunneledMcpServerHeaderMutationData>;
} {
  return {
    mutationKey: mutationKeyUpdateTunneledMcpServerHeader(),
    mutationFn: function updateTunneledMcpServerHeaderMutationFn({
      request,
      security,
      options,
    }): Promise<UpdateTunneledMcpServerHeaderMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(tunneledMcpUpdateServerHeader(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}
