/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GramCore } from "../core.js";
import { agentUpsertAiScanTarget } from "../funcs/agentUpsertAiScanTarget.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AiScanTargetMutationResult } from "../models/components/aiscantargetmutationresult.js";
import { GramError } from "../models/errors/gramerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { ServiceError } from "../models/errors/serviceerror.js";
import {
  UpsertDeviceAgentAiScanTargetRequest,
  UpsertDeviceAgentAiScanTargetSecurity,
} from "../models/operations/upsertdeviceagentaiscantarget.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type UpsertDeviceAgentAiScanTargetMutationVariables = {
  request: UpsertDeviceAgentAiScanTargetRequest;
  security?: UpsertDeviceAgentAiScanTargetSecurity | undefined;
  options?: RequestOptions;
};

export type UpsertDeviceAgentAiScanTargetMutationData =
  AiScanTargetMutationResult;

export type UpsertDeviceAgentAiScanTargetMutationError =
  | ServiceError
  | GramError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * upsertAiScanTarget agent
 *
 * @remarks
 * Add a scan target for this organization, replace one it added earlier, or customize a Speakeasy default under the same id, which is how a default is disabled for the organization. Agents pick the change up on their next policy poll. Requires a session with the org:admin scope.
 */
export function useUpsertDeviceAgentAiScanTargetMutation(
  options?: MutationHookOptions<
    UpsertDeviceAgentAiScanTargetMutationData,
    UpsertDeviceAgentAiScanTargetMutationError,
    UpsertDeviceAgentAiScanTargetMutationVariables
  >,
): UseMutationResult<
  UpsertDeviceAgentAiScanTargetMutationData,
  UpsertDeviceAgentAiScanTargetMutationError,
  UpsertDeviceAgentAiScanTargetMutationVariables
> {
  const client = useGramContext();
  return useMutation({
    ...buildUpsertDeviceAgentAiScanTargetMutation(client, options),
    ...options,
  });
}

export function mutationKeyUpsertDeviceAgentAiScanTarget(): MutationKey {
  return ["@gram/client", "agent", "upsertAiScanTarget"];
}

export function buildUpsertDeviceAgentAiScanTargetMutation(
  client$: GramCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: UpsertDeviceAgentAiScanTargetMutationVariables,
  ) => Promise<UpsertDeviceAgentAiScanTargetMutationData>;
} {
  return {
    mutationKey: mutationKeyUpsertDeviceAgentAiScanTarget(),
    mutationFn: function upsertDeviceAgentAiScanTargetMutationFn({
      request,
      security,
      options,
    }): Promise<UpsertDeviceAgentAiScanTargetMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(agentUpsertAiScanTarget(
        client$,
        request,
        security,
        mergedOptions,
      ));
    },
  };
}
