/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation, } from "@tanstack/react-query";
import { chatSetPinned } from "../funcs/chatSetPinned.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
/**
 * setPinned chat
 *
 * @remarks
 * Pin or unpin a chat. Pinned chats surface in a dedicated section above recents on the chat page.
 */
export function useChatSetPinnedMutation(options) {
    const client = useGramContext();
    return useMutation({
        ...buildChatSetPinnedMutation(client, options),
        ...options,
    });
}
export function mutationKeyChatSetPinned() {
    return ["@gram/client", "chat", "setPinned"];
}
export function buildChatSetPinnedMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyChatSetPinned(),
        mutationFn: function chatSetPinnedMutationFn({ request, security, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: combineSignals(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return unwrapAsync(chatSetPinned(client$, request, security, mergedOptions));
        },
    };
}
//# sourceMappingURL=chatSetPinned.js.map