/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation, } from "@tanstack/react-query";
import { environmentsClone } from "../funcs/environmentsClone.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
/**
 * cloneEnvironment environments
 *
 * @remarks
 * Clone an environment into a new one. Either copies only the variable names with empty placeholder values, or copies the encrypted values verbatim. Encrypted secret values are never decrypted by the application during the clone operation.
 */
export function useCloneEnvironmentMutation(options) {
    const client = useGramContext();
    return useMutation({
        ...buildCloneEnvironmentMutation(client, options),
        ...options,
    });
}
export function mutationKeyCloneEnvironment() {
    return ["@gram/client", "environments", "clone"];
}
export function buildCloneEnvironmentMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyCloneEnvironment(),
        mutationFn: function cloneEnvironmentMutationFn({ request, security, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: combineSignals(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return unwrapAsync(environmentsClone(client$, request, security, mergedOptions));
        },
    };
}
//# sourceMappingURL=cloneEnvironment.js.map