/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { telemetryGetProjectMetricsSummary } from "../funcs/telemetryGetProjectMetricsSummary.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
export function prefetchGetProjectMetricsSummary(
  queryClient,
  client$,
  request,
  security,
  options,
) {
  return queryClient.prefetchQuery({
    ...buildGetProjectMetricsSummaryQuery(client$, request, security, options),
  });
}
export function buildGetProjectMetricsSummaryQuery(
  client$,
  request,
  security,
  options,
) {
  return {
    queryKey: queryKeyGetProjectMetricsSummary({
      gramKey: request.gramKey,
      gramSession: request.gramSession,
      gramProject: request.gramProject,
    }),
    queryFn: async function getProjectMetricsSummaryQueryFn(ctx) {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };
      return unwrapAsync(
        telemetryGetProjectMetricsSummary(
          client$,
          request,
          security,
          mergedOptions,
        ),
      );
    },
  };
}
export function queryKeyGetProjectMetricsSummary(parameters) {
  return ["@gram/client", "telemetry", "getProjectMetricsSummary", parameters];
}
//# sourceMappingURL=getProjectMetricsSummary.core.js.map
