/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { useGramContext } from "./_context.js";
import {
  buildOrganizationQuery,
  prefetchOrganization,
  queryKeyOrganization,
} from "./organization.core.js";
export { buildOrganizationQuery, prefetchOrganization, queryKeyOrganization };
/**
 * get organizations
 *
 * @remarks
 * Get the active organization from the session.
 */
export function useOrganization(request, security, options) {
  const client = useGramContext();
  return useQuery({
    ...buildOrganizationQuery(client, request, security, options),
    ...options,
  });
}
/**
 * get organizations
 *
 * @remarks
 * Get the active organization from the session.
 */
export function useOrganizationSuspense(request, security, options) {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildOrganizationQuery(client, request, security, options),
    ...options,
  });
}
export function setOrganizationData(client, queryKeyBase, data) {
  const key = queryKeyOrganization(...queryKeyBase);
  return client.setQueryData(key, data);
}
export function invalidateOrganization(client, queryKeyBase, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "organizations", "get", ...queryKeyBase],
  });
}
export function invalidateAllOrganization(client, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "organizations", "get"],
  });
}
//# sourceMappingURL=organization.js.map
