/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery, } from "@tanstack/react-query";
import { useGramContext } from "./_context.js";
import { buildOtelForwardingConfigQuery, prefetchOtelForwardingConfig, queryKeyOtelForwardingConfig, } from "./otelForwardingConfig.core.js";
export { buildOtelForwardingConfigQuery, prefetchOtelForwardingConfig, queryKeyOtelForwardingConfig, };
/**
 * getConfig otelForwarding
 *
 * @remarks
 * Get the org-wide OTEL forwarding config. Returns an empty config (enabled=false, no URL) when none is set.
 */
export function useOtelForwardingConfig(request, security, options) {
    const client = useGramContext();
    return useQuery({
        ...buildOtelForwardingConfigQuery(client, request, security, options),
        ...options,
    });
}
/**
 * getConfig otelForwarding
 *
 * @remarks
 * Get the org-wide OTEL forwarding config. Returns an empty config (enabled=false, no URL) when none is set.
 */
export function useOtelForwardingConfigSuspense(request, security, options) {
    const client = useGramContext();
    return useSuspenseQuery({
        ...buildOtelForwardingConfigQuery(client, request, security, options),
        ...options,
    });
}
export function setOtelForwardingConfigData(client, queryKeyBase, data) {
    const key = queryKeyOtelForwardingConfig(...queryKeyBase);
    return client.setQueryData(key, data);
}
export function invalidateOtelForwardingConfig(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gram/client", "otelForwarding", "getConfig", ...queryKeyBase],
    });
}
export function invalidateAllOtelForwardingConfig(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gram/client", "otelForwarding", "getConfig"],
    });
}
//# sourceMappingURL=otelForwardingConfig.js.map