/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation } from "@tanstack/react-query";
import { projectsSetOrganizationWhitelist } from "../funcs/projectsSetOrganizationWhitelist.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
/**
 * setOrganizationWhitelist projects
 *
 * @remarks
 * Set organization whitelist status (admin only - requires speakeasy-team API key)
 */
export function useProjectsSetOrganizationWhitelistMutation(options) {
  const client = useGramContext();
  return useMutation({
    ...buildProjectsSetOrganizationWhitelistMutation(client, options),
    ...options,
  });
}
export function mutationKeyProjectsSetOrganizationWhitelist() {
  return ["@gram/client", "projects", "setOrganizationWhitelist"];
}
export function buildProjectsSetOrganizationWhitelistMutation(
  client$,
  hookOptions,
) {
  return {
    mutationKey: mutationKeyProjectsSetOrganizationWhitelist(),
    mutationFn: function projectsSetOrganizationWhitelistMutationFn({
      request,
      security,
      options,
    }) {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(
        projectsSetOrganizationWhitelist(
          client$,
          request,
          security,
          mergedOptions,
        ),
      );
    },
  };
}
//# sourceMappingURL=projectsSetOrganizationWhitelist.js.map
