/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { remoteSessionIssuersList } from "../funcs/remoteSessionIssuersList.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { unwrapResultIterator } from "../types/operations.js";
import { pageIteratorToJSON } from "./_types.js";
export function prefetchRemoteSessionIssuers(queryClient, client$, request, security, options) {
    return queryClient.prefetchQuery({
        ...buildRemoteSessionIssuersQuery(client$, request, security, options),
    });
}
export function prefetchRemoteSessionIssuersInfinite(queryClient, client$, request, security, options) {
    return queryClient.prefetchInfiniteQuery({
        ...buildRemoteSessionIssuersInfiniteQuery(client$, request, security, options),
        initialPageParam: undefined,
        getNextPageParam: (previousPage) => previousPage["~next"],
    });
}
export function buildRemoteSessionIssuersQuery(client$, request, security, options) {
    return {
        queryKey: queryKeyRemoteSessionIssuers({
            cursor: request?.cursor,
            limit: request?.limit,
            gramSession: request?.gramSession,
            gramKey: request?.gramKey,
            gramProject: request?.gramProject,
        }),
        queryFn: async function remoteSessionIssuersQueryFn(ctx) {
            const sig = combineSignals(ctx.signal, options?.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options?.fetchOptions,
                ...options,
                signal: sig,
            };
            return unwrapAsync(remoteSessionIssuersList(client$, request, security, mergedOptions));
        },
    };
}
export function buildRemoteSessionIssuersInfiniteQuery(client$, request, security, options) {
    return {
        queryKey: queryKeyRemoteSessionIssuersInfinite({
            cursor: request?.cursor,
            limit: request?.limit,
            gramSession: request?.gramSession,
            gramKey: request?.gramKey,
            gramProject: request?.gramProject,
        }),
        queryFn: async function remoteSessionIssuersQuery(ctx) {
            const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options,
                fetchOptions: { ...options?.fetchOptions, signal: sig },
            };
            if (!ctx.pageParam) {
                const pageResult = await unwrapResultIterator(remoteSessionIssuersList(client$, request, security, mergedOptions));
                return pageIteratorToJSON(pageResult);
            }
            const pageResult = await unwrapResultIterator(remoteSessionIssuersList(client$, {
                ...request,
                cursor: ctx.pageParam.cursor,
            }, security, mergedOptions));
            return pageIteratorToJSON(pageResult);
        },
    };
}
export function queryKeyRemoteSessionIssuers(parameters) {
    return ["@gram/client", "remoteSessionIssuers", "list", parameters];
}
export function queryKeyRemoteSessionIssuersInfinite(parameters) {
    return [
        "@gram/client",
        "remoteSessionIssuers",
        "list",
        "infinite",
        parameters,
    ];
}
//# sourceMappingURL=remoteSessionIssuers.core.js.map