/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import { useGramContext } from "./_context.js";
import {
  buildRemoteSessionsInfiniteQuery,
  buildRemoteSessionsQuery,
  prefetchRemoteSessions,
  prefetchRemoteSessionsInfinite,
  queryKeyRemoteSessions,
  queryKeyRemoteSessionsInfinite,
} from "./remoteSessions.core.js";
export {
  buildRemoteSessionsInfiniteQuery,
  buildRemoteSessionsQuery,
  prefetchRemoteSessions,
  prefetchRemoteSessionsInfinite,
  queryKeyRemoteSessions,
  queryKeyRemoteSessionsInfinite,
};
/**
 * listRemoteSessions remoteSessions
 *
 * @remarks
 * List remote_sessions in the caller's project. access_token_encrypted and refresh_token_encrypted are never returned — only metadata (access_expires_at, refresh_expires_at, scopes).
 */
export function useRemoteSessions(request, security, options) {
  const client = useGramContext();
  return useQuery({
    ...buildRemoteSessionsQuery(client, request, security, options),
    ...options,
  });
}
/**
 * listRemoteSessions remoteSessions
 *
 * @remarks
 * List remote_sessions in the caller's project. access_token_encrypted and refresh_token_encrypted are never returned — only metadata (access_expires_at, refresh_expires_at, scopes).
 */
export function useRemoteSessionsSuspense(request, security, options) {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildRemoteSessionsQuery(client, request, security, options),
    ...options,
  });
}
/**
 * listRemoteSessions remoteSessions
 *
 * @remarks
 * List remote_sessions in the caller's project. access_token_encrypted and refresh_token_encrypted are never returned — only metadata (access_expires_at, refresh_expires_at, scopes).
 */
export function useRemoteSessionsInfinite(request, security, options) {
  const client = useGramContext();
  return useInfiniteQuery({
    ...buildRemoteSessionsInfiniteQuery(client, request, security, options),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}
/**
 * listRemoteSessions remoteSessions
 *
 * @remarks
 * List remote_sessions in the caller's project. access_token_encrypted and refresh_token_encrypted are never returned — only metadata (access_expires_at, refresh_expires_at, scopes).
 */
export function useRemoteSessionsInfiniteSuspense(request, security, options) {
  const client = useGramContext();
  return useSuspenseInfiniteQuery({
    ...buildRemoteSessionsInfiniteQuery(client, request, security, options),
    initialPageParam: options?.initialPageParam,
    getNextPageParam: (previousPage) => previousPage["~next"],
    ...options,
  });
}
export function setRemoteSessionsData(client, queryKeyBase, data) {
  const key = queryKeyRemoteSessions(...queryKeyBase);
  return client.setQueryData(key, data);
}
export function invalidateRemoteSessions(client, queryKeyBase, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "remoteSessions", "list", ...queryKeyBase],
  });
}
export function invalidateAllRemoteSessions(client, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "remoteSessions", "list"],
  });
}
//# sourceMappingURL=remoteSessions.js.map
