/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation } from "@tanstack/react-query";
import { riskCustomRulesUpdate } from "../funcs/riskCustomRulesUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGramContext } from "./_context.js";
/**
 * updateCustomDetectionRule risk
 *
 * @remarks
 * Update a custom detection rule.
 */
export function useRiskUpdateCustomDetectionRuleMutation(options) {
  const client = useGramContext();
  return useMutation({
    ...buildRiskUpdateCustomDetectionRuleMutation(client, options),
    ...options,
  });
}
export function mutationKeyRiskUpdateCustomDetectionRule() {
  return ["@gram/client", "customRules", "update"];
}
export function buildRiskUpdateCustomDetectionRuleMutation(
  client$,
  hookOptions,
) {
  return {
    mutationKey: mutationKeyRiskUpdateCustomDetectionRule(),
    mutationFn: function riskUpdateCustomDetectionRuleMutationFn({
      request,
      security,
      options,
    }) {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(
        riskCustomRulesUpdate(client$, request, security, mergedOptions),
      );
    },
  };
}
//# sourceMappingURL=riskUpdateCustomDetectionRule.js.map
