/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { useGramContext } from "./_context.js";
import {
  buildRiskListResultsByChatQuery,
  prefetchRiskListResultsByChat,
  queryKeyRiskListResultsByChat,
} from "./riskListResultsByChat.core.js";
export {
  buildRiskListResultsByChatQuery,
  prefetchRiskListResultsByChat,
  queryKeyRiskListResultsByChat,
};
/**
 * listRiskResultsByChat risk
 *
 * @remarks
 * List risk results grouped by chat session for the current project.
 */
export function useRiskListResultsByChat(request, security, options) {
  const client = useGramContext();
  return useQuery({
    ...buildRiskListResultsByChatQuery(client, request, security, options),
    ...options,
  });
}
/**
 * listRiskResultsByChat risk
 *
 * @remarks
 * List risk results grouped by chat session for the current project.
 */
export function useRiskListResultsByChatSuspense(request, security, options) {
  const client = useGramContext();
  return useSuspenseQuery({
    ...buildRiskListResultsByChatQuery(client, request, security, options),
    ...options,
  });
}
export function setRiskListResultsByChatData(client, queryKeyBase, data) {
  const key = queryKeyRiskListResultsByChat(...queryKeyBase);
  return client.setQueryData(key, data);
}
export function invalidateRiskListResultsByChat(client, queryKeyBase, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "results", "byChat", ...queryKeyBase],
  });
}
export function invalidateAllRiskListResultsByChat(client, filters) {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gram/client", "results", "byChat"],
  });
}
//# sourceMappingURL=riskListResultsByChat.js.map
