/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CloneClientFromOAuthProxyProviderSecurityOption1 = {
  projectSlugHeaderGramProject: string;
  sessionHeaderGramSession: string;
};

export type CloneClientFromOAuthProxyProviderSecurityOption2 = {
  apikeyHeaderGramKey: string;
  projectSlugHeaderGramProject: string;
};

export type CloneClientFromOAuthProxyProviderSecurity = {
  option1?: CloneClientFromOAuthProxyProviderSecurityOption1 | undefined;
  option2?: CloneClientFromOAuthProxyProviderSecurityOption2 | undefined;
};

export type CloneClientFromOAuthProxyProviderRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * API Key header
   */
  gramKey?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
  cloneClientFromOAuthProxyProviderForm:
    components.CloneClientFromOAuthProxyProviderForm;
};

/** @internal */
export type CloneClientFromOAuthProxyProviderSecurityOption1$Outbound = {
  "project_slug_header_Gram-Project": string;
  "session_header_Gram-Session": string;
};

/** @internal */
export const CloneClientFromOAuthProxyProviderSecurityOption1$outboundSchema:
  z.ZodMiniType<
    CloneClientFromOAuthProxyProviderSecurityOption1$Outbound,
    CloneClientFromOAuthProxyProviderSecurityOption1
  > = z.pipe(
    z.object({
      projectSlugHeaderGramProject: z.string(),
      sessionHeaderGramSession: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
        sessionHeaderGramSession: "session_header_Gram-Session",
      });
    }),
  );

export function cloneClientFromOAuthProxyProviderSecurityOption1ToJSON(
  cloneClientFromOAuthProxyProviderSecurityOption1:
    CloneClientFromOAuthProxyProviderSecurityOption1,
): string {
  return JSON.stringify(
    CloneClientFromOAuthProxyProviderSecurityOption1$outboundSchema.parse(
      cloneClientFromOAuthProxyProviderSecurityOption1,
    ),
  );
}

/** @internal */
export type CloneClientFromOAuthProxyProviderSecurityOption2$Outbound = {
  "apikey_header_Gram-Key": string;
  "project_slug_header_Gram-Project": string;
};

/** @internal */
export const CloneClientFromOAuthProxyProviderSecurityOption2$outboundSchema:
  z.ZodMiniType<
    CloneClientFromOAuthProxyProviderSecurityOption2$Outbound,
    CloneClientFromOAuthProxyProviderSecurityOption2
  > = z.pipe(
    z.object({
      apikeyHeaderGramKey: z.string(),
      projectSlugHeaderGramProject: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        apikeyHeaderGramKey: "apikey_header_Gram-Key",
        projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      });
    }),
  );

export function cloneClientFromOAuthProxyProviderSecurityOption2ToJSON(
  cloneClientFromOAuthProxyProviderSecurityOption2:
    CloneClientFromOAuthProxyProviderSecurityOption2,
): string {
  return JSON.stringify(
    CloneClientFromOAuthProxyProviderSecurityOption2$outboundSchema.parse(
      cloneClientFromOAuthProxyProviderSecurityOption2,
    ),
  );
}

/** @internal */
export type CloneClientFromOAuthProxyProviderSecurity$Outbound = {
  Option1?:
    | CloneClientFromOAuthProxyProviderSecurityOption1$Outbound
    | undefined;
  Option2?:
    | CloneClientFromOAuthProxyProviderSecurityOption2$Outbound
    | undefined;
};

/** @internal */
export const CloneClientFromOAuthProxyProviderSecurity$outboundSchema:
  z.ZodMiniType<
    CloneClientFromOAuthProxyProviderSecurity$Outbound,
    CloneClientFromOAuthProxyProviderSecurity
  > = z.pipe(
    z.object({
      option1: z.optional(z.lazy(() =>
        CloneClientFromOAuthProxyProviderSecurityOption1$outboundSchema
      )),
      option2: z.optional(z.lazy(() =>
        CloneClientFromOAuthProxyProviderSecurityOption2$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        option1: "Option1",
        option2: "Option2",
      });
    }),
  );

export function cloneClientFromOAuthProxyProviderSecurityToJSON(
  cloneClientFromOAuthProxyProviderSecurity:
    CloneClientFromOAuthProxyProviderSecurity,
): string {
  return JSON.stringify(
    CloneClientFromOAuthProxyProviderSecurity$outboundSchema.parse(
      cloneClientFromOAuthProxyProviderSecurity,
    ),
  );
}

/** @internal */
export type CloneClientFromOAuthProxyProviderRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  "Gram-Key"?: string | undefined;
  "Gram-Project"?: string | undefined;
  CloneClientFromOAuthProxyProviderForm:
    components.CloneClientFromOAuthProxyProviderForm$Outbound;
};

/** @internal */
export const CloneClientFromOAuthProxyProviderRequest$outboundSchema:
  z.ZodMiniType<
    CloneClientFromOAuthProxyProviderRequest$Outbound,
    CloneClientFromOAuthProxyProviderRequest
  > = z.pipe(
    z.object({
      gramSession: z.optional(z.string()),
      gramKey: z.optional(z.string()),
      gramProject: z.optional(z.string()),
      cloneClientFromOAuthProxyProviderForm:
        components.CloneClientFromOAuthProxyProviderForm$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        gramSession: "Gram-Session",
        gramKey: "Gram-Key",
        gramProject: "Gram-Project",
        cloneClientFromOAuthProxyProviderForm:
          "CloneClientFromOAuthProxyProviderForm",
      });
    }),
  );

export function cloneClientFromOAuthProxyProviderRequestToJSON(
  cloneClientFromOAuthProxyProviderRequest:
    CloneClientFromOAuthProxyProviderRequest,
): string {
  return JSON.stringify(
    CloneClientFromOAuthProxyProviderRequest$outboundSchema.parse(
      cloneClientFromOAuthProxyProviderRequest,
    ),
  );
}
