/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateChatSessionSecurity = {
  apikeyHeaderGramKey?: string | undefined;
  projectSlugHeaderGramProject?: string | undefined;
};

export type CreateChatSessionRequest = {
  /**
   * API Key header
   */
  gramKey?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
  createRequestBody: components.CreateRequestBody;
};

/** @internal */
export const CreateChatSessionSecurity$inboundSchema: z.ZodType<
  CreateChatSessionSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "apikey_header_Gram-Key": z.string().optional(),
  "project_slug_header_Gram-Project": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "apikey_header_Gram-Key": "apikeyHeaderGramKey",
    "project_slug_header_Gram-Project": "projectSlugHeaderGramProject",
  });
});

/** @internal */
export type CreateChatSessionSecurity$Outbound = {
  "apikey_header_Gram-Key"?: string | undefined;
  "project_slug_header_Gram-Project"?: string | undefined;
};

/** @internal */
export const CreateChatSessionSecurity$outboundSchema: z.ZodType<
  CreateChatSessionSecurity$Outbound,
  z.ZodTypeDef,
  CreateChatSessionSecurity
> = z.object({
  apikeyHeaderGramKey: z.string().optional(),
  projectSlugHeaderGramProject: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    apikeyHeaderGramKey: "apikey_header_Gram-Key",
    projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateChatSessionSecurity$ {
  /** @deprecated use `CreateChatSessionSecurity$inboundSchema` instead. */
  export const inboundSchema = CreateChatSessionSecurity$inboundSchema;
  /** @deprecated use `CreateChatSessionSecurity$outboundSchema` instead. */
  export const outboundSchema = CreateChatSessionSecurity$outboundSchema;
  /** @deprecated use `CreateChatSessionSecurity$Outbound` instead. */
  export type Outbound = CreateChatSessionSecurity$Outbound;
}

export function createChatSessionSecurityToJSON(
  createChatSessionSecurity: CreateChatSessionSecurity,
): string {
  return JSON.stringify(
    CreateChatSessionSecurity$outboundSchema.parse(createChatSessionSecurity),
  );
}

export function createChatSessionSecurityFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatSessionSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatSessionSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatSessionSecurity' from JSON`,
  );
}

/** @internal */
export const CreateChatSessionRequest$inboundSchema: z.ZodType<
  CreateChatSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Gram-Key": z.string().optional(),
  "Gram-Project": z.string().optional(),
  CreateRequestBody: components.CreateRequestBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Gram-Key": "gramKey",
    "Gram-Project": "gramProject",
    "CreateRequestBody": "createRequestBody",
  });
});

/** @internal */
export type CreateChatSessionRequest$Outbound = {
  "Gram-Key"?: string | undefined;
  "Gram-Project"?: string | undefined;
  CreateRequestBody: components.CreateRequestBody$Outbound;
};

/** @internal */
export const CreateChatSessionRequest$outboundSchema: z.ZodType<
  CreateChatSessionRequest$Outbound,
  z.ZodTypeDef,
  CreateChatSessionRequest
> = z.object({
  gramKey: z.string().optional(),
  gramProject: z.string().optional(),
  createRequestBody: components.CreateRequestBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    gramKey: "Gram-Key",
    gramProject: "Gram-Project",
    createRequestBody: "CreateRequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateChatSessionRequest$ {
  /** @deprecated use `CreateChatSessionRequest$inboundSchema` instead. */
  export const inboundSchema = CreateChatSessionRequest$inboundSchema;
  /** @deprecated use `CreateChatSessionRequest$outboundSchema` instead. */
  export const outboundSchema = CreateChatSessionRequest$outboundSchema;
  /** @deprecated use `CreateChatSessionRequest$Outbound` instead. */
  export type Outbound = CreateChatSessionRequest$Outbound;
}

export function createChatSessionRequestToJSON(
  createChatSessionRequest: CreateChatSessionRequest,
): string {
  return JSON.stringify(
    CreateChatSessionRequest$outboundSchema.parse(createChatSessionRequest),
  );
}

export function createChatSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateChatSessionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChatSessionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChatSessionRequest' from JSON`,
  );
}
