/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type DetachServerFromCollectionSecurity = {
  sessionHeaderGramSession?: string | undefined;
  apikeyHeaderGramKey?: string | undefined;
};

export type DetachServerFromCollectionRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * API Key header
   */
  gramKey?: string | undefined;
  attachServerRequestBody: components.AttachServerRequestBody;
};

/** @internal */
export type DetachServerFromCollectionSecurity$Outbound = {
  "session_header_Gram-Session"?: string | undefined;
  "apikey_header_Gram-Key"?: string | undefined;
};

/** @internal */
export const DetachServerFromCollectionSecurity$outboundSchema: z.ZodMiniType<
  DetachServerFromCollectionSecurity$Outbound,
  DetachServerFromCollectionSecurity
> = z.pipe(
  z.object({
    sessionHeaderGramSession: z.optional(z.string()),
    apikeyHeaderGramKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      sessionHeaderGramSession: "session_header_Gram-Session",
      apikeyHeaderGramKey: "apikey_header_Gram-Key",
    });
  }),
);

export function detachServerFromCollectionSecurityToJSON(
  detachServerFromCollectionSecurity: DetachServerFromCollectionSecurity,
): string {
  return JSON.stringify(
    DetachServerFromCollectionSecurity$outboundSchema.parse(
      detachServerFromCollectionSecurity,
    ),
  );
}

/** @internal */
export type DetachServerFromCollectionRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  "Gram-Key"?: string | undefined;
  AttachServerRequestBody: components.AttachServerRequestBody$Outbound;
};

/** @internal */
export const DetachServerFromCollectionRequest$outboundSchema: z.ZodMiniType<
  DetachServerFromCollectionRequest$Outbound,
  DetachServerFromCollectionRequest
> = z.pipe(
  z.object({
    gramSession: z.optional(z.string()),
    gramKey: z.optional(z.string()),
    attachServerRequestBody: components.AttachServerRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramKey: "Gram-Key",
      attachServerRequestBody: "AttachServerRequestBody",
    });
  }),
);

export function detachServerFromCollectionRequestToJSON(
  detachServerFromCollectionRequest: DetachServerFromCollectionRequest,
): string {
  return JSON.stringify(
    DetachServerFromCollectionRequest$outboundSchema.parse(
      detachServerFromCollectionRequest,
    ),
  );
}
