/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 254021f354ed
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSourceEnvironmentSecurity = {
  projectSlugHeaderGramProject?: string | undefined;
  sessionHeaderGramSession?: string | undefined;
};

/**
 * The kind of source that can be linked to an environment
 */
export const QueryParamSourceKind = {
  Http: "http",
  Function: "function",
} as const;
/**
 * The kind of source that can be linked to an environment
 */
export type QueryParamSourceKind = ClosedEnum<typeof QueryParamSourceKind>;

export type GetSourceEnvironmentRequest = {
  /**
   * The kind of source (http or function)
   */
  sourceKind: QueryParamSourceKind;
  /**
   * The slug of the source
   */
  sourceSlug: string;
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
};

/** @internal */
export const GetSourceEnvironmentSecurity$inboundSchema: z.ZodType<
  GetSourceEnvironmentSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  "project_slug_header_Gram-Project": z.string().optional(),
  "session_header_Gram-Session": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "project_slug_header_Gram-Project": "projectSlugHeaderGramProject",
    "session_header_Gram-Session": "sessionHeaderGramSession",
  });
});

/** @internal */
export type GetSourceEnvironmentSecurity$Outbound = {
  "project_slug_header_Gram-Project"?: string | undefined;
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const GetSourceEnvironmentSecurity$outboundSchema: z.ZodType<
  GetSourceEnvironmentSecurity$Outbound,
  z.ZodTypeDef,
  GetSourceEnvironmentSecurity
> = z.object({
  projectSlugHeaderGramProject: z.string().optional(),
  sessionHeaderGramSession: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
    sessionHeaderGramSession: "session_header_Gram-Session",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSourceEnvironmentSecurity$ {
  /** @deprecated use `GetSourceEnvironmentSecurity$inboundSchema` instead. */
  export const inboundSchema = GetSourceEnvironmentSecurity$inboundSchema;
  /** @deprecated use `GetSourceEnvironmentSecurity$outboundSchema` instead. */
  export const outboundSchema = GetSourceEnvironmentSecurity$outboundSchema;
  /** @deprecated use `GetSourceEnvironmentSecurity$Outbound` instead. */
  export type Outbound = GetSourceEnvironmentSecurity$Outbound;
}

export function getSourceEnvironmentSecurityToJSON(
  getSourceEnvironmentSecurity: GetSourceEnvironmentSecurity,
): string {
  return JSON.stringify(
    GetSourceEnvironmentSecurity$outboundSchema.parse(
      getSourceEnvironmentSecurity,
    ),
  );
}

export function getSourceEnvironmentSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetSourceEnvironmentSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSourceEnvironmentSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSourceEnvironmentSecurity' from JSON`,
  );
}

/** @internal */
export const QueryParamSourceKind$inboundSchema: z.ZodNativeEnum<
  typeof QueryParamSourceKind
> = z.nativeEnum(QueryParamSourceKind);

/** @internal */
export const QueryParamSourceKind$outboundSchema: z.ZodNativeEnum<
  typeof QueryParamSourceKind
> = QueryParamSourceKind$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryParamSourceKind$ {
  /** @deprecated use `QueryParamSourceKind$inboundSchema` instead. */
  export const inboundSchema = QueryParamSourceKind$inboundSchema;
  /** @deprecated use `QueryParamSourceKind$outboundSchema` instead. */
  export const outboundSchema = QueryParamSourceKind$outboundSchema;
}

/** @internal */
export const GetSourceEnvironmentRequest$inboundSchema: z.ZodType<
  GetSourceEnvironmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  source_kind: QueryParamSourceKind$inboundSchema,
  source_slug: z.string(),
  "Gram-Session": z.string().optional(),
  "Gram-Project": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "source_kind": "sourceKind",
    "source_slug": "sourceSlug",
    "Gram-Session": "gramSession",
    "Gram-Project": "gramProject",
  });
});

/** @internal */
export type GetSourceEnvironmentRequest$Outbound = {
  source_kind: string;
  source_slug: string;
  "Gram-Session"?: string | undefined;
  "Gram-Project"?: string | undefined;
};

/** @internal */
export const GetSourceEnvironmentRequest$outboundSchema: z.ZodType<
  GetSourceEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  GetSourceEnvironmentRequest
> = z.object({
  sourceKind: QueryParamSourceKind$outboundSchema,
  sourceSlug: z.string(),
  gramSession: z.string().optional(),
  gramProject: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sourceKind: "source_kind",
    sourceSlug: "source_slug",
    gramSession: "Gram-Session",
    gramProject: "Gram-Project",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSourceEnvironmentRequest$ {
  /** @deprecated use `GetSourceEnvironmentRequest$inboundSchema` instead. */
  export const inboundSchema = GetSourceEnvironmentRequest$inboundSchema;
  /** @deprecated use `GetSourceEnvironmentRequest$outboundSchema` instead. */
  export const outboundSchema = GetSourceEnvironmentRequest$outboundSchema;
  /** @deprecated use `GetSourceEnvironmentRequest$Outbound` instead. */
  export type Outbound = GetSourceEnvironmentRequest$Outbound;
}

export function getSourceEnvironmentRequestToJSON(
  getSourceEnvironmentRequest: GetSourceEnvironmentRequest,
): string {
  return JSON.stringify(
    GetSourceEnvironmentRequest$outboundSchema.parse(
      getSourceEnvironmentRequest,
    ),
  );
}

export function getSourceEnvironmentRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSourceEnvironmentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSourceEnvironmentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSourceEnvironmentRequest' from JSON`,
  );
}
