/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ListAnnotationsSecurity = {
  projectSlugHeaderGramProject?: string | undefined;
  sessionHeaderGramSession?: string | undefined;
};

export type ListAnnotationsRequest = {
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
  getFeedbackRequestBody: components.GetFeedbackRequestBody;
};

/** @internal */
export type ListAnnotationsSecurity$Outbound = {
  "project_slug_header_Gram-Project"?: string | undefined;
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const ListAnnotationsSecurity$outboundSchema: z.ZodMiniType<
  ListAnnotationsSecurity$Outbound,
  ListAnnotationsSecurity
> = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.optional(z.string()),
    sessionHeaderGramSession: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function listAnnotationsSecurityToJSON(
  listAnnotationsSecurity: ListAnnotationsSecurity,
): string {
  return JSON.stringify(
    ListAnnotationsSecurity$outboundSchema.parse(listAnnotationsSecurity),
  );
}

/** @internal */
export type ListAnnotationsRequest$Outbound = {
  "Gram-Session"?: string | undefined;
  "Gram-Project"?: string | undefined;
  GetFeedbackRequestBody: components.GetFeedbackRequestBody$Outbound;
};

/** @internal */
export const ListAnnotationsRequest$outboundSchema: z.ZodMiniType<
  ListAnnotationsRequest$Outbound,
  ListAnnotationsRequest
> = z.pipe(
  z.object({
    gramSession: z.optional(z.string()),
    gramProject: z.optional(z.string()),
    getFeedbackRequestBody: components.GetFeedbackRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramProject: "Gram-Project",
      getFeedbackRequestBody: "GetFeedbackRequestBody",
    });
  }),
);

export function listAnnotationsRequestToJSON(
  listAnnotationsRequest: ListAnnotationsRequest,
): string {
  return JSON.stringify(
    ListAnnotationsRequest$outboundSchema.parse(listAnnotationsRequest),
  );
}
