/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListIntegrationsRequest = {
  /**
   * Keywords to filter integrations by
   */
  keywords?: Array<string> | undefined;
  /**
   * Session header
   */
  gramSession?: string | undefined;
  /**
   * project header
   */
  gramProject?: string | undefined;
};

/** @internal */
export const ListIntegrationsRequest$inboundSchema: z.ZodType<
  ListIntegrationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  keywords: z.array(z.string()).optional(),
  "Gram-Session": z.string().optional(),
  "Gram-Project": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Gram-Session": "gramSession",
    "Gram-Project": "gramProject",
  });
});

/** @internal */
export type ListIntegrationsRequest$Outbound = {
  keywords?: Array<string> | undefined;
  "Gram-Session"?: string | undefined;
  "Gram-Project"?: string | undefined;
};

/** @internal */
export const ListIntegrationsRequest$outboundSchema: z.ZodType<
  ListIntegrationsRequest$Outbound,
  z.ZodTypeDef,
  ListIntegrationsRequest
> = z.object({
  keywords: z.array(z.string()).optional(),
  gramSession: z.string().optional(),
  gramProject: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    gramSession: "Gram-Session",
    gramProject: "Gram-Project",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIntegrationsRequest$ {
  /** @deprecated use `ListIntegrationsRequest$inboundSchema` instead. */
  export const inboundSchema = ListIntegrationsRequest$inboundSchema;
  /** @deprecated use `ListIntegrationsRequest$outboundSchema` instead. */
  export const outboundSchema = ListIntegrationsRequest$outboundSchema;
  /** @deprecated use `ListIntegrationsRequest$Outbound` instead. */
  export type Outbound = ListIntegrationsRequest$Outbound;
}

export function listIntegrationsRequestToJSON(
  listIntegrationsRequest: ListIntegrationsRequest,
): string {
  return JSON.stringify(
    ListIntegrationsRequest$outboundSchema.parse(listIntegrationsRequest),
  );
}

export function listIntegrationsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListIntegrationsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIntegrationsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIntegrationsRequest' from JSON`,
  );
}
