/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SetSourceEnvironmentLinkSecurity = {
  projectSlugHeaderGramProject?: string | undefined;
  sessionHeaderGramSession?: string | undefined;
};

/** @internal */
export type SetSourceEnvironmentLinkSecurity$Outbound = {
  "project_slug_header_Gram-Project"?: string | undefined;
  "session_header_Gram-Session"?: string | undefined;
};

/** @internal */
export const SetSourceEnvironmentLinkSecurity$outboundSchema: z.ZodMiniType<
  SetSourceEnvironmentLinkSecurity$Outbound,
  SetSourceEnvironmentLinkSecurity
> = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.optional(z.string()),
    sessionHeaderGramSession: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);

export function setSourceEnvironmentLinkSecurityToJSON(
  setSourceEnvironmentLinkSecurity: SetSourceEnvironmentLinkSecurity,
): string {
  return JSON.stringify(
    SetSourceEnvironmentLinkSecurity$outboundSchema.parse(
      setSourceEnvironmentLinkSecurity,
    ),
  );
}
