# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  relative-path-mode: wd

linters:
  enable:
    - bodyclose
    - containedctx
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - forbidigo
    - forcetypeassert
    - gochecksumtype
    - gocritic
    - gosec
    - govet
    - iface
    - importas
    - ineffassign
    - loggercheck
    - mirror
    - musttag
    - nolintlint
    - paralleltest
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unused
    - usetesting
    - wrapcheck

  exclusions:
    rules:
      - path: internal/o11y/setup\.go
        linters:
          - wrapcheck
      - path: internal/billing/stub\.go
        linters:
          - musttag
      - path: _test\.go|internal/testenv/|cmd/
        linters:
          - forbidigo
      - path: _test\.go
        linters:
          - exhaustruct
          - gosec
  settings:
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^os\.Getenv$
          pkg: ^os$
          msg: "Direct environment variable access is forbidden because it makes testing harder. Access to environment variables is only allowed in the cmd/."
    sloglint:
      no-mixed-args: true
      attr-only: true
      no-global: all
      context: all
      no-raw-keys: true
      forbidden-keys:
        - err
        - org
        - project
    staticcheck:
      dot-import-whitelist:
        - goa.design/goa/v3/dsl
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-SA1019"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
    spancheck:
      checks:
        - end
        - set-status
      ignore-check-signatures:
        - '\(\*github\.com/speakeasy-api/gram/server/internal/oops\.ShareableError\)\.Log\('
    gocritic:
      disabled-checks:
        - ifElseChain
    exhaustruct:
      exclude:
        - '^crypto/tls\.Config$'
        - '^net\.Dialer$'
        - '^net/url\.URL$'
        - '^net/http\.Server$'
        - '^net/http\.Client$'
        - '^net/http\.Transport$'
        - '^github.com/charmbracelet/log\.Options$'
        - '^github.com/urfave/cli/v2\.App$'
        - '^github.com/urfave/cli/v2\.Command$'
        - '^github.com/urfave/cli/v2\..*Flag$'
        - '^gopkg.in/yaml.v3\.Node$'
        - '^github.com/redis/go-redis/v9\.Options$'
        - '^github.com/go-redis/cache/v9\.Options$'
        - '^github.com/go-redis/cache/v9\.Item$'
        - '^github.com/gomarkdown/markdown/html\.RendererOptions$'
        - '^go.temporal.io/sdk/internal\.RetryPolicy$'
        - '^go.temporal.io/sdk/internal\..+Options$'
        - '^go.temporal.io/sdk/internal\.ScheduleSpec$'
        - '^go.temporal.io/sdk/internal\.ScheduleIntervalSpec$'
        - '^go.temporal.io/sdk/internal\.ScheduleWorkflowAction$'
        - '^go.temporal.io/sdk/contrib/opentelemetry\..+Options$'
        - '^go.temporal.io/sdk/testsuite\.DevServerOptions$'
        - '^k8s.io/apimachinery/pkg/apis/meta/v1\..+$'
        - '^k8s.io/api/networking/v1\..+$'
        - '^github.com/posthog/posthog-go\..+$'
        - '^github\.com/speakeasy-api/openapi/.*'
        - '^github\.com/polarsource/polar-go/.*'
        - '^github\.com/docker/docker/api/types/.*'
        - '^github\.com/superfly/fly-go.*'
        - '^github\.com/speakeasy-api/gram/server/gen/types\.Tool$'
        - '^github\.com/ClickHouse/clickhouse-go/v2\.Options$'
        - '^github\.com/aws/aws-sdk-go-v2/service/s3\..+Input$'
        - '^github\.com/aws/aws-sdk-go-v2/service/s3\..+Options$'
        - '^cloud\.google\.com/go/storage\.SignedURLOptions$'
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    errcheck:
      exclude-functions:
        - "github.com/speakeasy-api/gram/server/internal/o11y.LogDefer"
        - "github.com/speakeasy-api/gram/server/internal/o11y.NoLogDefer"
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "go.uber.org/zap"
              desc: Use log/slog
            - pkg: "github.com/jackc/pgx/v4"
              desc: Use github.com/jackc/pgx/v5
            - pkg: "gopkg.in/yaml.v2"
              desc: Use gopkg.in/yaml.v3
            - pkg: "github.com/urfave/cli/v3"
              desc: V3 is not ready yet use github.com/urfave/cli/v2
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
    importas:
      no-unaliased: true
      alias:
        - pkg: goa.design/goa/v3/http
          alias: goahttp
    nolintlint:
      require-specific: true
      require-explanation: true
    wrapcheck:
      ignore-sigs:
        - "errors.New("
        - "errors.Join("
        - "fmt.Errorf("

        - "(*github.com/sourcegraph/conc/pool.ErrorPool).Wait("
        - "go.temporal.io/sdk/temporal.NewApplicationErrorWithOptions("
        - "go.temporal.io/sdk/temporal.NewApplicationErrorWithCause("
        - "go.temporal.io/sdk/temporal.NewNonRetryableApplicationError("
        - "go.temporal.io/sdk/workflow.NewContinueAsNewError("
        - "(go.temporal.io/sdk/client.Client).ExecuteWorkflow("
        - "(go.temporal.io/sdk/internal.WorkflowInboundInterceptor).ExecuteWorkflow("
        - "(go.temporal.io/sdk/internal.ActivityInboundInterceptor).ExecuteActivity("
        - "(go.temporal.io/sdk/internal.Future).Get("

        - "github.com/speakeasy-api/gram/server/internal/oops.Permanent("
        - "(*github.com/speakeasy-api/gram/server/internal/auth.Auth).Authorize("
        - "(*github.com/speakeasy-api/gram/server/internal/auth/chatsessions.Manager).Authorize("
        - "(*github.com/speakeasy-api/gram/server/internal/auth.Auth).CheckProjectAccess("
        - "(*github.com/speakeasy-api/gram/server/internal/auth/sessions.Manager).Authenticate("
        - "(*github.com/speakeasy-api/gram/server/internal/openapi.ToolExtractor).Do("
        - "(*github.com/speakeasy-api/gram/server/internal/functions.ToolExtractor).Do("

      ignore-sig-regexps:
        - "\\(\\*github\\.com\\/speakeasy-api\\/gram\\/server\\/internal\\/background\\/activities\\..+\\)\\.Do\\("
        - "github\\.com\\/speakeasy-api\\/gram\\/server\\/internal\\/mv\\.Describe.+\\("
