// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gram/openrouter/internal/utils"
	"github.com/speakeasy-api/gram/openrouter/models/components"
)

type ListGuardrailMemberAssignmentsRequest struct {
	// The unique identifier of the guardrail
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Number of records to skip for pagination
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// Maximum number of records to return (max 100)
	Limit *string `queryParam:"style=form,explode=true,name=limit"`
}

func (l *ListGuardrailMemberAssignmentsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGuardrailMemberAssignmentsRequest) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListGuardrailMemberAssignmentsRequest) GetLimit() *string {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListGuardrailMemberAssignmentsData struct {
	// Unique identifier for the assignment
	ID string `json:"id"`
	// Clerk user ID of the assigned member
	UserID string `json:"user_id"`
	// Organization ID
	OrganizationID string `json:"organization_id"`
	// ID of the guardrail
	GuardrailID string `json:"guardrail_id"`
	// User ID of who made the assignment
	AssignedBy *string `json:"assigned_by"`
	// ISO 8601 timestamp of when the assignment was created
	CreatedAt string `json:"created_at"`
}

func (l *ListGuardrailMemberAssignmentsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGuardrailMemberAssignmentsData) GetUserID() string {
	if l == nil {
		return ""
	}
	return l.UserID
}

func (l *ListGuardrailMemberAssignmentsData) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListGuardrailMemberAssignmentsData) GetGuardrailID() string {
	if l == nil {
		return ""
	}
	return l.GuardrailID
}

func (l *ListGuardrailMemberAssignmentsData) GetAssignedBy() *string {
	if l == nil {
		return nil
	}
	return l.AssignedBy
}

func (l *ListGuardrailMemberAssignmentsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

// ListGuardrailMemberAssignmentsResponseBody - List of member assignments
type ListGuardrailMemberAssignmentsResponseBody struct {
	// List of member assignments
	Data []ListGuardrailMemberAssignmentsData `json:"data"`
	// Total number of member assignments
	TotalCount float64 `json:"total_count"`
}

func (l *ListGuardrailMemberAssignmentsResponseBody) GetData() []ListGuardrailMemberAssignmentsData {
	if l == nil {
		return []ListGuardrailMemberAssignmentsData{}
	}
	return l.Data
}

func (l *ListGuardrailMemberAssignmentsResponseBody) GetTotalCount() float64 {
	if l == nil {
		return 0.0
	}
	return l.TotalCount
}

type ListGuardrailMemberAssignmentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of member assignments
	Object *ListGuardrailMemberAssignmentsResponseBody
}

func (l ListGuardrailMemberAssignmentsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGuardrailMemberAssignmentsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGuardrailMemberAssignmentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListGuardrailMemberAssignmentsResponse) GetObject() *ListGuardrailMemberAssignmentsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
