export type PolicyAction = "flag" | "block";

export type CheckScope =
  | "user_messages"
  | "system_messages"
  | "llm_responses"
  | "tool_arguments"
  | "tool_responses";

export type RuleCategory =
  | "secrets"
  | "financial"
  | "pii"
  | "government_ids"
  | "healthcare"
  | "prompt_attacks"
  | "prompt_injection"
  | "off_policy"
  | "custom";

export type DetectionRule = {
  id: string;
  description: string;
  source: "gitleaks" | "presidio";
};

export type McpServerScope = {
  slug: string;
  allTools: boolean;
  selectedTools: string[];
};

export type McpScope =
  | { mode: "all" }
  | { mode: "selected"; servers: McpServerScope[] };

export type DlpPolicy = {
  id: string;
  name: string;
  enabled: boolean;
  ruleCategories: RuleCategory[];
  selectedRules: string[];
  action: PolicyAction;
  scopes: CheckScope[];
  mcpScope: McpScope;
  createdAt: Date;
  updatedAt: Date;
};

export const RULE_CATEGORY_META: Record<
  RuleCategory,
  { label: string; description: string; icon: string }
> = {
  secrets: {
    label: "Secrets",
    description: "API keys, tokens, private keys, credentials",
    icon: "key-round",
  },
  financial: {
    label: "Financial Information",
    description: "Credit cards, bank accounts, routing numbers, IBAN codes",
    icon: "credit-card",
  },
  pii: {
    label: "Personal Identifiable Information",
    description: "Names, addresses, phone numbers, email addresses",
    icon: "user",
  },
  government_ids: {
    label: "Government Identifiers",
    description: "SSNs, passport numbers, driver's licenses, tax IDs",
    icon: "landmark",
  },
  healthcare: {
    label: "Healthcare Information",
    description: "Medical record numbers, patient data, Medicare IDs",
    icon: "heart-pulse",
  },
  prompt_attacks: {
    label: "Prompt Attacks",
    description: "Jailbreak attempts, role overrides, safety bypasses",
    icon: "shield-alert",
  },
  prompt_injection: {
    label: "Prompt Injection",
    description: "Indirect injection via tool outputs, hidden instructions",
    icon: "syringe",
  },
  off_policy: {
    label: "Off-Policy Content",
    description:
      "Requests that violate usage policies or acceptable use guidelines",
    icon: "ban",
  },
  custom: {
    label: "Custom Patterns",
    description: "Organization-specific data patterns (regex)",
    icon: "regex",
  },
};

export const CHECK_SCOPE_META: Record<
  CheckScope,
  { label: string; description: string }
> = {
  user_messages: {
    label: "User Messages",
    description: "Messages sent by users in chat",
  },
  system_messages: {
    label: "System Messages",
    description: "System prompts and assistant responses",
  },
  llm_responses: {
    label: "LLM Responses",
    description: "Responses generated by the language model",
  },
  tool_arguments: {
    label: "Tool Arguments",
    description: "Arguments passed to tool calls",
  },
  tool_responses: {
    label: "Tool Responses",
    description: "Data returned from tool executions",
  },
};

// All available detection rules, organized by category
export const DETECTION_RULES: Record<RuleCategory, DetectionRule[]> = {
  secrets: [
    {
      id: "1password-secret-key",
      description: "1Password Secret Key",
      source: "gitleaks",
    },
    {
      id: "1password-service-account-token",
      description: "1Password Service Account Token",
      source: "gitleaks",
    },
    {
      id: "adafruit-api-key",
      description: "Adafruit API Key",
      source: "gitleaks",
    },
    {
      id: "adobe-client-id",
      description: "Adobe Client ID",
      source: "gitleaks",
    },
    {
      id: "adobe-client-secret",
      description: "Adobe Client Secret",
      source: "gitleaks",
    },
    { id: "age-secret-key", description: "Age Secret Key", source: "gitleaks" },
    {
      id: "airtable-api-key",
      description: "Airtable API Key",
      source: "gitleaks",
    },
    {
      id: "airtable-personnal-access-token",
      description: "Airtable Personal Access Token",
      source: "gitleaks",
    },
    {
      id: "algolia-api-key",
      description: "Algolia API Key",
      source: "gitleaks",
    },
    {
      id: "alibaba-access-key-id",
      description: "Alibaba Access Key ID",
      source: "gitleaks",
    },
    {
      id: "alibaba-secret-key",
      description: "Alibaba Secret Key",
      source: "gitleaks",
    },
    {
      id: "anthropic-admin-api-key",
      description: "Anthropic Admin API Key",
      source: "gitleaks",
    },
    {
      id: "anthropic-api-key",
      description: "Anthropic API Key",
      source: "gitleaks",
    },
    {
      id: "artifactory-api-key",
      description: "Artifactory API Key",
      source: "gitleaks",
    },
    {
      id: "artifactory-reference-token",
      description: "Artifactory Reference Token",
      source: "gitleaks",
    },
    {
      id: "asana-client-id",
      description: "Asana Client ID",
      source: "gitleaks",
    },
    {
      id: "asana-client-secret",
      description: "Asana Client Secret",
      source: "gitleaks",
    },
    {
      id: "atlassian-api-token",
      description: "Atlassian API Token",
      source: "gitleaks",
    },
    {
      id: "authress-service-client-access-key",
      description: "Authress Service Client Access Key",
      source: "gitleaks",
    },
    {
      id: "aws-access-token",
      description: "AWS Credentials",
      source: "gitleaks",
    },
    {
      id: "aws-amazon-bedrock-api-key-long-lived",
      description: "Amazon Bedrock API Key (Long-Lived)",
      source: "gitleaks",
    },
    {
      id: "aws-amazon-bedrock-api-key-short-lived",
      description: "Amazon Bedrock API Key (Short-Lived)",
      source: "gitleaks",
    },
    {
      id: "azure-ad-client-secret",
      description: "Azure AD Client Secret",
      source: "gitleaks",
    },
    {
      id: "beamer-api-token",
      description: "Beamer API Token",
      source: "gitleaks",
    },
    {
      id: "bitbucket-client-id",
      description: "Bitbucket Client ID",
      source: "gitleaks",
    },
    {
      id: "bitbucket-client-secret",
      description: "Bitbucket Client Secret",
      source: "gitleaks",
    },
    {
      id: "bittrex-access-key",
      description: "Bittrex Access Key",
      source: "gitleaks",
    },
    {
      id: "bittrex-secret-key",
      description: "Bittrex Secret Key",
      source: "gitleaks",
    },
    {
      id: "cisco-meraki-api-key",
      description: "Cisco Meraki API Key",
      source: "gitleaks",
    },
    {
      id: "clickhouse-cloud-api-secret-key",
      description: "ClickHouse Cloud API Key",
      source: "gitleaks",
    },
    {
      id: "clojars-api-token",
      description: "Clojars API Token",
      source: "gitleaks",
    },
    {
      id: "cloudflare-api-key",
      description: "Cloudflare API Key",
      source: "gitleaks",
    },
    {
      id: "cloudflare-global-api-key",
      description: "Cloudflare Global API Key",
      source: "gitleaks",
    },
    {
      id: "cloudflare-origin-ca-key",
      description: "Cloudflare Origin Ca Key",
      source: "gitleaks",
    },
    {
      id: "codecov-access-token",
      description: "Codecov Access Token",
      source: "gitleaks",
    },
    {
      id: "cohere-api-token",
      description: "Cohere API Token",
      source: "gitleaks",
    },
    {
      id: "coinbase-access-token",
      description: "Coinbase Access Token",
      source: "gitleaks",
    },
    {
      id: "confluent-access-token",
      description: "Confluent Access Token",
      source: "gitleaks",
    },
    {
      id: "confluent-secret-key",
      description: "Confluent Secret Key",
      source: "gitleaks",
    },
    {
      id: "contentful-delivery-api-token",
      description: "Contentful Delivery API Token",
      source: "gitleaks",
    },
    {
      id: "curl-auth-header",
      description: "curl Authorization Header",
      source: "gitleaks",
    },
    {
      id: "curl-auth-user",
      description: "curl Basic Auth",
      source: "gitleaks",
    },
    {
      id: "databricks-api-token",
      description: "Databricks API Token",
      source: "gitleaks",
    },
    {
      id: "datadog-access-token",
      description: "Datadog Access Token",
      source: "gitleaks",
    },
    {
      id: "defined-networking-api-token",
      description: "Defined Networking API Token",
      source: "gitleaks",
    },
    {
      id: "digitalocean-access-token",
      description: "Digitalocean Access Token",
      source: "gitleaks",
    },
    {
      id: "digitalocean-pat",
      description: "Digitalocean PAT",
      source: "gitleaks",
    },
    {
      id: "digitalocean-refresh-token",
      description: "Digitalocean Refresh Token",
      source: "gitleaks",
    },
    {
      id: "discord-api-token",
      description: "Discord API Token",
      source: "gitleaks",
    },
    {
      id: "discord-client-id",
      description: "Discord Client ID",
      source: "gitleaks",
    },
    {
      id: "discord-client-secret",
      description: "Discord Client Secret",
      source: "gitleaks",
    },
    {
      id: "doppler-api-token",
      description: "Doppler API Token",
      source: "gitleaks",
    },
    {
      id: "droneci-access-token",
      description: "Droneci Access Token",
      source: "gitleaks",
    },
    {
      id: "dropbox-api-token",
      description: "Dropbox API Token",
      source: "gitleaks",
    },
    {
      id: "dropbox-long-lived-api-token",
      description: "Dropbox Long Lived API Token",
      source: "gitleaks",
    },
    {
      id: "dropbox-short-lived-api-token",
      description: "Dropbox Short Lived API Token",
      source: "gitleaks",
    },
    {
      id: "duffel-api-token",
      description: "Duffel API Token",
      source: "gitleaks",
    },
    {
      id: "dynatrace-api-token",
      description: "Dynatrace API Token",
      source: "gitleaks",
    },
    {
      id: "easypost-api-token",
      description: "Easypost API Token",
      source: "gitleaks",
    },
    {
      id: "easypost-test-api-token",
      description: "Easypost Test API Token",
      source: "gitleaks",
    },
    {
      id: "etsy-access-token",
      description: "Etsy Access Token",
      source: "gitleaks",
    },
    {
      id: "facebook-access-token",
      description: "Facebook Access Token",
      source: "gitleaks",
    },
    {
      id: "facebook-page-access-token",
      description: "Facebook Page Access Token",
      source: "gitleaks",
    },
    {
      id: "facebook-secret",
      description: "Facebook Secret",
      source: "gitleaks",
    },
    {
      id: "fastly-api-token",
      description: "Fastly API Token",
      source: "gitleaks",
    },
    {
      id: "finicity-api-token",
      description: "Finicity API Token",
      source: "gitleaks",
    },
    {
      id: "finicity-client-secret",
      description: "Finicity Client Secret",
      source: "gitleaks",
    },
    {
      id: "finnhub-access-token",
      description: "Finnhub Access Token",
      source: "gitleaks",
    },
    {
      id: "flickr-access-token",
      description: "Flickr Access Token",
      source: "gitleaks",
    },
    {
      id: "flutterwave-encryption-key",
      description: "Flutterwave Encryption Key",
      source: "gitleaks",
    },
    {
      id: "flutterwave-public-key",
      description: "Flutterwave Public Key",
      source: "gitleaks",
    },
    {
      id: "flutterwave-secret-key",
      description: "Flutterwave Secret Key",
      source: "gitleaks",
    },
    {
      id: "flyio-access-token",
      description: "Fly.io Access Token",
      source: "gitleaks",
    },
    {
      id: "frameio-api-token",
      description: "Frameio API Token",
      source: "gitleaks",
    },
    {
      id: "freemius-secret-key",
      description: "Freemius Secret Key",
      source: "gitleaks",
    },
    {
      id: "freshbooks-access-token",
      description: "Freshbooks Access Token",
      source: "gitleaks",
    },
    { id: "gcp-api-key", description: "GCP API Key", source: "gitleaks" },
    {
      id: "generic-api-key",
      description: "Generic API Key",
      source: "gitleaks",
    },
    {
      id: "github-app-token",
      description: "GitHub App Token",
      source: "gitleaks",
    },
    {
      id: "github-fine-grained-pat",
      description: "GitHub Fine-Grained PAT",
      source: "gitleaks",
    },
    {
      id: "github-oauth",
      description: "GitHub OAuth Token",
      source: "gitleaks",
    },
    {
      id: "github-pat",
      description: "GitHub Personal Access Token",
      source: "gitleaks",
    },
    {
      id: "github-refresh-token",
      description: "GitHub Refresh Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-cicd-job-token",
      description: "GitLab CI/CD Job Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-deploy-token",
      description: "GitLab Deploy Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-feature-flag-client-token",
      description: "GitLab Feature Flag Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-feed-token",
      description: "GitLab Feed Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-incoming-mail-token",
      description: "GitLab Incoming Mail Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-kubernetes-agent-token",
      description: "GitLab K8s Agent Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-oauth-app-secret",
      description: "GitLab OAuth App Secret",
      source: "gitleaks",
    },
    {
      id: "gitlab-pat",
      description: "GitLab Personal Access Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-pat-routable",
      description: "GitLab PAT (Routable)",
      source: "gitleaks",
    },
    {
      id: "gitlab-ptt",
      description: "GitLab Pipeline Trigger Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-rrt",
      description: "GitLab Runner Registration Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-runner-authentication-token",
      description: "GitLab Runner Auth Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-runner-authentication-token-routable",
      description: "GitLab Runner Auth Token (Routable)",
      source: "gitleaks",
    },
    {
      id: "gitlab-scim-token",
      description: "GitLab SCIM Token",
      source: "gitleaks",
    },
    {
      id: "gitlab-session-cookie",
      description: "GitLab Session Cookie",
      source: "gitleaks",
    },
    {
      id: "gitter-access-token",
      description: "Gitter Access Token",
      source: "gitleaks",
    },
    {
      id: "gocardless-api-token",
      description: "Gocardless API Token",
      source: "gitleaks",
    },
    {
      id: "grafana-api-key",
      description: "Grafana API Key",
      source: "gitleaks",
    },
    {
      id: "grafana-cloud-api-token",
      description: "Grafana Cloud API Token",
      source: "gitleaks",
    },
    {
      id: "grafana-service-account-token",
      description: "Grafana Service Account Token",
      source: "gitleaks",
    },
    {
      id: "harness-api-key",
      description: "Harness API Key",
      source: "gitleaks",
    },
    {
      id: "hashicorp-tf-api-token",
      description: "HashiCorp Terraform API Token",
      source: "gitleaks",
    },
    {
      id: "hashicorp-tf-password",
      description: "HashiCorp Terraform Password",
      source: "gitleaks",
    },
    { id: "heroku-api-key", description: "Heroku API Key", source: "gitleaks" },
    {
      id: "heroku-api-key-v2",
      description: "Heroku API Key (v2)",
      source: "gitleaks",
    },
    {
      id: "hubspot-api-key",
      description: "Hubspot API Key",
      source: "gitleaks",
    },
    {
      id: "huggingface-access-token",
      description: "Hugging Face Access Token",
      source: "gitleaks",
    },
    {
      id: "huggingface-organization-api-token",
      description: "Hugging Face Org API Token",
      source: "gitleaks",
    },
    {
      id: "infracost-api-token",
      description: "Infracost API Token",
      source: "gitleaks",
    },
    {
      id: "intercom-api-key",
      description: "Intercom API Key",
      source: "gitleaks",
    },
    {
      id: "intra42-client-secret",
      description: "Intra42 Client Secret",
      source: "gitleaks",
    },
    { id: "jfrog-api-key", description: "Jfrog API Key", source: "gitleaks" },
    {
      id: "jfrog-identity-token",
      description: "Jfrog Identity Token",
      source: "gitleaks",
    },
    { id: "jwt", description: "JSON Web Token (JWT)", source: "gitleaks" },
    {
      id: "jwt-base64",
      description: "JSON Web Token (Base64)",
      source: "gitleaks",
    },
    {
      id: "kraken-access-token",
      description: "Kraken Access Token",
      source: "gitleaks",
    },
    {
      id: "kubernetes-secret-yaml",
      description: "Kubernetes Secret (YAML)",
      source: "gitleaks",
    },
    {
      id: "kucoin-access-token",
      description: "Kucoin Access Token",
      source: "gitleaks",
    },
    {
      id: "kucoin-secret-key",
      description: "Kucoin Secret Key",
      source: "gitleaks",
    },
    {
      id: "launchdarkly-access-token",
      description: "Launchdarkly Access Token",
      source: "gitleaks",
    },
    { id: "linear-api-key", description: "Linear API Key", source: "gitleaks" },
    {
      id: "linear-client-secret",
      description: "Linear Client Secret",
      source: "gitleaks",
    },
    {
      id: "linkedin-client-id",
      description: "Linkedin Client ID",
      source: "gitleaks",
    },
    {
      id: "linkedin-client-secret",
      description: "Linkedin Client Secret",
      source: "gitleaks",
    },
    { id: "lob-api-key", description: "Lob API Key", source: "gitleaks" },
    {
      id: "lob-pub-api-key",
      description: "Lob Pub API Key",
      source: "gitleaks",
    },
    {
      id: "looker-client-id",
      description: "Looker Client ID",
      source: "gitleaks",
    },
    {
      id: "looker-client-secret",
      description: "Looker Client Secret",
      source: "gitleaks",
    },
    {
      id: "mailchimp-api-key",
      description: "Mailchimp API Key",
      source: "gitleaks",
    },
    {
      id: "mailgun-private-api-token",
      description: "Mailgun Private API Token",
      source: "gitleaks",
    },
    {
      id: "mailgun-pub-key",
      description: "Mailgun Pub Key",
      source: "gitleaks",
    },
    {
      id: "mailgun-signing-key",
      description: "Mailgun Signing Key",
      source: "gitleaks",
    },
    {
      id: "mapbox-api-token",
      description: "Mapbox API Token",
      source: "gitleaks",
    },
    {
      id: "mattermost-access-token",
      description: "Mattermost Access Token",
      source: "gitleaks",
    },
    {
      id: "maxmind-license-key",
      description: "Maxmind License Key",
      source: "gitleaks",
    },
    {
      id: "messagebird-api-token",
      description: "Messagebird API Token",
      source: "gitleaks",
    },
    {
      id: "messagebird-client-id",
      description: "Messagebird Client ID",
      source: "gitleaks",
    },
    {
      id: "microsoft-teams-webhook",
      description: "Microsoft Teams Webhook",
      source: "gitleaks",
    },
    {
      id: "netlify-access-token",
      description: "Netlify Access Token",
      source: "gitleaks",
    },
    {
      id: "new-relic-browser-api-token",
      description: "New Relic Browser API Token",
      source: "gitleaks",
    },
    {
      id: "new-relic-insert-key",
      description: "New Relic Insert Key",
      source: "gitleaks",
    },
    {
      id: "new-relic-user-api-id",
      description: "New Relic User API ID",
      source: "gitleaks",
    },
    {
      id: "new-relic-user-api-key",
      description: "New Relic User API Key",
      source: "gitleaks",
    },
    {
      id: "notion-api-token",
      description: "Notion API Token",
      source: "gitleaks",
    },
    {
      id: "npm-access-token",
      description: "npm Access Token",
      source: "gitleaks",
    },
    {
      id: "nuget-config-password",
      description: "NuGet Config Password",
      source: "gitleaks",
    },
    {
      id: "nytimes-access-token",
      description: "NY Times Access Token",
      source: "gitleaks",
    },
    {
      id: "octopus-deploy-api-key",
      description: "Octopus Deploy API Key",
      source: "gitleaks",
    },
    {
      id: "okta-access-token",
      description: "Okta Access Token",
      source: "gitleaks",
    },
    { id: "openai-api-key", description: "OpenAI API Key", source: "gitleaks" },
    {
      id: "openshift-user-token",
      description: "Openshift User Token",
      source: "gitleaks",
    },
    {
      id: "perplexity-api-key",
      description: "Perplexity API Key",
      source: "gitleaks",
    },
    { id: "pkcs12-file", description: "PKCS #12 File", source: "gitleaks" },
    {
      id: "plaid-api-token",
      description: "Plaid API Token",
      source: "gitleaks",
    },
    {
      id: "plaid-client-id",
      description: "Plaid Client ID",
      source: "gitleaks",
    },
    {
      id: "plaid-secret-key",
      description: "Plaid Secret Key",
      source: "gitleaks",
    },
    {
      id: "planetscale-api-token",
      description: "Planetscale API Token",
      source: "gitleaks",
    },
    {
      id: "planetscale-oauth-token",
      description: "Planetscale OAUTH Token",
      source: "gitleaks",
    },
    {
      id: "planetscale-password",
      description: "Planetscale Password",
      source: "gitleaks",
    },
    {
      id: "postman-api-token",
      description: "Postman API Token",
      source: "gitleaks",
    },
    {
      id: "prefect-api-token",
      description: "Prefect API Token",
      source: "gitleaks",
    },
    {
      id: "private-key",
      description: "Private Key (RSA/EC/DSA/SSH)",
      source: "gitleaks",
    },
    {
      id: "privateai-api-token",
      description: "Privateai API Token",
      source: "gitleaks",
    },
    {
      id: "pulumi-api-token",
      description: "Pulumi API Token",
      source: "gitleaks",
    },
    {
      id: "pypi-upload-token",
      description: "PyPI Upload Token",
      source: "gitleaks",
    },
    {
      id: "rapidapi-access-token",
      description: "Rapidapi Access Token",
      source: "gitleaks",
    },
    {
      id: "readme-api-token",
      description: "Readme API Token",
      source: "gitleaks",
    },
    {
      id: "rubygems-api-token",
      description: "Rubygems API Token",
      source: "gitleaks",
    },
    {
      id: "scalingo-api-token",
      description: "Scalingo API Token",
      source: "gitleaks",
    },
    {
      id: "sendbird-access-id",
      description: "Sendbird Access ID",
      source: "gitleaks",
    },
    {
      id: "sendbird-access-token",
      description: "Sendbird Access Token",
      source: "gitleaks",
    },
    {
      id: "sendgrid-api-token",
      description: "Sendgrid API Token",
      source: "gitleaks",
    },
    {
      id: "sendinblue-api-token",
      description: "Sendinblue API Token",
      source: "gitleaks",
    },
    {
      id: "sentry-access-token",
      description: "Sentry Access Token",
      source: "gitleaks",
    },
    {
      id: "sentry-org-token",
      description: "Sentry Org Token",
      source: "gitleaks",
    },
    {
      id: "sentry-user-token",
      description: "Sentry User Token",
      source: "gitleaks",
    },
    {
      id: "settlemint-application-access-token",
      description: "SettleMint Application Token",
      source: "gitleaks",
    },
    {
      id: "settlemint-personal-access-token",
      description: "SettleMint Personal Token",
      source: "gitleaks",
    },
    {
      id: "settlemint-service-access-token",
      description: "SettleMint Service Token",
      source: "gitleaks",
    },
    {
      id: "shippo-api-token",
      description: "Shippo API Token",
      source: "gitleaks",
    },
    {
      id: "shopify-access-token",
      description: "Shopify Access Token",
      source: "gitleaks",
    },
    {
      id: "shopify-custom-access-token",
      description: "Shopify Custom Access Token",
      source: "gitleaks",
    },
    {
      id: "shopify-private-app-access-token",
      description: "Shopify Private App Access Token",
      source: "gitleaks",
    },
    {
      id: "shopify-shared-secret",
      description: "Shopify Shared Secret",
      source: "gitleaks",
    },
    { id: "sidekiq-secret", description: "Sidekiq Secret", source: "gitleaks" },
    {
      id: "sidekiq-sensitive-url",
      description: "Sidekiq Sensitive URL",
      source: "gitleaks",
    },
    {
      id: "slack-app-token",
      description: "Slack App Token",
      source: "gitleaks",
    },
    {
      id: "slack-bot-token",
      description: "Slack Bot Token",
      source: "gitleaks",
    },
    {
      id: "slack-config-access-token",
      description: "Slack Config Access Token",
      source: "gitleaks",
    },
    {
      id: "slack-config-refresh-token",
      description: "Slack Config Refresh Token",
      source: "gitleaks",
    },
    {
      id: "slack-legacy-bot-token",
      description: "Slack Legacy Bot Token",
      source: "gitleaks",
    },
    {
      id: "slack-legacy-token",
      description: "Slack Legacy Token",
      source: "gitleaks",
    },
    {
      id: "slack-legacy-workspace-token",
      description: "Slack Legacy Workspace Token",
      source: "gitleaks",
    },
    {
      id: "slack-user-token",
      description: "Slack User Token",
      source: "gitleaks",
    },
    {
      id: "slack-webhook-url",
      description: "Slack Webhook URL",
      source: "gitleaks",
    },
    { id: "snyk-api-token", description: "Snyk API Token", source: "gitleaks" },
    {
      id: "sonar-api-token",
      description: "Sonar API Token",
      source: "gitleaks",
    },
    {
      id: "sourcegraph-access-token",
      description: "Sourcegraph Access Token",
      source: "gitleaks",
    },
    {
      id: "square-access-token",
      description: "Square Access Token",
      source: "gitleaks",
    },
    {
      id: "squarespace-access-token",
      description: "Squarespace Access Token",
      source: "gitleaks",
    },
    {
      id: "stripe-access-token",
      description: "Stripe Access Token",
      source: "gitleaks",
    },
    {
      id: "sumologic-access-id",
      description: "Sumologic Access ID",
      source: "gitleaks",
    },
    {
      id: "sumologic-access-token",
      description: "Sumologic Access Token",
      source: "gitleaks",
    },
    {
      id: "telegram-bot-api-token",
      description: "Telegram Bot API Token",
      source: "gitleaks",
    },
    {
      id: "travisci-access-token",
      description: "Travisci Access Token",
      source: "gitleaks",
    },
    { id: "twilio-api-key", description: "Twilio API Key", source: "gitleaks" },
    {
      id: "twitch-api-token",
      description: "Twitch API Token",
      source: "gitleaks",
    },
    {
      id: "twitter-access-secret",
      description: "Twitter Access Secret",
      source: "gitleaks",
    },
    {
      id: "twitter-access-token",
      description: "Twitter Access Token",
      source: "gitleaks",
    },
    {
      id: "twitter-api-key",
      description: "Twitter API Key",
      source: "gitleaks",
    },
    {
      id: "twitter-api-secret",
      description: "Twitter API Secret",
      source: "gitleaks",
    },
    {
      id: "twitter-bearer-token",
      description: "Twitter Bearer Token",
      source: "gitleaks",
    },
    {
      id: "typeform-api-token",
      description: "Typeform API Token",
      source: "gitleaks",
    },
    {
      id: "vault-batch-token",
      description: "Vault Batch Token",
      source: "gitleaks",
    },
    {
      id: "vault-service-token",
      description: "Vault Service Token",
      source: "gitleaks",
    },
    {
      id: "yandex-access-token",
      description: "Yandex Access Token",
      source: "gitleaks",
    },
    { id: "yandex-api-key", description: "Yandex API Key", source: "gitleaks" },
    {
      id: "yandex-aws-access-token",
      description: "Yandex Aws Access Token",
      source: "gitleaks",
    },
    {
      id: "zendesk-secret-key",
      description: "Zendesk Secret Key",
      source: "gitleaks",
    },
  ],
  financial: [
    {
      id: "CREDIT_CARD",
      description: "Credit card number (12-19 digits)",
      source: "presidio",
    },
    {
      id: "IBAN_CODE",
      description: "International Bank Account Number",
      source: "presidio",
    },
    {
      id: "US_BANK_NUMBER",
      description: "US bank account number (8-17 digits)",
      source: "presidio",
    },
    { id: "CRYPTO", description: "Bitcoin wallet address", source: "presidio" },
  ],
  pii: [
    {
      id: "PERSON",
      description: "Full person name (NLP-backed)",
      source: "presidio",
    },
    { id: "EMAIL_ADDRESS", description: "Email address", source: "presidio" },
    { id: "PHONE_NUMBER", description: "Telephone number", source: "presidio" },
    {
      id: "LOCATION",
      description: "Geographically defined location",
      source: "presidio",
    },
    {
      id: "IP_ADDRESS",
      description: "IPv4 or IPv6 address",
      source: "presidio",
    },
    { id: "URL", description: "Uniform Resource Locator", source: "presidio" },
    {
      id: "MAC_ADDRESS",
      description: "Network interface identifier",
      source: "presidio",
    },
    {
      id: "DATE_TIME",
      description: "Absolute or relative dates/times",
      source: "presidio",
    },
    {
      id: "NRP",
      description: "Nationality / religious / political group",
      source: "presidio",
    },
  ],
  government_ids: [
    {
      id: "US_SSN",
      description: "US Social Security Number",
      source: "presidio",
    },
    {
      id: "US_PASSPORT",
      description: "US passport number (9 digits)",
      source: "presidio",
    },
    {
      id: "US_DRIVER_LICENSE",
      description: "US state-issued driver license",
      source: "presidio",
    },
    {
      id: "US_ITIN",
      description: "US Individual Taxpayer ID Number",
      source: "presidio",
    },
    {
      id: "UK_NHS",
      description: "UK National Health Service number",
      source: "presidio",
    },
    {
      id: "UK_NINO",
      description: "UK National Insurance Number",
      source: "presidio",
    },
    {
      id: "UK_PASSPORT",
      description: "UK passport number",
      source: "presidio",
    },
    {
      id: "ES_NIF",
      description: "Spain personal tax ID (NIF)",
      source: "presidio",
    },
    {
      id: "IT_FISCAL_CODE",
      description: "Italy personal identification code",
      source: "presidio",
    },
    {
      id: "AU_TFN",
      description: "Australia Tax File Number",
      source: "presidio",
    },
    {
      id: "IN_PAN",
      description: "India Permanent Account Number",
      source: "presidio",
    },
    {
      id: "IN_AADHAAR",
      description: "India Aadhaar (12-digit identity)",
      source: "presidio",
    },
    {
      id: "SG_NRIC_FIN",
      description: "Singapore NRIC / FIN",
      source: "presidio",
    },
  ],
  healthcare: [
    {
      id: "MEDICAL_LICENSE",
      description: "Common medical license numbers",
      source: "presidio",
    },
    {
      id: "US_MBI",
      description: "US Medicare Beneficiary Identifier",
      source: "presidio",
    },
    {
      id: "US_NPI",
      description: "US National Provider Identifier",
      source: "presidio",
    },
    {
      id: "MEDICAL_DISEASE_DISORDER",
      description: "Disease or disorder mention",
      source: "presidio",
    },
    {
      id: "MEDICAL_MEDICATION",
      description: "Medication or drug name",
      source: "presidio",
    },
    {
      id: "MEDICAL_THERAPEUTIC_PROCEDURE",
      description: "Treatment or diagnostic procedure",
      source: "presidio",
    },
    {
      id: "MEDICAL_CLINICAL_EVENT",
      description: "Clinical event mention",
      source: "presidio",
    },
    {
      id: "MEDICAL_BIOLOGICAL_ATTRIBUTE",
      description: "Biological attribute or measurement",
      source: "presidio",
    },
    {
      id: "MEDICAL_FAMILY_HISTORY",
      description: "Family medical history reference",
      source: "presidio",
    },
  ],
  prompt_attacks: [
    {
      id: "jailbreak-attempt",
      description: "Jailbreak / safety bypass attempt",
      source: "presidio",
    },
    {
      id: "role-override",
      description: "Role or persona override attempt",
      source: "presidio",
    },
    {
      id: "system-prompt-extraction",
      description: "System prompt extraction attempt",
      source: "presidio",
    },
    {
      id: "multi-turn-manipulation",
      description: "Multi-turn conversation manipulation",
      source: "presidio",
    },
  ],
  prompt_injection: [
    {
      id: "indirect-injection",
      description: "Indirect prompt injection via external content",
      source: "presidio",
    },
    {
      id: "tool-output-injection",
      description: "Malicious instructions embedded in tool responses",
      source: "presidio",
    },
    {
      id: "hidden-instruction",
      description: "Hidden instructions in user-provided data",
      source: "presidio",
    },
    {
      id: "encoding-evasion",
      description: "Encoded or obfuscated injection payloads",
      source: "presidio",
    },
  ],
  off_policy: [
    {
      id: "harmful-content-request",
      description: "Request to generate harmful or dangerous content",
      source: "presidio",
    },
    {
      id: "policy-violation",
      description: "Request that violates acceptable use policy",
      source: "presidio",
    },
    {
      id: "unauthorized-action",
      description: "Attempt to perform unauthorized actions",
      source: "presidio",
    },
    {
      id: "topic-boundary-violation",
      description: "Request outside permitted topic boundaries",
      source: "presidio",
    },
  ],
  custom: [],
};

// Mock policies for initial display
export const MOCK_POLICIES: DlpPolicy[] = [
  {
    id: "pol-1",
    name: "Production Secret Scanner",
    enabled: true,
    ruleCategories: ["secrets"],
    selectedRules: [
      "private-key",
      "aws-access-token",
      "github-pat",
      "anthropic-api-key",
      "openai-api-key",
      "generic-api-key",
      "jwt",
    ],
    action: "block",
    scopes: [
      "user_messages",
      "tool_arguments",
      "tool_responses",
      "llm_responses",
    ],
    mcpScope: { mode: "all" },
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-04-10"),
  },
  {
    id: "pol-2",
    name: "PII Protection",
    enabled: true,
    ruleCategories: ["pii", "government_ids"],
    selectedRules: [
      "PERSON",
      "EMAIL_ADDRESS",
      "PHONE_NUMBER",
      "US_SSN",
      "US_PASSPORT",
      "US_DRIVER_LICENSE",
    ],
    action: "flag",
    scopes: ["user_messages", "llm_responses", "tool_responses"],
    mcpScope: { mode: "all" },
    createdAt: new Date("2026-03-20"),
    updatedAt: new Date("2026-04-08"),
  },
  {
    id: "pol-3",
    name: "Financial Data Guard",
    enabled: false,
    ruleCategories: ["financial"],
    selectedRules: ["CREDIT_CARD", "IBAN_CODE", "US_BANK_NUMBER"],
    action: "block",
    scopes: ["user_messages", "tool_arguments", "tool_responses"],
    mcpScope: { mode: "all" },
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
];

export function createEmptyPolicy(): DlpPolicy {
  return {
    id: `pol-${Date.now()}`,
    name: "",
    enabled: true,
    ruleCategories: [],
    selectedRules: [],
    action: "flag",
    scopes: ["user_messages", "tool_arguments", "tool_responses"],
    mcpScope: { mode: "all" },
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}
