// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Query struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	OrganizationID  string
	CreatedByUserID pgtype.Text
	Name            string
	Dataset         string
	Spec            []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Deleted         bool
}
