// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createExploreSavedQuery = `-- name: CreateExploreSavedQuery :one
INSERT INTO explore_saved_queries (
  organization_id,
  name,
  chart_type,
  time_window,
  spec
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::jsonb
)
RETURNING id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
`

type CreateExploreSavedQueryParams struct {
	OrganizationID string
	Name           string
	ChartType      string
	TimeWindow     string
	Spec           []byte
}

func (q *Queries) CreateExploreSavedQuery(ctx context.Context, arg CreateExploreSavedQueryParams) (ExploreSavedQuery, error) {
	row := q.db.QueryRow(ctx, createExploreSavedQuery,
		arg.OrganizationID,
		arg.Name,
		arg.ChartType,
		arg.TimeWindow,
		arg.Spec,
	)
	var i ExploreSavedQuery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChartType,
		&i.TimeWindow,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const getExploreSavedQuery = `-- name: GetExploreSavedQuery :one
SELECT id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
FROM explore_saved_queries
WHERE organization_id = $1
  AND id = $2
  AND deleted IS FALSE
`

type GetExploreSavedQueryParams struct {
	OrganizationID string
	ID             uuid.UUID
}

func (q *Queries) GetExploreSavedQuery(ctx context.Context, arg GetExploreSavedQueryParams) (ExploreSavedQuery, error) {
	row := q.db.QueryRow(ctx, getExploreSavedQuery, arg.OrganizationID, arg.ID)
	var i ExploreSavedQuery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChartType,
		&i.TimeWindow,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const listExploreSavedQueries = `-- name: ListExploreSavedQueries :many
SELECT id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
FROM explore_saved_queries
WHERE organization_id = $1
  AND deleted IS FALSE
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListExploreSavedQueries(ctx context.Context, organizationID string) ([]ExploreSavedQuery, error) {
	rows, err := q.db.Query(ctx, listExploreSavedQueries, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExploreSavedQuery
	for rows.Next() {
		var i ExploreSavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ChartType,
			&i.TimeWindow,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExploreSavedQuery = `-- name: LockExploreSavedQuery :one
SELECT id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
FROM explore_saved_queries
WHERE organization_id = $1
  AND id = $2
  AND deleted IS FALSE
FOR UPDATE
`

type LockExploreSavedQueryParams struct {
	OrganizationID string
	ID             uuid.UUID
}

func (q *Queries) LockExploreSavedQuery(ctx context.Context, arg LockExploreSavedQueryParams) (ExploreSavedQuery, error) {
	row := q.db.QueryRow(ctx, lockExploreSavedQuery, arg.OrganizationID, arg.ID)
	var i ExploreSavedQuery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChartType,
		&i.TimeWindow,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteExploreSavedQuery = `-- name: SoftDeleteExploreSavedQuery :one
UPDATE explore_saved_queries
SET deleted_at = clock_timestamp(),
    updated_at = clock_timestamp()
WHERE organization_id = $1
  AND id = $2
  AND deleted IS FALSE
RETURNING id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
`

type SoftDeleteExploreSavedQueryParams struct {
	OrganizationID string
	ID             uuid.UUID
}

func (q *Queries) SoftDeleteExploreSavedQuery(ctx context.Context, arg SoftDeleteExploreSavedQueryParams) (ExploreSavedQuery, error) {
	row := q.db.QueryRow(ctx, softDeleteExploreSavedQuery, arg.OrganizationID, arg.ID)
	var i ExploreSavedQuery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChartType,
		&i.TimeWindow,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const updateExploreSavedQuery = `-- name: UpdateExploreSavedQuery :one
UPDATE explore_saved_queries
SET name = $1,
    chart_type = $2,
    time_window = $3,
    spec = $4::jsonb,
    updated_at = clock_timestamp()
WHERE organization_id = $5
  AND id = $6
  AND deleted IS FALSE
RETURNING id, organization_id, name, chart_type, time_window, spec, created_at, updated_at, deleted_at, deleted
`

type UpdateExploreSavedQueryParams struct {
	Name           string
	ChartType      string
	TimeWindow     string
	Spec           []byte
	OrganizationID string
	ID             uuid.UUID
}

func (q *Queries) UpdateExploreSavedQuery(ctx context.Context, arg UpdateExploreSavedQueryParams) (ExploreSavedQuery, error) {
	row := q.db.QueryRow(ctx, updateExploreSavedQuery,
		arg.Name,
		arg.ChartType,
		arg.TimeWindow,
		arg.Spec,
		arg.OrganizationID,
		arg.ID,
	)
	var i ExploreSavedQuery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChartType,
		&i.TimeWindow,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}
