{
    "openapi": "3.0.1",
    "info": {
      "title": "Deals",
      "version": "v3"
    },
    "servers": [
      {
        "url": "https://api.hubapi.com"
      }
    ],
    "tags": [
      {
        "name": "Basic"
      },
      {
        "name": "Search"
      }
    ],
    "paths": {
      "/crm/v3/properties/{objectType}": {
        "get": {
          "tags": [
            "Basic"
          ],
          "summary": "Get the list of all groups that are available on any hubspot object.",
          "description": "Get the list of all properties that are available on any hubspot object.",
          "operationId": "getProperties",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.companies.read"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/companies/{companyId}": {
        "get": {
          "tags": [
            "Basic"
          ],
          "summary": "Retrieve a company",
          "description": "Retrieve a company by its ID (`companyId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
          "operationId": "getCompany",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.companies.read"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Basic"
          ],
          "summary": "Update a company",
          "description": "Update a company by ID (`companyId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
          "operationId": "updateCompany",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.companies.write"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/companies/search": {
        "post": {
          "tags": [
            "Search"
          ],
          "summary": "Search for companies",
          "description": "Search for companies by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
          "operationId": "searchCompanies",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.companies.read"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/contacts/{contactId}": {
        "get": {
          "tags": [
            "Basic"
          ],
          "summary": "Retrieve a contact",
          "description": "Retrieve a contact by its ID (`contactId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
          "operationId": "getContact",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.contacts.read"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Basic"
          ],
          "summary": "Update a contact",
          "description": "Update a contact by ID (`contactId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
          "operationId": "updateContact",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.contacts.write"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/contacts": {
        "post": {
          "tags": [
            "Basic"
          ],
          "summary": "Create a contact",
          "description": "Create a single contact. Include a `properties` object to define [property values](https://developers.hubspot.com/docs/guides/api/crm/properties) for the contact, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
          "operationId": "createContact",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.contacts.write"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/contacts/search": {
        "post": {
          "tags": [
            "Search"
          ],
          "summary": "Search for contacts",
          "description": "Search for contacts by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
          "operationId": "searchContacts",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.contacts.read"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/deals/{dealId}": {
        "get": {
          "tags": [
            "Basic"
          ],
          "summary": "Read",
          "description": "Read a Deal Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
          "operationId": "getDeal",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.deals.read"
              ]
            }
          ]
        },
        "patch": {
          "tags": [
            "Basic"
          ],
          "summary": "Update",
          "description": "Perform a partial update of an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
          "operationId": "updateDeal",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.deals.write"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/deals": {
        "post": {
          "tags": [
            "Basic"
          ],
          "summary": "Create",
          "description": "Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.",
          "operationId": "createDeal",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.deals.write"
              ]
            }
          ]
        }
      },
      "/crm/v3/objects/deals/search": {
        "post": {
          "tags": [
            "Search"
          ],
          "operationId": "searchDeals",
          "security": [
            {
              "hubspot_token": [
                "crm.objects.deals.read"
              ]
            }
          ]
        }
      }
    },
    "components": {
      "securitySchemes": {
        "hubspot_token": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    }
  }