// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OktaResourceConnection struct {
	ID                           uuid.UUID
	OrganizationID               string
	IdentityProviderConnectionID uuid.UUID
	RemoteSessionIssuerID        uuid.UUID
	Resource                     string
	Audience                     string
	OktaApplicationID            pgtype.Text
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}
