edition = "2024";

package gram.otel.v1;

import "gcp/pubsub/v1/options.proto";

option go_package = "github.com/speakeasy-api/gram/infra/gen/gram/otel/v1;otelv1";

message MetricRelay {
  option (gcp.pubsub.v1.subscription) = {
    topic: "gram.otel.v1.Metric"
    ack_deadline: {seconds: 60}
    retention: {seconds: 604800} /* 7 days */
    retain_acked_messages: true
    retry_policy: {
      minimum_backoff: {seconds: 10}
      maximum_backoff: {seconds: 60}
    }
    dead_letter: {max_delivery_attempts: 10}
  };
}
