/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PolicyEvalCandidateConfig,
  PolicyEvalCandidateConfig$Outbound,
  PolicyEvalCandidateConfig$outboundSchema,
} from "./policyevalcandidateconfig.js";
import {
  PolicyEvalSampleDefinition,
  PolicyEvalSampleDefinition$Outbound,
  PolicyEvalSampleDefinition$outboundSchema,
} from "./policyevalsampledefinition.js";

export type CreatePolicyEvalRunRequestBody = {
  candidate?: PolicyEvalCandidateConfig | undefined;
  /**
   * The saved policy to evaluate. Omit when supplying a candidate config for a draft.
   */
  policyId?: string | undefined;
  sample: PolicyEvalSampleDefinition;
};

/** @internal */
export type CreatePolicyEvalRunRequestBody$Outbound = {
  candidate?: PolicyEvalCandidateConfig$Outbound | undefined;
  policy_id?: string | undefined;
  sample: PolicyEvalSampleDefinition$Outbound;
};

/** @internal */
export const CreatePolicyEvalRunRequestBody$outboundSchema: z.ZodMiniType<
  CreatePolicyEvalRunRequestBody$Outbound,
  CreatePolicyEvalRunRequestBody
> = z.pipe(
  z.object({
    candidate: z.optional(PolicyEvalCandidateConfig$outboundSchema),
    policyId: z.optional(z.string()),
    sample: PolicyEvalSampleDefinition$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      policyId: "policy_id",
    });
  }),
);

export function createPolicyEvalRunRequestBodyToJSON(
  createPolicyEvalRunRequestBody: CreatePolicyEvalRunRequestBody,
): string {
  return JSON.stringify(
    CreatePolicyEvalRunRequestBody$outboundSchema.parse(
      createPolicyEvalRunRequestBody,
    ),
  );
}
