/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A proxy tool that references an external MCP server
 */
export type ExternalMCPToolDefinition = {
  /**
   * When the tool definition was created.
   */
  createdAt: Date;
  /**
   * The ID of the deployments_external_mcps record
   */
  deploymentExternalMcpId: string;
  /**
   * The ID of the deployment
   */
  deploymentId: string;
  /**
   * The ID of the tool definition
   */
  id: string;
  /**
   * The reverse-DNS name of the external MCP server (e.g., ai.exa/exa)
   */
  name: string;
  /**
   * The ID of the MCP registry
   */
  registryId: string;
  /**
   * The URL to connect to the MCP server
   */
  remoteUrl: string;
  /**
   * Whether the external MCP server requires OAuth authentication
   */
  requiresOauth: boolean;
  /**
   * The slug used for tool prefixing (e.g., github)
   */
  slug: string;
  /**
   * The URN of this tool (tools:externalmcp:<slug>:proxy)
   */
  toolUrn: string;
  /**
   * When the tool definition was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const ExternalMCPToolDefinition$inboundSchema: z.ZodType<
  ExternalMCPToolDefinition,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deployment_external_mcp_id: z.string(),
  deployment_id: z.string(),
  id: z.string(),
  name: z.string(),
  registry_id: z.string(),
  remote_url: z.string(),
  requires_oauth: z.boolean(),
  slug: z.string(),
  tool_urn: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "deployment_external_mcp_id": "deploymentExternalMcpId",
    "deployment_id": "deploymentId",
    "registry_id": "registryId",
    "remote_url": "remoteUrl",
    "requires_oauth": "requiresOauth",
    "tool_urn": "toolUrn",
    "updated_at": "updatedAt",
  });
});

export function externalMCPToolDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<ExternalMCPToolDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalMCPToolDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalMCPToolDefinition' from JSON`,
  );
}
