/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Current state of product feature flags
 */
export type GramProductFeatures = {
  /**
   * Whether authz challenge logging to ClickHouse is enabled
   */
  authzChallengeLoggingEnabled: boolean;
  /**
   * Whether logging is enabled
   */
  logsEnabled: boolean;
  /**
   * Whether Claude Code session capture is enabled
   */
  sessionCaptureEnabled: boolean;
  /**
   * Whether tool I/O logging is enabled
   */
  toolIoLogsEnabled: boolean;
};

/** @internal */
export const GramProductFeatures$inboundSchema: z.ZodMiniType<
  GramProductFeatures,
  unknown
> = z.pipe(
  z.object({
    authz_challenge_logging_enabled: z.boolean(),
    logs_enabled: z.boolean(),
    session_capture_enabled: z.boolean(),
    tool_io_logs_enabled: z.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "authz_challenge_logging_enabled": "authzChallengeLoggingEnabled",
      "logs_enabled": "logsEnabled",
      "session_capture_enabled": "sessionCaptureEnabled",
      "tool_io_logs_enabled": "toolIoLogsEnabled",
    });
  }),
);

export function gramProductFeaturesFromJSON(
  jsonString: string,
): SafeParseResult<GramProductFeatures, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GramProductFeatures$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GramProductFeatures' from JSON`,
  );
}
