/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * A permission entry identifying who it applies to, what action it covers, and which resource it targets.
 */
export type GrantEntry = {
  /**
   * The user or role this permission entry applies to (e.g. "user:user_abc", "role:admin").
   */
  principalUrn: string;
  /**
   * The resource this permission applies to. Use "*" for unrestricted access.
   */
  resource: string;
  /**
   * The action being permitted (e.g. "build:read", "mcp:connect").
   */
  scope: string;
};

/** @internal */
export type GrantEntry$Outbound = {
  principal_urn: string;
  resource: string;
  scope: string;
};

/** @internal */
export const GrantEntry$outboundSchema: z.ZodMiniType<
  GrantEntry$Outbound,
  GrantEntry
> = z.pipe(
  z.object({
    principalUrn: z.string(),
    resource: z.string(),
    scope: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      principalUrn: "principal_urn",
    });
  }),
);

export function grantEntryToJSON(grantEntry: GrantEntry): string {
  return JSON.stringify(GrantEntry$outboundSchema.parse(grantEntry));
}
