/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TelemetryLogRecord,
  TelemetryLogRecord$inboundSchema,
} from "./telemetrylogrecord.js";

/**
 * Result of listing logs for a trace
 */
export type ListLogsForTraceResult = {
  /**
   * List of telemetry log records for this trace
   */
  logs: Array<TelemetryLogRecord>;
};

/** @internal */
export const ListLogsForTraceResult$inboundSchema: z.ZodType<
  ListLogsForTraceResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  logs: z.array(TelemetryLogRecord$inboundSchema),
});

export function listLogsForTraceResultFromJSON(
  jsonString: string,
): SafeParseResult<ListLogsForTraceResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLogsForTraceResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLogsForTraceResult' from JSON`,
  );
}
