/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TraceSummaryRecord,
  TraceSummaryRecord$inboundSchema,
} from "./tracesummaryrecord.js";

/**
 * Result of listing trace summaries
 */
export type ListTracesResult = {
  /**
   * Cursor for next page (trace ID)
   */
  nextCursor?: string | undefined;
  /**
   * List of trace summaries
   */
  traces: Array<TraceSummaryRecord>;
};

/** @internal */
export const ListTracesResult$inboundSchema: z.ZodType<
  ListTracesResult,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    next_cursor: z.string().optional(),
    traces: z.array(TraceSummaryRecord$inboundSchema),
  })
  .transform((v) => {
    return remap$(v, {
      next_cursor: "nextCursor",
    });
  });

export function listTracesResultFromJSON(
  jsonString: string,
): SafeParseResult<ListTracesResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTracesResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTracesResult' from JSON`,
  );
}
