/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PluginPackagePlatformContents,
  PluginPackagePlatformContents$inboundSchema,
} from "./pluginpackageplatformcontents.js";

export type PluginPackageContentsResult = {
  /**
   * Generated contents per platform.
   */
  platforms: Array<PluginPackagePlatformContents>;
  /**
   * The placeholder string substituted for the Gram API key in the returned contents.
   */
  redactedKeyPlaceholder: string;
};

/** @internal */
export const PluginPackageContentsResult$inboundSchema: z.ZodMiniType<
  PluginPackageContentsResult,
  unknown
> = z.pipe(
  z.object({
    platforms: z.array(PluginPackagePlatformContents$inboundSchema),
    redacted_key_placeholder: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "redacted_key_placeholder": "redactedKeyPlaceholder",
    });
  }),
);

export function pluginPackageContentsResultFromJSON(
  jsonString: string,
): SafeParseResult<PluginPackageContentsResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PluginPackageContentsResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PluginPackageContentsResult' from JSON`,
  );
}
