/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Deployment,
  Deployment$inboundSchema,
  Deployment$Outbound,
  Deployment$outboundSchema,
} from "./deployment.js";

export type RedeployResult = {
  deployment?: Deployment | undefined;
};

/** @internal */
export const RedeployResult$inboundSchema: z.ZodType<
  RedeployResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  deployment: Deployment$inboundSchema.optional(),
});

/** @internal */
export type RedeployResult$Outbound = {
  deployment?: Deployment$Outbound | undefined;
};

/** @internal */
export const RedeployResult$outboundSchema: z.ZodType<
  RedeployResult$Outbound,
  z.ZodTypeDef,
  RedeployResult
> = z.object({
  deployment: Deployment$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedeployResult$ {
  /** @deprecated use `RedeployResult$inboundSchema` instead. */
  export const inboundSchema = RedeployResult$inboundSchema;
  /** @deprecated use `RedeployResult$outboundSchema` instead. */
  export const outboundSchema = RedeployResult$outboundSchema;
  /** @deprecated use `RedeployResult$Outbound` instead. */
  export type Outbound = RedeployResult$Outbound;
}

export function redeployResultToJSON(redeployResult: RedeployResult): string {
  return JSON.stringify(RedeployResult$outboundSchema.parse(redeployResult));
}

export function redeployResultFromJSON(
  jsonString: string,
): SafeParseResult<RedeployResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedeployResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedeployResult' from JSON`,
  );
}
