/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RiskMatchCondition,
  RiskMatchCondition$inboundSchema,
  RiskMatchCondition$Outbound,
  RiskMatchCondition$outboundSchema,
} from "./riskmatchcondition.js";

/**
 * How the conditions reduce to a verdict.
 */
export const Combine = {
  And: "and",
  Or: "or",
} as const;
/**
 * How the conditions reduce to a verdict.
 */
export type Combine = ClosedEnum<typeof Combine>;

/**
 * Rule polarity: deny (flag a finding, the default) or allow (an allowlist that short-circuits the whole policy for a message when matched).
 */
export const RiskMatchConfigEffect = {
  Deny: "deny",
  Allow: "allow",
} as const;
/**
 * Rule polarity: deny (flag a finding, the default) or allow (an allowlist that short-circuits the whole policy for a message when matched).
 */
export type RiskMatchConfigEffect = ClosedEnum<typeof RiskMatchConfigEffect>;

export type RiskMatchConfig = {
  /**
   * How the conditions reduce to a verdict.
   */
  combine?: Combine | undefined;
  /**
   * Conditions evaluated against a message; all (and) or any (or) must match.
   */
  conditions: Array<RiskMatchCondition>;
  /**
   * Rule polarity: deny (flag a finding, the default) or allow (an allowlist that short-circuits the whole policy for a message when matched).
   */
  effect?: RiskMatchConfigEffect | undefined;
};

/** @internal */
export const Combine$inboundSchema: z.ZodMiniEnum<typeof Combine> = z.enum(
  Combine,
);
/** @internal */
export const Combine$outboundSchema: z.ZodMiniEnum<typeof Combine> =
  Combine$inboundSchema;

/** @internal */
export const RiskMatchConfigEffect$inboundSchema: z.ZodMiniEnum<
  typeof RiskMatchConfigEffect
> = z.enum(RiskMatchConfigEffect);
/** @internal */
export const RiskMatchConfigEffect$outboundSchema: z.ZodMiniEnum<
  typeof RiskMatchConfigEffect
> = RiskMatchConfigEffect$inboundSchema;

/** @internal */
export const RiskMatchConfig$inboundSchema: z.ZodMiniType<
  RiskMatchConfig,
  unknown
> = z.object({
  combine: z.optional(Combine$inboundSchema),
  conditions: z.array(RiskMatchCondition$inboundSchema),
  effect: z.optional(RiskMatchConfigEffect$inboundSchema),
});
/** @internal */
export type RiskMatchConfig$Outbound = {
  combine?: string | undefined;
  conditions: Array<RiskMatchCondition$Outbound>;
  effect?: string | undefined;
};

/** @internal */
export const RiskMatchConfig$outboundSchema: z.ZodMiniType<
  RiskMatchConfig$Outbound,
  RiskMatchConfig
> = z.object({
  combine: z.optional(Combine$outboundSchema),
  conditions: z.array(RiskMatchCondition$outboundSchema),
  effect: z.optional(RiskMatchConfigEffect$outboundSchema),
});

export function riskMatchConfigToJSON(
  riskMatchConfig: RiskMatchConfig,
): string {
  return JSON.stringify(RiskMatchConfig$outboundSchema.parse(riskMatchConfig));
}
export function riskMatchConfigFromJSON(
  jsonString: string,
): SafeParseResult<RiskMatchConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RiskMatchConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RiskMatchConfig' from JSON`,
  );
}
