/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RiskMatchConfig,
  RiskMatchConfig$inboundSchema,
  RiskMatchConfig$Outbound,
  RiskMatchConfig$outboundSchema,
} from "./riskmatchconfig.js";

export type RiskPolicyApplication = {
  /**
   * Exempt predicates. A message is skipped for the whole policy when it matches ANY exempt (alongside exempt_rule_ids). Empty/omitted means no inline exemption.
   */
  exempts?: Array<RiskMatchConfig> | undefined;
  /**
   * Include predicates (the fine-grained scope). A message is evaluated when it matches ANY include; the list supersedes message_types. Empty/omitted scopes by message_types instead.
   */
  includes?: Array<RiskMatchConfig> | undefined;
};

/** @internal */
export const RiskPolicyApplication$inboundSchema: z.ZodMiniType<
  RiskPolicyApplication,
  unknown
> = z.object({
  exempts: z.optional(z.array(RiskMatchConfig$inboundSchema)),
  includes: z.optional(z.array(RiskMatchConfig$inboundSchema)),
});
/** @internal */
export type RiskPolicyApplication$Outbound = {
  exempts?: Array<RiskMatchConfig$Outbound> | undefined;
  includes?: Array<RiskMatchConfig$Outbound> | undefined;
};

/** @internal */
export const RiskPolicyApplication$outboundSchema: z.ZodMiniType<
  RiskPolicyApplication$Outbound,
  RiskPolicyApplication
> = z.object({
  exempts: z.optional(z.array(RiskMatchConfig$outboundSchema)),
  includes: z.optional(z.array(RiskMatchConfig$outboundSchema)),
});

export function riskPolicyApplicationToJSON(
  riskPolicyApplication: RiskPolicyApplication,
): string {
  return JSON.stringify(
    RiskPolicyApplication$outboundSchema.parse(riskPolicyApplication),
  );
}
export function riskPolicyApplicationFromJSON(
  jsonString: string,
): SafeParseResult<RiskPolicyApplication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RiskPolicyApplication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RiskPolicyApplication' from JSON`,
  );
}
