/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SearchLogsRequestBody = {
  /**
   * Cursor for pagination
   */
  cursor?: string | undefined;
  /**
   * Number of logs to return
   */
  limit?: number | undefined;
};

/** @internal */
export type SearchLogsRequestBody$Outbound = {
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const SearchLogsRequestBody$outboundSchema: z.ZodMiniType<
  SearchLogsRequestBody$Outbound,
  SearchLogsRequestBody
> = z.object({
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 20),
});

export function searchLogsRequestBodyToJSON(
  searchLogsRequestBody: SearchLogsRequestBody,
): string {
  return JSON.stringify(
    SearchLogsRequestBody$outboundSchema.parse(searchLogsRequestBody),
  );
}
