/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ExternalMCPServer,
  ExternalMCPServer$inboundSchema,
} from "./externalmcpserver.js";

export type ServeResponseBody = {
  /**
   * Pagination cursor for the next page
   */
  nextCursor?: string | undefined;
  /**
   * List of available MCP servers
   */
  servers: Array<ExternalMCPServer>;
};

/** @internal */
export const ServeResponseBody$inboundSchema: z.ZodMiniType<
  ServeResponseBody,
  unknown
> = z.pipe(
  z.object({
    next_cursor: z.optional(z.string()),
    servers: z.array(ExternalMCPServer$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function serveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ServeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServeResponseBody' from JSON`,
  );
}
