/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolVariation = {
  /**
   * The confirmation mode for the tool variation
   */
  confirm?: string | undefined;
  /**
   * The confirmation prompt for the tool variation
   */
  confirmPrompt?: string | undefined;
  /**
   * The creation date of the tool variation
   */
  createdAt: string;
  /**
   * The description of the tool variation
   */
  description?: string | undefined;
  /**
   * The ID of the tool variation group
   */
  groupId: string;
  /**
   * The ID of the tool variation
   */
  id: string;
  /**
   * The name of the tool variation
   */
  name?: string | undefined;
  /**
   * The name of the source tool
   */
  srcToolName: string;
  /**
   * The URN of the source tool
   */
  srcToolUrn: string;
  /**
   * The summarizer of the tool variation
   */
  summarizer?: string | undefined;
  /**
   * The last update date of the tool variation
   */
  updatedAt: string;
};

/** @internal */
export const ToolVariation$inboundSchema: z.ZodType<
  ToolVariation,
  z.ZodTypeDef,
  unknown
> = z.object({
  confirm: z.string().optional(),
  confirm_prompt: z.string().optional(),
  created_at: z.string(),
  description: z.string().optional(),
  group_id: z.string(),
  id: z.string(),
  name: z.string().optional(),
  src_tool_name: z.string(),
  src_tool_urn: z.string(),
  summarizer: z.string().optional(),
  updated_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "confirm_prompt": "confirmPrompt",
    "created_at": "createdAt",
    "group_id": "groupId",
    "src_tool_name": "srcToolName",
    "src_tool_urn": "srcToolUrn",
    "updated_at": "updatedAt",
  });
});

export function toolVariationFromJSON(
  jsonString: string,
): SafeParseResult<ToolVariation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolVariation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolVariation' from JSON`,
  );
}
