/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentGetPlugins } from "../funcs/agentGetPlugins.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agent extends ClientSDK {
  /**
   * getPlugins agent
   *
   * @remarks
   * Resolve the set of plugins assigned to the enrolled user and return them as a plain description the agent can render into local AI-tool configs (Claude Code, etc.).
   */
  async getPlugins(
    request: operations.GetAgentPluginsRequest,
    security?: operations.GetAgentPluginsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetPluginsResult> {
    return unwrapAsync(agentGetPlugins(
      this,
      request,
      security,
      options,
    ));
  }
}
