/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpEndpointsCreate } from "../funcs/mcpEndpointsCreate.js";
import { mcpEndpointsDelete } from "../funcs/mcpEndpointsDelete.js";
import { mcpEndpointsGet } from "../funcs/mcpEndpointsGet.js";
import { mcpEndpointsList } from "../funcs/mcpEndpointsList.js";
import { mcpEndpointsUpdate } from "../funcs/mcpEndpointsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class McpEndpoints extends ClientSDK {
  /**
   * createMcpEndpoint mcpEndpoints
   *
   * @remarks
   * Create a new MCP endpoint for an MCP server
   */
  async create(
    request: operations.CreateMcpEndpointRequest,
    security?: operations.CreateMcpEndpointSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpEndpoint> {
    return unwrapAsync(mcpEndpointsCreate(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * deleteMcpEndpoint mcpEndpoints
   *
   * @remarks
   * Delete an MCP endpoint
   */
  async delete(
    request: operations.DeleteMcpEndpointRequest,
    security?: operations.DeleteMcpEndpointSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(mcpEndpointsDelete(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getMcpEndpoint mcpEndpoints
   *
   * @remarks
   * Get an MCP endpoint by id or by (custom_domain_id, slug). Provide either id, or slug with an optional custom_domain_id — not both.
   */
  async get(
    request?: operations.GetMcpEndpointRequest | undefined,
    security?: operations.GetMcpEndpointSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpEndpoint> {
    return unwrapAsync(mcpEndpointsGet(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listMcpEndpoints mcpEndpoints
   *
   * @remarks
   * List MCP endpoints for a project. Optionally filter to only those associated with a specific MCP server.
   */
  async list(
    request?: operations.ListMcpEndpointsRequest | undefined,
    security?: operations.ListMcpEndpointsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListMcpEndpointsResult> {
    return unwrapAsync(mcpEndpointsList(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * updateMcpEndpoint mcpEndpoints
   *
   * @remarks
   * Update an MCP endpoint. This is a full-record replace: fields omitted from the request become null on the stored record. The id, mcp_server_id, and slug fields are required.
   */
  async update(
    request: operations.UpdateMcpEndpointRequest,
    security?: operations.UpdateMcpEndpointSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpEndpoint> {
    return unwrapAsync(mcpEndpointsUpdate(
      this,
      request,
      security,
      options,
    ));
  }
}
