/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpFrontendsCreate } from "../funcs/mcpFrontendsCreate.js";
import { mcpFrontendsDelete } from "../funcs/mcpFrontendsDelete.js";
import { mcpFrontendsGet } from "../funcs/mcpFrontendsGet.js";
import { mcpFrontendsList } from "../funcs/mcpFrontendsList.js";
import { mcpFrontendsUpdate } from "../funcs/mcpFrontendsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class McpFrontends extends ClientSDK {
  /**
   * createMcpFrontend mcpFrontends
   *
   * @remarks
   * Create a new MCP frontend
   */
  async create(
    request: operations.CreateMcpFrontendRequest,
    security?: operations.CreateMcpFrontendSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpFrontend> {
    return unwrapAsync(mcpFrontendsCreate(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * deleteMcpFrontend mcpFrontends
   *
   * @remarks
   * Delete an MCP frontend
   */
  async delete(
    request: operations.DeleteMcpFrontendRequest,
    security?: operations.DeleteMcpFrontendSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(mcpFrontendsDelete(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getMcpFrontend mcpFrontends
   *
   * @remarks
   * Get an MCP frontend by ID
   */
  async get(
    request: operations.GetMcpFrontendRequest,
    security?: operations.GetMcpFrontendSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpFrontend> {
    return unwrapAsync(mcpFrontendsGet(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listMcpFrontends mcpFrontends
   *
   * @remarks
   * List all MCP frontends for a project
   */
  async list(
    request?: operations.ListMcpFrontendsRequest | undefined,
    security?: operations.ListMcpFrontendsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListMcpFrontendsResult> {
    return unwrapAsync(mcpFrontendsList(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * updateMcpFrontend mcpFrontends
   *
   * @remarks
   * Update an MCP frontend. This is a full-record replace: fields omitted from the request become null on the stored record. The id and visibility fields are required; exactly one of remote_mcp_server_id or toolset_id must be provided; at most one of external_oauth_server_id or oauth_proxy_server_id may be provided.
   */
  async update(
    request: operations.UpdateMcpFrontendRequest,
    security?: operations.UpdateMcpFrontendSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.McpFrontend> {
    return unwrapAsync(mcpFrontendsUpdate(
      this,
      request,
      security,
      options,
    ));
  }
}
