/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pluginsAddPluginServer } from "../funcs/pluginsAddPluginServer.js";
import { pluginsConnectGitHub } from "../funcs/pluginsConnectGitHub.js";
import { pluginsCreatePlugin } from "../funcs/pluginsCreatePlugin.js";
import { pluginsDeletePlugin } from "../funcs/pluginsDeletePlugin.js";
import { pluginsDisconnectGitHub } from "../funcs/pluginsDisconnectGitHub.js";
import { pluginsDownloadPluginPackage } from "../funcs/pluginsDownloadPluginPackage.js";
import { pluginsGetGitHubConnection } from "../funcs/pluginsGetGitHubConnection.js";
import { pluginsGetGitHubInstallURL } from "../funcs/pluginsGetGitHubInstallURL.js";
import { pluginsGetPlugin } from "../funcs/pluginsGetPlugin.js";
import { pluginsListPlugins } from "../funcs/pluginsListPlugins.js";
import { pluginsPublishPlugins } from "../funcs/pluginsPublishPlugins.js";
import { pluginsRemovePluginServer } from "../funcs/pluginsRemovePluginServer.js";
import { pluginsSetPluginAssignments } from "../funcs/pluginsSetPluginAssignments.js";
import { pluginsUpdatePlugin } from "../funcs/pluginsUpdatePlugin.js";
import { pluginsUpdatePluginServer } from "../funcs/pluginsUpdatePluginServer.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Plugins extends ClientSDK {
  /**
   * addPluginServer plugins
   *
   * @remarks
   * Add an MCP server to a plugin.
   */
  async addPluginServer(
    request: operations.AddPluginServerRequest,
    security?: operations.AddPluginServerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.PluginServer> {
    return unwrapAsync(pluginsAddPluginServer(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * connectGitHub plugins
   *
   * @remarks
   * Connect the organization to a GitHub App installation, creating a repo in the customer's org.
   */
  async connectGitHub(
    request: operations.ConnectGitHubRequest,
    security?: operations.ConnectGitHubSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.PluginGitHubConnection> {
    return unwrapAsync(pluginsConnectGitHub(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * createPlugin plugins
   *
   * @remarks
   * Create a new plugin.
   */
  async createPlugin(
    request: operations.CreatePluginRequest,
    security?: operations.CreatePluginSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.Plugin> {
    return unwrapAsync(pluginsCreatePlugin(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * deletePlugin plugins
   *
   * @remarks
   * Delete a plugin.
   */
  async deletePlugin(
    request: operations.DeletePluginRequest,
    security?: operations.DeletePluginSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(pluginsDeletePlugin(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * disconnectGitHub plugins
   *
   * @remarks
   * Disconnect the organization's GitHub integration.
   */
  async disconnectGitHub(
    request?: operations.DisconnectGitHubRequest | undefined,
    security?: operations.DisconnectGitHubSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(pluginsDisconnectGitHub(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * downloadPluginPackage plugins
   *
   * @remarks
   * Download a ZIP archive of generated plugin packages for the organization, filtered by platform.
   */
  async downloadPluginPackage(
    request: operations.DownloadPluginPackageRequest,
    security?: operations.DownloadPluginPackageSecurity | undefined,
    options?: RequestOptions,
  ): Promise<operations.DownloadPluginPackageResponse> {
    return unwrapAsync(pluginsDownloadPluginPackage(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getGitHubConnection plugins
   *
   * @remarks
   * Get the current GitHub connection for the organization.
   */
  async getGitHubConnection(
    request?: operations.GetGitHubConnectionRequest | undefined,
    security?: operations.GetGitHubConnectionSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.PluginGitHubConnection> {
    return unwrapAsync(pluginsGetGitHubConnection(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getGitHubInstallURL plugins
   *
   * @remarks
   * Get the GitHub App installation URL and whether it is already installed.
   */
  async getGitHubInstallURL(
    request?: operations.GetGitHubInstallURLRequest | undefined,
    security?: operations.GetGitHubInstallURLSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetGitHubInstallURLResponseBody> {
    return unwrapAsync(pluginsGetGitHubInstallURL(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getPlugin plugins
   *
   * @remarks
   * Get a plugin with its servers and assignments.
   */
  async getPlugin(
    request: operations.GetPluginRequest,
    security?: operations.GetPluginSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.Plugin> {
    return unwrapAsync(pluginsGetPlugin(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listPlugins plugins
   *
   * @remarks
   * List all plugins for the current organization.
   */
  async listPlugins(
    request?: operations.ListPluginsRequest | undefined,
    security?: operations.ListPluginsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListPluginsResult> {
    return unwrapAsync(pluginsListPlugins(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * publishPlugins plugins
   *
   * @remarks
   * Generate platform-specific plugin packages and push them to the connected GitHub repository.
   */
  async publishPlugins(
    request?: operations.PublishPluginsRequest | undefined,
    security?: operations.PublishPluginsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.PublishPluginsResult> {
    return unwrapAsync(pluginsPublishPlugins(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * removePluginServer plugins
   *
   * @remarks
   * Remove a server from a plugin.
   */
  async removePluginServer(
    request: operations.RemovePluginServerRequest,
    security?: operations.RemovePluginServerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(pluginsRemovePluginServer(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * setPluginAssignments plugins
   *
   * @remarks
   * Replace all assignments for a plugin with the given list of principal URNs.
   */
  async setPluginAssignments(
    request: operations.SetPluginAssignmentsRequest,
    security?: operations.SetPluginAssignmentsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.SetPluginAssignmentsResponseBody> {
    return unwrapAsync(pluginsSetPluginAssignments(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * updatePlugin plugins
   *
   * @remarks
   * Update plugin metadata.
   */
  async updatePlugin(
    request: operations.UpdatePluginRequest,
    security?: operations.UpdatePluginSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.Plugin> {
    return unwrapAsync(pluginsUpdatePlugin(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * updatePluginServer plugins
   *
   * @remarks
   * Update a server's configuration within a plugin.
   */
  async updatePluginServer(
    request: operations.UpdatePluginServerRequest,
    security?: operations.UpdatePluginServerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.PluginServer> {
    return unwrapAsync(pluginsUpdatePluginServer(
      this,
      request,
      security,
      options,
    ));
  }
}
