/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remoteSessionIssuersCreate } from "../funcs/remoteSessionIssuersCreate.js";
import { remoteSessionIssuersDelete } from "../funcs/remoteSessionIssuersDelete.js";
import { remoteSessionIssuersDiscover } from "../funcs/remoteSessionIssuersDiscover.js";
import { remoteSessionIssuersGet } from "../funcs/remoteSessionIssuersGet.js";
import { remoteSessionIssuersList } from "../funcs/remoteSessionIssuersList.js";
import { remoteSessionIssuersRegister } from "../funcs/remoteSessionIssuersRegister.js";
import { remoteSessionIssuersUpdate } from "../funcs/remoteSessionIssuersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class RemoteSessionIssuers extends ClientSDK {
  /**
   * createRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Create a new remote_session_issuer.
   */
  async create(
    request: operations.CreateRemoteSessionIssuerRequest,
    security?: operations.CreateRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.RemoteSessionIssuer> {
    return unwrapAsync(remoteSessionIssuersCreate(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * deleteRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Soft-delete a remote_session_issuer. Blocked if any remote_session_clients still reference it.
   */
  async delete(
    request: operations.DeleteRemoteSessionIssuerRequest,
    security?: operations.DeleteRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(remoteSessionIssuersDelete(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * discoverRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Hit an upstream issuer's RFC 8414 .well-known/oauth-authorization-server document and return a draft suitable for createRemoteSessionIssuer. No persistence.
   */
  async discover(
    request: operations.DiscoverRemoteSessionIssuerRequest,
    security?: operations.DiscoverRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.RemoteSessionIssuerDraft> {
    return unwrapAsync(remoteSessionIssuersDiscover(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Get a remote_session_issuer by id or by slug. Provide exactly one.
   */
  async get(
    request?: operations.GetRemoteSessionIssuerRequest | undefined,
    security?: operations.GetRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.RemoteSessionIssuer> {
    return unwrapAsync(remoteSessionIssuersGet(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listRemoteSessionIssuers remoteSessionIssuers
   *
   * @remarks
   * List remote_session_issuers in the caller's project.
   */
  async list(
    request?: operations.ListRemoteSessionIssuersRequest | undefined,
    security?: operations.ListRemoteSessionIssuersSecurity | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.ListRemoteSessionIssuersResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(remoteSessionIssuersList(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * registerRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Perform an RFC 7591 Dynamic Client Registration call against an existing issuer's registration_endpoint and persist the issued credentials as a new remote_session_client. The issuer must already have a registration_endpoint configured.
   */
  async register(
    request: operations.RegisterRemoteSessionIssuerRequest,
    security?: operations.RegisterRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.RemoteSessionClient> {
    return unwrapAsync(remoteSessionIssuersRegister(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * updateRemoteSessionIssuer remoteSessionIssuers
   *
   * @remarks
   * Update fields on an existing remote_session_issuer.
   */
  async update(
    request: operations.UpdateRemoteSessionIssuerRequest,
    security?: operations.UpdateRemoteSessionIssuerSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.RemoteSessionIssuer> {
    return unwrapAsync(remoteSessionIssuersUpdate(
      this,
      request,
      security,
      options,
    ));
  }
}
