/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { telemetryCaptureEvent } from "../funcs/telemetryCaptureEvent.js";
import { telemetryGetHooksSummary } from "../funcs/telemetryGetHooksSummary.js";
import { telemetryGetObservabilityOverview } from "../funcs/telemetryGetObservabilityOverview.js";
import { telemetryGetProjectMetricsSummary } from "../funcs/telemetryGetProjectMetricsSummary.js";
import { telemetryGetProjectOverview } from "../funcs/telemetryGetProjectOverview.js";
import { telemetryGetUserMetricsSummary } from "../funcs/telemetryGetUserMetricsSummary.js";
import { telemetryListAttributeKeys } from "../funcs/telemetryListAttributeKeys.js";
import { telemetryListFilterOptions } from "../funcs/telemetryListFilterOptions.js";
import { telemetryListHooksTraces } from "../funcs/telemetryListHooksTraces.js";
import { telemetrySearchChats } from "../funcs/telemetrySearchChats.js";
import { telemetrySearchLogs } from "../funcs/telemetrySearchLogs.js";
import { telemetrySearchToolCalls } from "../funcs/telemetrySearchToolCalls.js";
import { telemetrySearchUsers } from "../funcs/telemetrySearchUsers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Telemetry extends ClientSDK {
  /**
   * captureEvent telemetry
   *
   * @remarks
   * Capture a telemetry event and forward it to PostHog
   */
  async captureEvent(
    request: operations.CaptureEventRequest,
    security?: operations.CaptureEventSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.CaptureEventResult> {
    return unwrapAsync(telemetryCaptureEvent(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getHooksSummary telemetry
   *
   * @remarks
   * Get aggregated hooks metrics grouped by server
   */
  async getHooksSummary(
    request: operations.GetHooksSummaryRequest,
    security?: operations.GetHooksSummarySecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetHooksSummaryResult> {
    return unwrapAsync(telemetryGetHooksSummary(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getObservabilityOverview telemetry
   *
   * @remarks
   * Get observability overview metrics including time series, tool breakdowns, and summary stats
   */
  async getObservabilityOverview(
    request: operations.GetObservabilityOverviewRequest,
    security?: operations.GetObservabilityOverviewSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetObservabilityOverviewResult> {
    return unwrapAsync(telemetryGetObservabilityOverview(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getProjectMetricsSummary telemetry
   *
   * @remarks
   * Get aggregated metrics summary for an entire project
   */
  async getProjectMetricsSummary(
    request: operations.GetProjectMetricsSummaryRequest,
    security?: operations.GetProjectMetricsSummarySecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetMetricsSummaryResult> {
    return unwrapAsync(telemetryGetProjectMetricsSummary(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getProjectOverview telemetry
   *
   * @remarks
   * Get project-level overview including total chats, tool calls, active servers/users, and top lists
   */
  async getProjectOverview(
    request: operations.GetProjectOverviewRequest,
    security?: operations.GetProjectOverviewSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetProjectOverviewResult> {
    return unwrapAsync(telemetryGetProjectOverview(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * getUserMetricsSummary telemetry
   *
   * @remarks
   * Get aggregated metrics summary grouped by user
   */
  async getUserMetricsSummary(
    request: operations.GetUserMetricsSummaryRequest,
    security?: operations.GetUserMetricsSummarySecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.GetUserMetricsSummaryResult> {
    return unwrapAsync(telemetryGetUserMetricsSummary(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listAttributeKeys telemetry
   *
   * @remarks
   * List distinct attribute keys available for filtering
   */
  async listAttributeKeys(
    request: operations.ListAttributeKeysRequest,
    security?: operations.ListAttributeKeysSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListAttributeKeysResult> {
    return unwrapAsync(telemetryListAttributeKeys(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listFilterOptions telemetry
   *
   * @remarks
   * List available filter options (API keys or users) for the observability overview
   */
  async listFilterOptions(
    request: operations.ListFilterOptionsRequest,
    security?: operations.ListFilterOptionsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListFilterOptionsResult> {
    return unwrapAsync(telemetryListFilterOptions(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * listHooksTraces telemetry
   *
   * @remarks
   * List hook traces aggregated by trace_id with user information
   */
  async listHooksTraces(
    request: operations.ListHooksTracesRequest,
    security?: operations.ListHooksTracesSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.ListHooksTracesResult> {
    return unwrapAsync(telemetryListHooksTraces(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * searchChats telemetry
   *
   * @remarks
   * Search and list chat session summaries that match a search filter
   */
  async searchChats(
    request: operations.SearchChatsRequest,
    security?: operations.SearchChatsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchChatsResult> {
    return unwrapAsync(telemetrySearchChats(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * searchLogs telemetry
   *
   * @remarks
   * Search and list telemetry logs that match a search filter
   */
  async searchLogs(
    request: operations.SearchLogsRequest,
    security?: operations.SearchLogsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchLogsResult> {
    return unwrapAsync(telemetrySearchLogs(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * searchToolCalls telemetry
   *
   * @remarks
   * Search and list tool calls that match a search filter
   */
  async searchToolCalls(
    request: operations.SearchToolCallsRequest,
    security?: operations.SearchToolCallsSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchToolCallsResult> {
    return unwrapAsync(telemetrySearchToolCalls(
      this,
      request,
      security,
      options,
    ));
  }

  /**
   * searchUsers telemetry
   *
   * @remarks
   * Search and list user usage summaries grouped by user_id or external_user_id
   */
  async searchUsers(
    request: operations.SearchUsersRequest,
    security?: operations.SearchUsersSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchUsersResult> {
    return unwrapAsync(telemetrySearchUsers(
      this,
      request,
      security,
      options,
    ));
  }
}
