-- Create "deployments_functions" table
CREATE TABLE "deployments_functions" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "deployment_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "name" text NOT NULL, "slug" text NOT NULL, "tool_runtime" text NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "deployments_functions_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "deployments_functions_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "deployments_functions_name_check" CHECK ((name <> ''::text) AND (char_length(name) <= 60)), CONSTRAINT "deployments_functions_slug_check" CHECK ((slug <> ''::text) AND (char_length(slug) <= 60)));
-- Create index "deployments_functions_deployment_id_slug_key" to table: "deployments_functions"
CREATE UNIQUE INDEX "deployments_functions_deployment_id_slug_key" ON "deployments_functions" ("deployment_id", "slug");
-- Create "function_tool_definitions" table
CREATE TABLE "function_tool_definitions" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "tool_urn" text NOT NULL, "deployment_id" uuid NOT NULL, "function_id" uuid NOT NULL, "runtime" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "input_schema" jsonb NULL, "variables" jsonb NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "function_tool_definitions_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "function_tool_definitions_function_id_fkey" FOREIGN KEY ("function_id") REFERENCES "deployments_functions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "function_tool_definitions_deployment_id_tool_urn_key" to table: "function_tool_definitions"
CREATE UNIQUE INDEX "function_tool_definitions_deployment_id_tool_urn_key" ON "function_tool_definitions" ("deployment_id", "tool_urn") WHERE (deleted IS FALSE);
-- Create index "function_tool_definitions_function_id_idx" to table: "function_tool_definitions"
CREATE INDEX "function_tool_definitions_function_id_idx" ON "function_tool_definitions" ("function_id") WHERE (deleted IS FALSE);
