-- Create "deployment_statuses" table
CREATE TABLE "deployment_statuses" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "seq" bigserial NOT NULL, "deployment_id" uuid NOT NULL, "status" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY ("id"), CONSTRAINT "deployment_statuses_seq_key" UNIQUE ("seq"));
-- Create "projects" table
CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "name" character varying(40) NOT NULL, "slug" character varying(40) NOT NULL, "organization_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"));
-- Create index "projects_organization_id_slug_key" to table: "projects"
CREATE UNIQUE INDEX "projects_organization_id_slug_key" ON "projects" ("organization_id", "slug") WHERE (deleted IS FALSE);
-- Create "api_keys" table
CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "organization_id" text NOT NULL, "project_id" uuid NULL, "created_by_user_id" text NOT NULL, "name" character varying(40) NOT NULL, "token" text NOT NULL, "scopes" text[] NOT NULL DEFAULT ARRAY[]::text[], "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "api_keys_token_key" UNIQUE ("token"), CONSTRAINT "api_keys_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "api_keys_organization_id_name_key" to table: "api_keys"
CREATE UNIQUE INDEX "api_keys_organization_id_name_key" ON "api_keys" ("organization_id", "name") WHERE (deleted IS FALSE);
-- Create "deployments" table
CREATE TABLE "deployments" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "seq" bigserial NOT NULL, "user_id" text NOT NULL, "project_id" uuid NOT NULL, "organization_id" text NOT NULL, "idempotency_key" text NOT NULL, "cloned_from" uuid NULL, "github_repo" character varying(100) NULL, "github_pr" character varying(100) NULL, "github_sha" character varying(100) NULL, "external_id" character varying(100) NULL, "external_url" character varying(100) NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY ("id"), CONSTRAINT "deployments_project_id_idempotency_key" UNIQUE ("project_id", "idempotency_key"), CONSTRAINT "deployments_seq_key" UNIQUE ("seq"), CONSTRAINT "deployments_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT);
-- Create "deployment_logs" table
CREATE TABLE "deployment_logs" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "seq" bigserial NOT NULL, "event" text NOT NULL, "message" text NOT NULL, "deployment_id" uuid NOT NULL, "project_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY ("id"), CONSTRAINT "deployment_logs_seq_key" UNIQUE ("seq"), CONSTRAINT "deployment_logs_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "deployment_logs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "assets" table
CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "url" text NOT NULL, "kind" text NOT NULL, "content_type" text NOT NULL, "content_length" bigint NOT NULL, "sha256" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "assets_project_id_sha256_key" UNIQUE ("project_id", "sha256"));
-- Create "deployments_openapiv3_assets" table
CREATE TABLE "deployments_openapiv3_assets" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "deployment_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "name" character varying(60) NOT NULL, "slug" character varying(60) NOT NULL, CONSTRAINT "deployments_openapiv3_documents_pkey" PRIMARY KEY ("id"), CONSTRAINT "deployments_openapiv3_documents_deployment_id_slug_key" UNIQUE ("deployment_id", "slug"), CONSTRAINT "deployments_openapiv3_documents_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "deployments_openapiv3_documents_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "packages" table
CREATE TABLE "packages" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "name" character varying(100) NOT NULL, "title" character varying(100) NULL, "summary" character varying(80) NULL, "keywords" character varying(20)[] NOT NULL DEFAULT (ARRAY[]::character varying[])::character varying(20)[], "organization_id" text NOT NULL, "project_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "packages_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "packages_keywords_check" CHECK (array_length(keywords, 1) <= 8));
-- Create index "packages_name_idx" to table: "packages"
CREATE INDEX "packages_name_idx" ON "packages" ("name");
-- Create index "packages_organization_id_name_key" to table: "packages"
CREATE UNIQUE INDEX "packages_organization_id_name_key" ON "packages" ("organization_id", "name") WHERE (deleted IS FALSE);
-- Create index "packages_project_id_key" to table: "packages"
CREATE UNIQUE INDEX "packages_project_id_key" ON "packages" ("project_id") WHERE (deleted IS FALSE);
-- Create "package_versions" table
CREATE TABLE "package_versions" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "package_id" uuid NOT NULL, "deployment_id" uuid NOT NULL, "visibility" character varying(20) NOT NULL, "major" smallint NOT NULL, "minor" smallint NOT NULL, "patch" smallint NOT NULL, "prerelease" character varying(20) NULL, "build" character varying(20) NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "package_versions_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "package_versions_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "package_versions_package_id_major_minor_patch_prerelease_build_" to table: "package_versions"
CREATE UNIQUE INDEX "package_versions_package_id_major_minor_patch_prerelease_build_" ON "package_versions" ("package_id", "major", "minor", "patch", "prerelease", "build") WHERE (deleted IS FALSE);
-- Create "deployments_packages" table
CREATE TABLE "deployments_packages" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "deployment_id" uuid NOT NULL, "package_id" uuid NOT NULL, "version_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "deployments_packages_deployment_id_package_id_key" UNIQUE ("deployment_id", "package_id"), CONSTRAINT "deployments_packages_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "deployments_packages_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "deployments_packages_version_id_fkey" FOREIGN KEY ("version_id") REFERENCES "package_versions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "environments" table
CREATE TABLE "environments" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "organization_id" text NOT NULL, "project_id" uuid NOT NULL, "name" character varying(40) NOT NULL, "slug" character varying(40) NOT NULL, "description" character varying(100) NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "environments_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "environments_project_id_slug_key" to table: "environments"
CREATE UNIQUE INDEX "environments_project_id_slug_key" ON "environments" ("project_id", "slug") WHERE (deleted IS FALSE);
-- Create "environment_entries" table
CREATE TABLE "environment_entries" ("name" character varying(60) NOT NULL, "value" character varying(4000) NOT NULL, "environment_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), CONSTRAINT "environments_entries_pkey" PRIMARY KEY ("environment_id", "name"), CONSTRAINT "environments_entries_environment_id_fkey" FOREIGN KEY ("environment_id") REFERENCES "environments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "http_security" table
CREATE TABLE "http_security" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "key" character varying(60) NOT NULL, "deployment_id" uuid NOT NULL, "type" character varying(20) NULL, "name" character varying(60) NOT NULL, "in_placement" character varying(10) NOT NULL, "scheme" character varying(20) NULL, "bearer_format" character varying(20) NULL, "env_variables" character varying(60)[] NULL DEFAULT (ARRAY[]::character varying[])::character varying(60)[], "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "http_security_key_unique" UNIQUE ("deployment_id", "key"), CONSTRAINT "http_security_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "http_tool_definitions" table
CREATE TABLE "http_tool_definitions" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "project_id" uuid NOT NULL, "deployment_id" uuid NOT NULL, "openapiv3_document_id" uuid NULL, "name" character varying(100) NOT NULL, "summary" text NOT NULL, "description" text NOT NULL, "openapiv3_operation" character varying(100) NULL, "tags" character varying(40)[] NOT NULL DEFAULT (ARRAY[]::character varying[])::character varying(40)[], "server_env_var" text NOT NULL, "default_server_url" text NULL, "security" jsonb NULL, "http_method" character varying(20) NOT NULL, "path" character varying(140) NOT NULL, "schema_version" character varying(20) NOT NULL, "schema" jsonb NULL, "header_settings" jsonb NULL, "query_settings" jsonb NULL, "path_settings" jsonb NULL, "request_content_type" text NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "http_tool_definitions_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "deployments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "http_tool_definitions_openapiv3_document_id_fkey" FOREIGN KEY ("openapiv3_document_id") REFERENCES "deployments_openapiv3_assets" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT, CONSTRAINT "http_tool_definitions_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "http_tool_definitions_name_idx" to table: "http_tool_definitions"
CREATE INDEX "http_tool_definitions_name_idx" ON "http_tool_definitions" ("name");
-- Create "toolsets" table
CREATE TABLE "toolsets" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "organization_id" text NOT NULL, "project_id" uuid NOT NULL, "name" character varying(40) NOT NULL, "slug" character varying(40) NOT NULL, "description" character varying(100) NULL, "default_environment_slug" character varying(40) NULL, "http_tool_names" character varying(100)[] NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "toolsets_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "toolsets_project_id_slug_key" to table: "toolsets"
CREATE UNIQUE INDEX "toolsets_project_id_slug_key" ON "toolsets" ("project_id", "slug") WHERE (deleted IS FALSE);
