-- Create "tool_variations_groups" table
CREATE TABLE "tool_variations_groups" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "project_id" uuid NOT NULL, "name" text NOT NULL, "description" text NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "tool_variations_groups_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "tool_variations_groups_description_check" CHECK ((description <> ''::text) AND (char_length(description) <= 100)), CONSTRAINT "tool_variations_groups_name_check" CHECK ((name <> ''::text) AND (char_length(name) <= 40)));
-- Create "project_tool_variations" table
CREATE TABLE "project_tool_variations" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "project_id" uuid NOT NULL, "group_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "project_tool_variations_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "tool_variations_groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "project_tool_variations_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "project_tool_variations_project_id_key" to table: "project_tool_variations"
CREATE UNIQUE INDEX "project_tool_variations_project_id_key" ON "project_tool_variations" ("project_id");
-- Create "tool_variations" table
CREATE TABLE "tool_variations" ("id" uuid NOT NULL DEFAULT generate_uuidv7(), "group_id" uuid NOT NULL, "src_tool_name" text NOT NULL, "confirm" text NULL, "confirm_prompt" text NULL, "name" text NULL, "summary" text NULL, "description" text NULL, "tags" text[] NULL, "summarizer" text NULL, "created_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "updated_at" timestamptz NOT NULL DEFAULT clock_timestamp(), "deleted_at" timestamptz NULL, "deleted" boolean NOT NULL GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED, PRIMARY KEY ("id"), CONSTRAINT "tool_variations_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "tool_variations_groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "tool_variations_scoped_src_tool_name_key" to table: "tool_variations"
CREATE UNIQUE INDEX "tool_variations_scoped_src_tool_name_key" ON "tool_variations" ("group_id", "src_tool_name") WHERE (deleted IS FALSE);
