-- Enable PII scanning on all existing risk policies that only have gitleaks.
UPDATE risk_policies
SET sources = sources || '{presidio}'
  , presidio_entities = '{PERSON,EMAIL_ADDRESS,PHONE_NUMBER,LOCATION,IP_ADDRESS,URL,MAC_ADDRESS,DATE_TIME,NRP,CREDIT_CARD,CRYPTO,IBAN_CODE,US_BANK_NUMBER,US_SSN,US_ITIN,US_PASSPORT,US_DRIVER_LICENSE,UK_NHS,UK_NINO,UK_PASSPORT,ES_NIF,IT_FISCAL_CODE,AU_TFN,IN_PAN,IN_AADHAAR,SG_NRIC_FIN,MEDICAL_LICENSE,US_MBI,US_NPI,MEDICAL_DISEASE_DISORDER,MEDICAL_MEDICATION,MEDICAL_THERAPEUTIC_PROCEDURE,MEDICAL_CLINICAL_EVENT,MEDICAL_BIOLOGICAL_ATTRIBUTE,MEDICAL_FAMILY_HISTORY}'
  , version = version + 1
WHERE NOT sources @> '{presidio}'
  AND deleted IS FALSE;
