// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationFeature struct {
	// @access: confidential
	ID int64
	// @access: confidential
	OrganizationID string
	// @access: confidential
	FeatureName string
	// @access: confidential
	CreatedAt pgtype.Timestamptz
	// @access: confidential
	UpdatedAt pgtype.Timestamptz
	// @access: confidential
	DeletedAt pgtype.Timestamptz
	// @access: confidential
	Deleted bool
}
