/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  ToolUsageUserFilter,
  ToolUsageUserFilter$Outbound,
  ToolUsageUserFilter$outboundSchema,
} from "./toolusageuserfilter.js";

/**
 * Tool usage target type
 */
export const TargetTypes = {
  HostedMcpServer: "hosted_mcp_server",
  TunneledMcpServer: "tunneled_mcp_server",
  ShadowMcpServer: "shadow_mcp_server",
  LocalTool: "local_tool",
  Skill: "skill",
} as const;
/**
 * Tool usage target type
 */
export type TargetTypes = ClosedEnum<typeof TargetTypes>;

/**
 * Payload for target-aware MCP and tool usage metrics
 */
export type GetToolUsageSummaryPayload = {
  /**
   * Optional account type filter ('team' or 'personal').
   */
  accountType?: string | undefined;
  /**
   * Start time in ISO 8601 format
   */
  from: Date;
  /**
   * Hook plugin sources to include. Direct hosted MCP calls have no hook source and are excluded when this filter is set.
   */
  hookSources?: Array<string> | undefined;
  /**
   * Hosted MCP toolset slugs to include
   */
  hostedToolsetSlugs?: Array<string> | undefined;
  /**
   * Shadow MCP server names to include
   */
  shadowServerNames?: Array<string> | undefined;
  /**
   * Target types to include. Empty means all target types.
   */
  targetTypes?: Array<TargetTypes> | undefined;
  /**
   * End time in ISO 8601 format
   */
  to: Date;
  /**
   * Typed user identities to include
   */
  userFilters?: Array<ToolUsageUserFilter> | undefined;
};

/** @internal */
export const TargetTypes$outboundSchema: z.ZodMiniEnum<typeof TargetTypes> = z
  .enum(TargetTypes);

/** @internal */
export type GetToolUsageSummaryPayload$Outbound = {
  account_type?: string | undefined;
  from: string;
  hook_sources?: Array<string> | undefined;
  hosted_toolset_slugs?: Array<string> | undefined;
  shadow_server_names?: Array<string> | undefined;
  target_types?: Array<string> | undefined;
  to: string;
  user_filters?: Array<ToolUsageUserFilter$Outbound> | undefined;
};

/** @internal */
export const GetToolUsageSummaryPayload$outboundSchema: z.ZodMiniType<
  GetToolUsageSummaryPayload$Outbound,
  GetToolUsageSummaryPayload
> = z.pipe(
  z.object({
    accountType: z.optional(z.string()),
    from: z.pipe(z.date(), z.transform(v => v.toISOString())),
    hookSources: z.optional(z.array(z.string())),
    hostedToolsetSlugs: z.optional(z.array(z.string())),
    shadowServerNames: z.optional(z.array(z.string())),
    targetTypes: z.optional(z.array(TargetTypes$outboundSchema)),
    to: z.pipe(z.date(), z.transform(v => v.toISOString())),
    userFilters: z.optional(z.array(ToolUsageUserFilter$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      accountType: "account_type",
      hookSources: "hook_sources",
      hostedToolsetSlugs: "hosted_toolset_slugs",
      shadowServerNames: "shadow_server_names",
      targetTypes: "target_types",
      userFilters: "user_filters",
    });
  }),
);

export function getToolUsageSummaryPayloadToJSON(
  getToolUsageSummaryPayload: GetToolUsageSummaryPayload,
): string {
  return JSON.stringify(
    GetToolUsageSummaryPayload$outboundSchema.parse(getToolUsageSummaryPayload),
  );
}
