/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type IdentityProviderSetupValue = {
  key: string;
  value: string;
};

/** @internal */
export type IdentityProviderSetupValue$Outbound = {
  key: string;
  value: string;
};

/** @internal */
export const IdentityProviderSetupValue$outboundSchema: z.ZodMiniType<
  IdentityProviderSetupValue$Outbound,
  IdentityProviderSetupValue
> = z.object({
  key: z.string(),
  value: z.string(),
});

export function identityProviderSetupValueToJSON(
  identityProviderSetupValue: IdentityProviderSetupValue,
): string {
  return JSON.stringify(
    IdentityProviderSetupValue$outboundSchema.parse(identityProviderSetupValue),
  );
}
