/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ToolActivityCall = {
  /**
   * The tool name.
   */
  name: string;
};

/** @internal */
export type ToolActivityCall$Outbound = {
  name: string;
};

/** @internal */
export const ToolActivityCall$outboundSchema: z.ZodMiniType<
  ToolActivityCall$Outbound,
  ToolActivityCall
> = z.object({
  name: z.string(),
});

export function toolActivityCallToJSON(
  toolActivityCall: ToolActivityCall,
): string {
  return JSON.stringify(
    ToolActivityCall$outboundSchema.parse(toolActivityCall),
  );
}
