/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateIngressRequestBody = {
  /**
   * Whether the ingress node should be running
   */
  enabled?: boolean | undefined;
  /**
   * Replacement device hostname
   */
  hostname?: string | undefined;
  /**
   * Whether requests without an attributable network identity are rejected
   */
  identityRequired?: boolean | undefined;
  /**
   * Whether public access to the org's MCP endpoints is disabled
   */
  privateNetworkOnly?: boolean | undefined;
};

/** @internal */
export type UpdateIngressRequestBody$Outbound = {
  enabled?: boolean | undefined;
  hostname?: string | undefined;
  identity_required?: boolean | undefined;
  private_network_only?: boolean | undefined;
};

/** @internal */
export const UpdateIngressRequestBody$outboundSchema: z.ZodMiniType<
  UpdateIngressRequestBody$Outbound,
  UpdateIngressRequestBody
> = z.pipe(
  z.object({
    enabled: z.optional(z.boolean()),
    hostname: z.optional(z.string()),
    identityRequired: z.optional(z.boolean()),
    privateNetworkOnly: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      identityRequired: "identity_required",
      privateNetworkOnly: "private_network_only",
    });
  }),
);

export function updateIngressRequestBodyToJSON(
  updateIngressRequestBody: UpdateIngressRequestBody,
): string {
  return JSON.stringify(
    UpdateIngressRequestBody$outboundSchema.parse(updateIngressRequestBody),
  );
}
