-- create "authz_challenges" table
CREATE TABLE `authz_challenges` (
  `id` UUID DEFAULT generateUUIDv7() COMMENT 'Unique identifier for the challenge entry.',
  `timestamp` DateTime64(9) COMMENT 'Time the authz decision was made.' CODEC(DoubleDelta, ZSTD(1)),
  `organization_id` String COMMENT 'Organization the principal was acting in.' CODEC(ZSTD(1)),
  `project_id` String DEFAULT '' COMMENT 'Project the check was scoped to. Empty string when the check is org-level (kept non-nullable so it can sit in the primary key).' CODEC(ZSTD(1)),
  `trace_id` FixedString(32) COMMENT 'W3C trace ID linking the challenge to the originating request.',
  `span_id` FixedString(16) COMMENT 'W3C span ID for the specific operation that triggered the challenge.',
  `request_id` Nullable(String) COMMENT 'Internal request ID from RequestContext (when set).' CODEC(ZSTD(1)),
  `principal_urn` String COMMENT 'Primary principal URN (e.g. user:<uuid> or api_key:<id>).' CODEC(ZSTD(1)),
  `principal_type` LowCardinality(String) COMMENT 'Principal kind: user | api_key | assistant.',
  `user_id` Nullable(String) COMMENT 'AuthContext.UserID at decision time.' CODEC(ZSTD(1)),
  `user_external_id` Nullable(String) COMMENT 'Customer-supplied external user identifier.' CODEC(ZSTD(1)),
  `user_email` Nullable(String) COMMENT 'AuthContext.Email when present (session auth path).' CODEC(ZSTD(1)),
  `api_key_id` Nullable(String) COMMENT 'API key ID for api_key principals.' CODEC(ZSTD(1)),
  `session_id` Nullable(String) COMMENT 'Session ID for session-authed principals.' CODEC(ZSTD(1)),
  `role_slugs` Array(LowCardinality(String)) COMMENT 'Role principal URNs whose grants were loaded for this principal.',
  `operation` LowCardinality(String) COMMENT 'Authz operation: require | require_any | filter.',
  `outcome` LowCardinality(String) COMMENT 'Decision outcome: allow | deny | error.',
  `reason` LowCardinality(String) COMMENT 'Reason: grant_matched | no_grants | scope_unsatisfied | invalid_check | rbac_skipped_apikey | dev_override.',
  `scope` LowCardinality(String) COMMENT 'Scope of the focus check.',
  `resource_kind` LowCardinality(String) COMMENT 'Resource kind of the focus check.',
  `resource_id` String COMMENT 'Resource ID of the focus check.' CODEC(ZSTD(1)),
  `selector` String COMMENT 'JSON selector of the focus check.' CODEC(ZSTD(1)),
  `expanded_scopes` Array(LowCardinality(String)) COMMENT 'Scope hierarchy expansion of the focus check.',
  `requested_checks.scope` Array(LowCardinality(String)) COMMENT 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  `requested_checks.resource_kind` Array(LowCardinality(String)) COMMENT 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  `requested_checks.resource_id` Array(String) COMMENT 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  `requested_checks.selector` Array(String) COMMENT 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  `matched_grants.principal_urn` Array(String) COMMENT 'Grants that satisfied at least one requested check. Empty on deny.',
  `matched_grants.scope` Array(LowCardinality(String)) COMMENT 'Grants that satisfied at least one requested check. Empty on deny.',
  `matched_grants.selector` Array(String) COMMENT 'Grants that satisfied at least one requested check. Empty on deny.',
  `matched_grants.matched_via_check_scope` Array(LowCardinality(String)) COMMENT 'Grants that satisfied at least one requested check. Empty on deny.',
  `evaluated_grant_count` UInt32 COMMENT 'Total grants the principal had loaded on context at decision time.',
  `filter_candidate_count` UInt32 DEFAULT '0' COMMENT 'Number of resource IDs the Filter call considered.',
  `filter_allowed_count` UInt32 DEFAULT '0' COMMENT 'Number of resource IDs the Filter call returned as allowed.',
  INDEX `idx_authz_challenges_api_key_id` ((api_key_id)) TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX `idx_authz_challenges_principal_urn` ((principal_urn)) TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX `idx_authz_challenges_reason` ((reason)) TYPE set(0) GRANULARITY 4,
  INDEX `idx_authz_challenges_resource_id` ((resource_id)) TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX `idx_authz_challenges_scope` ((scope)) TYPE set(0) GRANULARITY 4,
  INDEX `idx_authz_challenges_session_id` ((session_id)) TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX `idx_authz_challenges_trace_id` ((trace_id)) TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX `idx_authz_challenges_user_id` ((user_id)) TYPE bloom_filter(0.01) GRANULARITY 1
) ENGINE = MergeTree
PRIMARY KEY (`organization_id`, `project_id`, `outcome`, `timestamp`, `id`) ORDER BY (`organization_id`, `project_id`, `outcome`, `timestamp`, `id`) PARTITION BY (toYYYYMMDD(timestamp)) TTL toDateTime(timestamp) + toIntervalDay(30) SETTINGS index_granularity = 8192 COMMENT 'Authz challenge log: every authz decision (allow + deny) for forensics and the Challenge UI.';
