-- Restore the previous view definition in place, for the same reason the up
-- migration swaps it in place: a drop and recreate loses traces in between.
ALTER TABLE `gram`.`trace_summaries_mv` MODIFY QUERY SELECT trace_id, gram_project_id, any(gram_deployment_id) AS gram_deployment_id, any(gram_function_id) AS gram_function_id, any(gram_urn) AS gram_urn, max(tool_name) AS tool_name, any(tool_source) AS tool_source, any(event_source) AS event_source, any(user_email) AS user_email, any(hook_source) AS hook_source, any(skill_name) AS skill_name, anyIf(toolset_slug, toolset_slug != '') AS toolset_slug, anyIf(external_user_id, external_user_id != '') AS external_user_id, anyIf(user_id, user_id != '') AS user_id, max(if((telemetry_logs.event_source IN ('tool_call', 'resource_read', 'meta_discovery')) AND (toString(attributes.gram.authorization.actor.type) = 'agent'), toString(attributes.gram.authorization.actor.id), '')) AS agent_id, anyIf(toString(attributes.gram.mcp.match), toString(attributes.gram.mcp.match) != '') AS mcp_match, anyIf(toString(attributes.gram.mcp.server_url), toString(attributes.gram.mcp.server_url) != '') AS mcp_server_url, min(time_unix_nano) AS start_time_unix_nano, toUInt64(count(*)) AS log_count, anyIfState(toInt32OrNull(toString(attributes.http.response.status_code)), toString(attributes.http.response.status_code) != '') AS http_status_code, max(if(toString(attributes.gen_ai.tool.call.result) != '', 1, 0)) AS has_result, max(if(toString(attributes.gram.hook.error) != '', 1, 0)) AS has_error, max(if(toString(attributes.gram.hook.block_reason) != '', 1, 0)) AS has_block, anyIf(toString(attributes.gram.hook.block_reason), toString(attributes.gram.hook.block_reason) != '') AS block_reason, anyIf(account_type, account_type != '') AS account_type, anyIf(provider, provider != '') AS provider, anyIf(meta_mcp_server_id, meta_mcp_server_id != '') AS meta_mcp_server_id FROM gram.telemetry_logs WHERE (trace_id IS NOT NULL) AND (trace_id != '') AND (NOT startsWith(telemetry_logs.gram_urn, 'urn:uuid:')) GROUP BY trace_id, gram_project_id;
ALTER TABLE `gram`.`trace_summaries`
  DROP COLUMN `mcp_client_version`,
  DROP COLUMN `mcp_client_name`;
ALTER TABLE `gram`.`telemetry_logs`
  DROP INDEX `idx_telemetry_logs_mat_mcp_client_name`,
  DROP COLUMN `mcp_client_version`,
  DROP COLUMN `mcp_client_name`;
