ALTER TABLE `gram`.`billing_meter_readings_by_time`
  ADD COLUMN `account_type` LowCardinality(String) MATERIALIZED attributes['account_type'] COMMENT 'Frozen reporting attribute for account type.' AFTER `tokenizer_codec`,
  ADD COLUMN `assistant_id` String MATERIALIZED attributes['assistant_id'] COMMENT 'Frozen reporting attribute for assistant identity.' AFTER `account_type`,
  ADD COLUMN `billing_mode` LowCardinality(String) MATERIALIZED attributes['billing_mode'] COMMENT 'Frozen reporting attribute for billing mode.' AFTER `assistant_id`,
  ADD COLUMN `billing_user_account_email` String MATERIALIZED attributes['billing_user_account_email'] COMMENT 'Frozen reporting label for the billing user.' AFTER `billing_mode`,
  ADD COLUMN `billing_user_cost_center_name` LowCardinality(String) MATERIALIZED attributes['billing_user_cost_center_name'] COMMENT 'Frozen reporting attribute for billing-user cost center.' AFTER `billing_user_account_email`,
  ADD COLUMN `billing_user_department_name` LowCardinality(String) MATERIALIZED attributes['billing_user_department_name'] COMMENT 'Frozen reporting attribute for billing-user department.' AFTER `billing_user_cost_center_name`,
  ADD COLUMN `billing_user_directory_groups` LowCardinality(String) MATERIALIZED attributes['billing_user_directory_groups'] COMMENT 'Frozen JSON directory-group set for reporting.' AFTER `billing_user_department_name`,
  ADD COLUMN `billing_user_division_name` LowCardinality(String) MATERIALIZED attributes['billing_user_division_name'] COMMENT 'Frozen reporting attribute for billing-user division.' AFTER `billing_user_directory_groups`,
  ADD COLUMN `billing_user_employee_type` LowCardinality(String) MATERIALIZED attributes['billing_user_employee_type'] COMMENT 'Frozen reporting attribute for billing-user employee type.' AFTER `billing_user_division_name`,
  ADD COLUMN `billing_user_id` String MATERIALIZED attributes['billing_user_id'] COMMENT 'Frozen reporting identity of the billing user.' AFTER `billing_user_employee_type`,
  ADD COLUMN `billing_user_job_title` LowCardinality(String) MATERIALIZED attributes['billing_user_job_title'] COMMENT 'Frozen reporting attribute for billing-user job title.' AFTER `billing_user_id`,
  ADD COLUMN `billing_user_rbac_roles` LowCardinality(String) MATERIALIZED attributes['billing_user_rbac_roles'] COMMENT 'Frozen JSON RBAC role set for reporting.' AFTER `billing_user_job_title`,
  ADD COLUMN `custom_domain` String MATERIALIZED attributes['custom_domain'] COMMENT 'Frozen reporting attribute for the custom domain.' AFTER `billing_user_rbac_roles`,
  ADD COLUMN `hook_hostname` String MATERIALIZED attributes['hook_hostname'] COMMENT 'Frozen reporting attribute for the agent device.' AFTER `custom_domain`,
  ADD COLUMN `hook_source` LowCardinality(String) MATERIALIZED attributes['hook_source'] COMMENT 'Frozen reporting attribute for the agent source.' AFTER `hook_hostname`,
  ADD COLUMN `mcp_server_id` String MATERIALIZED attributes['mcp_server_id'] COMMENT 'Frozen reporting identity of the MCP server.' AFTER `hook_source`,
  ADD COLUMN `mcp_server_slug` String MATERIALIZED attributes['mcp_server_slug'] COMMENT 'Frozen reporting label for the MCP server.' AFTER `mcp_server_id`,
  ADD COLUMN `mcp_server_type` LowCardinality(String) MATERIALIZED attributes['mcp_server_type'] COMMENT 'Frozen reporting namespace for the MCP server.' AFTER `mcp_server_slug`,
  ADD COLUMN `message_link_reason` LowCardinality(String) MATERIALIZED attributes['message_link_reason'] COMMENT 'Frozen reporting attribute for message-link reason.' AFTER `mcp_server_type`,
  ADD COLUMN `message_link_status` LowCardinality(String) MATERIALIZED attributes['message_link_status'] COMMENT 'Frozen reporting attribute for message-link status.' AFTER `message_link_reason`,
  ADD COLUMN `message_type` LowCardinality(String) MATERIALIZED attributes['message_type'] COMMENT 'Frozen reporting attribute for message type.' AFTER `message_link_status`,
  ADD COLUMN `message_user_id` String MATERIALIZED attributes['message_user_id'] COMMENT 'Frozen reporting attribute for message user identity.' AFTER `message_type`,
  ADD COLUMN `model` LowCardinality(String) MATERIALIZED attributes['model'] COMMENT 'Frozen reporting attribute for the model.' AFTER `message_user_id`,
  ADD COLUMN `provider` LowCardinality(String) MATERIALIZED attributes['provider'] COMMENT 'Frozen reporting attribute for the provider.' AFTER `model`,
  ADD COLUMN `request_path` String MATERIALIZED attributes['request_path'] COMMENT 'Frozen reporting attribute for the request path.' AFTER `provider`,
  ADD COLUMN `risk_policy_id` String MATERIALIZED attributes['risk_policy_id'] COMMENT 'Frozen reporting attribute for risk-policy identity.' AFTER `request_path`,
  ADD COLUMN `risk_policy_link_reason` LowCardinality(String) MATERIALIZED attributes['risk_policy_link_reason'] COMMENT 'Frozen reporting attribute for risk-policy-link reason.' AFTER `risk_policy_id`,
  ADD COLUMN `risk_policy_link_status` LowCardinality(String) MATERIALIZED attributes['risk_policy_link_status'] COMMENT 'Frozen reporting attribute for risk-policy-link status.' AFTER `risk_policy_link_reason`,
  ADD COLUMN `risk_policy_version` LowCardinality(String) MATERIALIZED attributes['risk_policy_version'] COMMENT 'Frozen reporting attribute for risk-policy version.' AFTER `risk_policy_link_status`,
  ADD COLUMN `scan_execution_path` LowCardinality(String) MATERIALIZED attributes['scan_execution_path'] COMMENT 'Frozen reporting attribute for scan execution path.' AFTER `risk_policy_version`,
  ADD COLUMN `tool_name` LowCardinality(String) MATERIALIZED attributes['tool_name'] COMMENT 'Frozen reporting attribute for tool name.' AFTER `scan_execution_path`,
  ADD COLUMN `workload_source` LowCardinality(String) MATERIALIZED attributes['workload_source'] COMMENT 'Frozen reporting attribute for workload source.';
