ALTER TABLE `gram`.`trace_summaries`
  MODIFY COLUMN `mcp_client_version` REMOVE COMMENT,
  MODIFY COLUMN `mcp_client_name` REMOVE COMMENT,
  MODIFY COLUMN `meta_mcp_server_id` REMOVE COMMENT,
  MODIFY COLUMN `provider` REMOVE COMMENT,
  MODIFY COLUMN `account_type` REMOVE COMMENT,
  MODIFY COLUMN `mcp_server_url` REMOVE COMMENT,
  MODIFY COLUMN `mcp_match` REMOVE COMMENT,
  MODIFY COLUMN `agent_id` REMOVE COMMENT,
  MODIFY COLUMN `user_id` REMOVE COMMENT,
  MODIFY COLUMN `external_user_id` REMOVE COMMENT,
  MODIFY COLUMN `toolset_slug` REMOVE COMMENT,
  MODIFY COLUMN `block_reason` REMOVE COMMENT,
  MODIFY COLUMN `has_block` REMOVE COMMENT,
  MODIFY COLUMN `has_error` REMOVE COMMENT,
  MODIFY COLUMN `has_result` REMOVE COMMENT,
  MODIFY COLUMN `skill_name` REMOVE COMMENT,
  MODIFY COLUMN `hook_source` REMOVE COMMENT,
  MODIFY COLUMN `user_email` REMOVE COMMENT,
  MODIFY COLUMN `event_source` REMOVE COMMENT,
  MODIFY COLUMN `tool_source` REMOVE COMMENT,
  MODIFY COLUMN `tool_name` REMOVE COMMENT,
  MODIFY COLUMN `http_status_code` REMOVE COMMENT,
  MODIFY COLUMN `log_count` REMOVE COMMENT,
  MODIFY COLUMN `start_time_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `gram_urn` REMOVE COMMENT,
  MODIFY COLUMN `gram_function_id` REMOVE COMMENT,
  MODIFY COLUMN `gram_deployment_id` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT,
  MODIFY COLUMN `trace_id` REMOVE COMMENT;
ALTER TABLE `gram`.`telemetry_logs_staging`
  COMMENT COLUMN `org_id` 'Gram org id (materialized from attributes.gram.org.id) — the attribution tuple join scope. The tuple is keyed by org, not project, because the hooks key and the OTEL exporter key can resolve different projects.',
  COMMENT COLUMN `request_id` 'Claude API request id (materialized from attributes.request_id) — the attribution join key.',
  COMMENT COLUMN `chat_id` 'Chat ID (materialized from attributes.gen_ai.conversation.id) — the promotion worker scopes by this.',
  COMMENT COLUMN `gram_chat_id` 'The Chat ID (Claude session id) associated with the log.',
  COMMENT COLUMN `service_version` 'Service version.',
  COMMENT COLUMN `service_name` 'Logical service name.',
  COMMENT COLUMN `gram_urn` 'The Gram URN (e.g. claude-code:otel:logs).',
  COMMENT COLUMN `gram_function_id` 'Function ID that generated the log (null for HTTP logs).',
  COMMENT COLUMN `gram_deployment_id` 'Deployment ID (denormalized from resource_attributes).',
  COMMENT COLUMN `gram_project_id` 'Project ID (denormalized from resource_attributes).',
  COMMENT COLUMN `resource_attributes` 'Attributes describing the resource that generated this log.',
  COMMENT COLUMN `attributes` 'Additional attributes about the specific event occurrence.',
  COMMENT COLUMN `span_id` 'W3C span ID for specific operation within a trace.',
  COMMENT COLUMN `trace_id` 'W3C trace ID linking related logs across services.',
  COMMENT COLUMN `body` 'The primary log message extracted from the log record.',
  COMMENT COLUMN `severity_text` 'Text representation of severity (DEBUG, INFO, WARN, ERROR, FATAL).',
  COMMENT COLUMN `observed_timestamp` 'Human-readable timestamp derived from observed_time_unix_nano.',
  COMMENT COLUMN `observed_time_unix_nano` 'Unix time (ns) when the event was observed by the collection system.',
  COMMENT COLUMN `time_unix_nano` 'Unix time (ns) when the event occurred measured by the origin clock.',
  COMMENT COLUMN `id` 'Unique identifier for the log entry, preserved when the row is promoted to telemetry_logs.';
ALTER TABLE `gram`.`telemetry_logs`
  COMMENT COLUMN `mcp_client_version` 'MCP client version reported alongside mcp_client_name. Empty when the client reported a name but no version (materialized from attributes.gram.mcp.client.version).',
  COMMENT COLUMN `mcp_client_name` 'MCP client name self-reported at the initialize handshake or in the per-request _meta hint. Untrusted, attribution only. Empty for hook-observed and non-MCP traffic (materialized from attributes.gram.mcp.client.name).',
  COMMENT COLUMN `meta_mcp_server_id` 'Meta MCP server (Gateway Endpoint) ID when the call was dispatched through a gateway (materialized from attributes.gram.meta_mcp_server.id).',
  COMMENT COLUMN `event_urn` 'Canonical event identity in the form urn:telemetry:<origin>:<kind>:<type> where origin is the observation channel (provider_otel | provider_api | agent_hook | gram_service | unknown), kind is the signal shape (log | metric | span) and type is the producer event type lowercased. Stamped by telemetry.Logger. Empty on rows written before the column existed (materialized from attributes.gram.event.urn).',
  COMMENT COLUMN `billing_mode` 'How the account is billed: metered (pay-per-token, cost is real spend) | flat_rate (subscription seat, cost is an estimate) | unknown | empty. Resolved by ingest from admin-declared config (materialized from attributes.gram.billing_mode).',
  COMMENT COLUMN `account_type` 'team (company/enterprise account) or personal (individual account). Set by ingest. Empty until classified (materialized from attributes.gram.account_type).',
  COMMENT COLUMN `external_org_id` 'Provider organization id for the account the user was logged into on-device (e.g. Claude organization.id). Distinct from the Gram org. Personal-account tracking discriminator. Normalized by ingest (materialized from attributes.gram.external_org_id).',
  COMMENT COLUMN `provider` 'AI provider for the session account (e.g. anthropic, openai). Set by ingest (materialized from attributes.gram.provider).',
  COMMENT COLUMN `mcp_server_id` 'MCP server ID (materialized from attributes.gram.mcp_server.id).',
  COMMENT COLUMN `remote_mcp_server_id` 'Remote MCP server ID (materialized from attributes.gram.remote_mcp_server.id).',
  COMMENT COLUMN `hook_block_reason` 'Hook block reason set when the Gram hook denied a tool call (materialized from attributes.gram.hook.block_reason).',
  COMMENT COLUMN `skill_name` 'Skill name extracted from tool arguments when tool_name is Skill (materialized).',
  COMMENT COLUMN `hook_source` 'Hook source (materialized from attributes.gram.hook.source).',
  COMMENT COLUMN `user_email` 'User email (materialized from attributes.user.email).',
  COMMENT COLUMN `toolset_slug` 'Toolset slug (materialized from attributes.gram.toolset.slug).',
  COMMENT COLUMN `event_source` 'Event source (materialized from attributes.gram.event.source).',
  COMMENT COLUMN `tool_source` 'Tool call source (materialized from attributes.gram.tool_call.source).',
  COMMENT COLUMN `tool_name` 'Tool name (materialized from attributes.gram.tool.name).',
  COMMENT COLUMN `evaluation_score_label` 'Evaluation result label (success, failure, partial, abandoned).',
  COMMENT COLUMN `api_key_id` 'API key ID (materialized from attributes.gram.api_key.id).',
  COMMENT COLUMN `external_user_id` 'External user ID (materialized from attributes.gram.external_user.id).',
  COMMENT COLUMN `user_id` 'User ID (materialized from attributes.user.id).',
  COMMENT COLUMN `chat_id` 'Chat ID (materialized from attributes.gen_ai.conversation.id).',
  COMMENT COLUMN `urn` 'Tool URN (materialized from attributes.gram.tool.urn).',
  COMMENT COLUMN `function_id` 'Function ID (materialized from attributes.gram.function.id).',
  COMMENT COLUMN `deployment_id` 'Deployment ID (materialized from resource_attributes.gram.deployment.id).',
  COMMENT COLUMN `project_id` 'Project ID (materialized from attributes.gram.project.id).',
  COMMENT COLUMN `gram_chat_id` 'The Chat ID associated with the log (if generated by chat).',
  COMMENT COLUMN `observed_timestamp` 'Human-readable timestamp derived from observed_time_unix_nano.',
  COMMENT COLUMN `service_version` 'Service version.',
  COMMENT COLUMN `service_name` 'Logical service name (e.g., gram-functions, gram-http-gateway).',
  COMMENT COLUMN `gram_urn` 'The Gram URN (e.g. tools:function:my-source:my-tool).',
  COMMENT COLUMN `gram_function_id` 'Function ID that generated the log (null for HTTP logs).',
  COMMENT COLUMN `gram_deployment_id` 'Deployment ID (denormalized from resource_attributes).',
  COMMENT COLUMN `gram_project_id` 'Project ID (denormalized from resource_attributes).',
  COMMENT COLUMN `resource_attributes` 'Attributes describing the resource that generated this log.',
  COMMENT COLUMN `attributes` 'Additional attributes about the specific event occurrence.',
  COMMENT COLUMN `span_id` 'W3C span ID for specific operation within a trace.',
  COMMENT COLUMN `trace_id` 'W3C trace ID linking related logs across services.',
  COMMENT COLUMN `body` 'The primary log message extracted from the log record. For structured logs, this is the human-readable message component.',
  COMMENT COLUMN `severity_text` 'Text representation of severity (DEBUG, INFO, WARN, ERROR, FATAL).',
  COMMENT COLUMN `observed_time_unix_nano` 'Unix time (ns) when the event was observed by the collection system.',
  COMMENT COLUMN `time_unix_nano` 'Unix time (ns) when the event occurred measured by the origin clock.',
  COMMENT COLUMN `id` 'Unique identifier for the log entry.';
ALTER TABLE `gram`.`spend_rule_usage_summaries`
  MODIFY COLUMN `total_cost` REMOVE COMMENT,
  MODIFY COLUMN `time_bucket` REMOVE COMMENT,
  MODIFY COLUMN `user_email` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`skill_session_versions`
  COMMENT COLUMN `surface` 'Observation surface: dev | assistant.',
  COMMENT COLUMN `canonical_sha256` 'Canonical SHA-256 digest of the observed skill.',
  COMMENT COLUMN `skill_version_id` 'Observed skill version identifier.',
  COMMENT COLUMN `skill_id` 'Observed skill identifier.',
  COMMENT COLUMN `session_id` 'Session identifier.',
  COMMENT COLUMN `project_id` 'Project the session belongs to.',
  COMMENT COLUMN `organization_id` 'Organization the session belongs to.',
  COMMENT COLUMN `seen_at` 'Time the skill version became active in the session.',
  COMMENT COLUMN `inserted_at` 'Time the mapping was inserted.',
  COMMENT COLUMN `created_at` 'Time the mapping was created.',
  COMMENT COLUMN `id` 'Source observation identifier.';
ALTER TABLE `gram`.`skill_efficacy_scores`
  COMMENT COLUMN `judge_prompt_version` 'Judge prompt version.',
  COMMENT COLUMN `judge_model` 'Model used to judge efficacy.',
  COMMENT COLUMN `flags` 'Assessment flags: ignored | misapplied | partially_followed | harmful.',
  COMMENT COLUMN `roi_confidence` 'ROI estimate confidence when estimated: low | med | high.',
  COMMENT COLUMN `est_minutes_saved` 'Estimated minutes saved.',
  COMMENT COLUMN `est_turns_saved` 'Estimated conversation turns saved.',
  COMMENT COLUMN `rationale` 'Judge rationale for the score, capped at 200 characters.',
  COMMENT COLUMN `score` 'Skill efficacy score in the range 0.0 to 1.0.',
  COMMENT COLUMN `gram_chat_id` 'Gram chat identifier when available.',
  COMMENT COLUMN `trace_id` 'W3C trace ID for the evaluated session when available.',
  COMMENT COLUMN `surface` 'Evaluation surface: dev | assistant.',
  COMMENT COLUMN `canonical_sha256` 'Canonical SHA-256 digest of the evaluated skill.',
  COMMENT COLUMN `skill_version_id` 'Evaluated skill version identifier.',
  COMMENT COLUMN `skill_id` 'Evaluated skill identifier.',
  COMMENT COLUMN `session_id` 'Scoring session identifier, using the hook session ID for dev and chat ID for assistant.',
  COMMENT COLUMN `project_id` 'Project the score belongs to when known.',
  COMMENT COLUMN `organization_id` 'Organization the score belongs to.',
  COMMENT COLUMN `inserted_at` 'Time the score was inserted.',
  COMMENT COLUMN `created_at` 'Time the score was completed.',
  COMMENT COLUMN `id` 'Producer-supplied score identifier.';
ALTER TABLE `gram`.`shadow_mcp_inventory_urls`
  MODIFY COLUMN `updated_at` REMOVE COMMENT,
  MODIFY COLUMN `last_seen` REMOVE COMMENT,
  MODIFY COLUMN `first_seen` REMOVE COMMENT,
  MODIFY COLUMN `server_name_override` REMOVE COMMENT,
  MODIFY COLUMN `server_name` REMOVE COMMENT,
  MODIFY COLUMN `url_host` REMOVE COMMENT,
  MODIFY COLUMN `canonical_server_url` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`risk_findings`
  COMMENT COLUMN `shadow` 'Set to 1 on findings the LLM analyzer produced while the organization ran the shadow risk engine mode, recorded to compare the model with the legacy engines per message and never enforced. Every user-facing read path filters shadow = 0, so shadow rows are hidden from Risk Events, the overview, signals, the Watchdog and reveal by default. 0 on every enforcing finding and on rows written before this column existed.',
  COMMENT COLUMN `enforcement_outcome` 'Enforcement action taken, independent of detection. Empty when unspecified or legacy.',
  COMMENT COLUMN `identity_stamped` 'Whether validated principal provenance was present, including validated anonymous sessions.',
  COMMENT COLUMN `principal_kind` 'Credential class established exclusively by mcpidentity. Empty when unstamped.',
  COMMENT COLUMN `mcp_method` 'MCP method or equivalent mediated operation, such as tools/call.',
  COMMENT COLUMN `mediation_surface` 'Concrete mediation seam producing the finding.',
  COMMENT COLUMN `phase` 'Inspection phase: request or response. Empty for legacy findings.',
  COMMENT COLUMN `tool_name` 'Resolved concrete tool name, empty when unavailable.',
  COMMENT COLUMN `toolset_id` 'Persisted toolset ID, empty for runtime-only or unavailable toolsets.',
  COMMENT COLUMN `meta_mcp_server_id` 'Outer meta MCP gateway ID, separate from the concrete member server.',
  COMMENT COLUMN `mcp_server_id` 'Canonical concrete MCP server ID. Empty when unavailable.',
  COMMENT COLUMN `execution_id` 'Correlation ID of one mediated execution. Empty for legacy and chat-only findings.',
  COMMENT COLUMN `event_kind` 'Kind of this copy of the finding: finding (scanner output, dead-letter sentinels included), suppression or unsuppression (appended state-change copies from manual dismiss/undo and the retroactive exclusion reconcile). Empty on rows written before this column existed - such rows rank as finding copies.',
  COMMENT COLUMN `excluded_detail` 'Free-form context for the suppression: the user-supplied dismissal reason for manual rows, the false-positive catalog reason for automated rows. Empty for rule rows and when no reason was given.',
  COMMENT COLUMN `excluded_reason` 'Why the finding was suppressed: rule (exclusion rule, exclusion_id set), manual (dismissed by a user via UI or agent tool) or automated (offline false-positive sweep). Empty when the finding is not suppressed or on legacy rows written before this column existed.',
  COMMENT COLUMN `user_email` 'Email of the resolved internal user at ingest (users.email), letting the Watchdog display users without a Postgres lookup. Empty for external-only users or when attribution is unresolved.',
  COMMENT COLUMN `team` 'WorkOS directory department_name of the resolved user at ingest. Empty when the user has no directory profile or attribution is unresolved.',
  COMMENT COLUMN `chat_source` 'Canonical product surface the scanned message came from (chat_messages.source canonicalized at ingest, e.g. codex, cursor, claude-code). Empty for rows written before the column existed or when attribution is unresolved.',
  COMMENT COLUMN `tool_call_id` 'Recorded tool call id anchoring the finding when the scanned text belongs to a tool call. Empty when not applicable or unknown.',
  COMMENT COLUMN `path` 'JSON path of the extracted value within the field for json_path surfaces, gjson syntax. Empty otherwise.',
  COMMENT COLUMN `field` 'Scanner field the finding was detected in, e.g. content or tool.args, copied from the scanner span. Empty when unknown.',
  COMMENT COLUMN `surface` 'Which text start_pos and end_pos index: content, scan_surface, tool_args, json_path, derived, legacy_presidio or none. Empty for rows written before this column existed, where reveal falls back to a verified candidate cascade.',
  COMMENT COLUMN `assistant_id` 'Assistant linked to the finding chat via a live assistant_threads row at ingest. Empty when the chat has no assistant link or attribution is unresolved.',
  COMMENT COLUMN `message_created_at` 'Event time of the scanned chat message (chat_messages.created_at). Defaults to created_at (scan time) for rows written before the column existed or when attribution is unresolved.',
  COMMENT COLUMN `content_part_id` 'Chat content part the finding was detected in.',
  COMMENT COLUMN `false_positive_at` 'Time the finding was marked a false positive, mirrored from Postgres after the fact. Null when the finding is not marked.',
  COMMENT COLUMN `category` 'Risk category derived from rule_id and source at ingest, e.g. pii or secrets. Empty when the rule maps to no category.',
  COMMENT COLUMN `external_user_id` 'Resolved external user id: chat_messages.external_user_id with fallback to chats.external_user_id. Empty when unresolved.',
  COMMENT COLUMN `user_id` 'Resolved internal user id: chat_messages.user_id with fallback to chats.user_id. Empty when unresolved.',
  COMMENT COLUMN `chat_id` 'Denormalized chats.id of the chat the finding was detected in. Empty when unresolved.',
  COMMENT COLUMN `exclusion_id` 'Id of the risk_exclusions row that suppressed the finding. Null when the finding is not excluded.',
  COMMENT COLUMN `excluded_at` 'Time the finding was suppressed by an exclusion. Null when the finding is not excluded.',
  COMMENT COLUMN `inserted_at` 'Server-side ingestion time, stamped on insert. Used for ingestion-lag diagnostics and to tie-break redelivered rows sharing the same id.',
  COMMENT COLUMN `fingerprint_tenant_hs256` 'Tenant-qualified fingerprint: base64url HMAC-SHA256 under a per-org HKDF key. Used to dedupe unique matches within an org.',
  COMMENT COLUMN `fingerprint_global_hs256` 'Global fingerprint: base64url HMAC-SHA256 of the match under the current pepper. Stable across tenants.',
  COMMENT COLUMN `fingerprint_pepper_version` 'Pepper keyring version used to compute the fingerprints.',
  COMMENT COLUMN `match_redacted` 'Partial-mask display string rendered as the match by default in listings. General tier shows first 4 and last 2 characters for length 8 and up, first 2 and last 1 for length 5 to 7, first 1 and last 1 below 5, stars in between. Financial-category matches show only the last 4 characters. Emails show ***@ followed by the real domain. Prompt injection, llm_judge and destructive sources leave it empty since the rationale carries the signal. Shadow MCP stores the server identifier verbatim as a documented carve-out. Storing boundary characters of real matches here is a deliberate, signed-off relaxation of the earlier no-plaintext rule per the reveal-from-ClickHouse design. Rows written before the change may still carry the legacy redacted len=N sha=XXXX form.',
  COMMENT COLUMN `match_len` 'Byte length of the raw match, used to render the redacted display.',
  COMMENT COLUMN `dead_letter_reason` 'Non-empty marks a synthetic could-not-analyze sentinel rather than a real finding.',
  COMMENT COLUMN `end_pos` 'Byte offset of the match end within the scanned field.',
  COMMENT COLUMN `start_pos` 'Byte offset of the match start within the scanned field.',
  COMMENT COLUMN `tags` 'Category tags for the finding, e.g. [pii].',
  COMMENT COLUMN `confidence` 'Detection confidence in the range 0.0 to 1.0.',
  COMMENT COLUMN `source` 'Detection source: gitleaks | presidio | shadow_mcp | prompt_injection | llm_judge | account_identity.',
  COMMENT COLUMN `description` 'Human-readable description of the rule that fired.',
  COMMENT COLUMN `rule_id` 'Rule that fired, e.g. pii.email_address.',
  COMMENT COLUMN `risk_policy_version` 'Version of the risk policy at scan time.',
  COMMENT COLUMN `risk_policy_id` 'Risk policy the message was scanned against.',
  COMMENT COLUMN `chat_message_id` 'Chat message the finding was detected in.',
  COMMENT COLUMN `request_id` 'Internal request ID that produced the finding, when set.',
  COMMENT COLUMN `project_id` 'Project the finding was scoped to. Empty string when unknown, kept non-nullable so it can sit in the primary key.',
  COMMENT COLUMN `organization_id` 'Organization the finding belongs to (HKDF salt for the tenant fingerprint).',
  COMMENT COLUMN `created_at` 'Time the finding was produced.',
  COMMENT COLUMN `id` 'Finding UUIDv7, supplied by the scanner that produced it.';
ALTER TABLE `gram`.`projects_staging`
  COMMENT COLUMN `deleted_at` 'When the project was soft-deleted.',
  COMMENT COLUMN `updated_at` 'When the project was last updated.',
  COMMENT COLUMN `created_at` 'When the project was created.',
  COMMENT COLUMN `slug` 'Current project slug within its organization.',
  COMMENT COLUMN `organization_id` 'Organization that owns the project.',
  COMMENT COLUMN `id` 'Gram project identifier.';
ALTER TABLE `gram`.`projects`
  COMMENT COLUMN `deleted_at` 'When the project was soft-deleted.',
  COMMENT COLUMN `updated_at` 'When the project was last updated.',
  COMMENT COLUMN `created_at` 'When the project was created.',
  COMMENT COLUMN `slug` 'Current project slug within its organization.',
  COMMENT COLUMN `organization_id` 'Organization that owns the project.',
  COMMENT COLUMN `id` 'Gram project identifier.';
ALTER TABLE `gram`.`otel_traces`
  COMMENT COLUMN `scope_attributes` 'Instrumentation scope attributes.',
  COMMENT COLUMN `scope_version` 'Instrumentation scope version. Empty when not reported.',
  COMMENT COLUMN `scope_name` 'Instrumentation scope name. The transform pipeline rewrites this to com.speakeasy.ai.logging and keeps the producer scope in span_attributes under speakeasy.original_instrumentation_scope.name.',
  COMMENT COLUMN `resource_schema_url` 'Schema URL of the resource. Empty when not reported.',
  COMMENT COLUMN `resource_attributes` 'Attributes of the resource that produced the span.',
  COMMENT COLUMN `span_attributes` 'Span attributes, including Gram enrichments applied by the transform pipeline.',
  COMMENT COLUMN `trace_state` 'W3C tracestate header value. Empty when not reported.',
  COMMENT COLUMN `status_message` 'Status message, set only when status_code is error.',
  COMMENT COLUMN `status_code` 'OTLP status code: unspecified | ok | error.',
  COMMENT COLUMN `span_kind` 'OTLP span kind: unspecified | internal | server | client | producer | consumer.',
  COMMENT COLUMN `span_name` 'Span name.',
  COMMENT COLUMN `parent_span_id` 'Hex-encoded parent span id. Empty for root spans.',
  COMMENT COLUMN `span_id` 'Hex-encoded span id (16 chars).',
  COMMENT COLUMN `trace_id` 'Hex-encoded W3C trace id (32 chars).',
  COMMENT COLUMN `source` 'Canonicalized producer surface derived from resource service.name at write time (e.g. claude-code, litellm). unknown when the resource carries no service.name.',
  COMMENT COLUMN `duration_nano` 'Span duration in nanoseconds (end time minus start time).',
  COMMENT COLUMN `timestamp` 'Human-readable timestamp derived from time_unix_nano.',
  COMMENT COLUMN `time_unix_nano` 'Span start time as Unix time (ns). Validated non-zero at the ingest edge.',
  COMMENT COLUMN `project_id` 'Project the span was ingested under, from the provenance stamped at the ingest edge.',
  COMMENT COLUMN `organization_id` 'Organization the span belongs to, from the provenance stamped at the ingest edge.';
ALTER TABLE `gram`.`otel_logs`
  COMMENT COLUMN `scope_attributes` 'Instrumentation scope attributes.',
  COMMENT COLUMN `scope_version` 'Instrumentation scope version. Empty when not reported.',
  COMMENT COLUMN `scope_name` 'Instrumentation scope name. The transform pipeline rewrites this to com.speakeasy.ai.logging and keeps the producer scope in log_attributes under speakeasy.original_instrumentation_scope.name.',
  COMMENT COLUMN `resource_schema_url` 'Schema URL of the resource. Empty when not reported.',
  COMMENT COLUMN `resource_attributes` 'Attributes of the resource that produced the record.',
  COMMENT COLUMN `flags` 'W3C trace flags for the emitting span context.',
  COMMENT COLUMN `log_attributes` 'Log record attributes, including Gram enrichments applied by the transform pipeline.',
  COMMENT COLUMN `body` 'Log body. String bodies are stored verbatim and structured bodies are JSON-encoded.',
  COMMENT COLUMN `severity_number` 'OTLP SeverityNumber enum value (1-24). 0 when unspecified.',
  COMMENT COLUMN `severity_text` 'Producer-supplied severity text (DEBUG, INFO, WARN, ERROR, FATAL). Empty when unclassified.',
  COMMENT COLUMN `event_name` 'Event name for records that represent a named event (OTLP 1.5+). Empty otherwise.',
  COMMENT COLUMN `span_id` 'Hex-encoded span id (16 chars). Empty when the record has no span context.',
  COMMENT COLUMN `trace_id` 'Hex-encoded W3C trace id (32 chars). Empty when the record has no span context.',
  COMMENT COLUMN `source` 'Canonicalized producer surface derived from resource service.name at write time (e.g. claude-code, litellm). unknown when the resource carries no service.name.',
  COMMENT COLUMN `timestamp` 'Human-readable timestamp derived from time_unix_nano.',
  COMMENT COLUMN `observed_time_unix_nano` 'Unix time (ns) when the event was observed by the collection system. 0 when the producer omitted it.',
  COMMENT COLUMN `time_unix_nano` 'Unix time (ns) when the event occurred. The writer substitutes observed_time_unix_nano when the producer sent 0 and drops records with neither, so this is never epoch zero.',
  COMMENT COLUMN `project_id` 'Project the record was ingested under, from the provenance stamped at the ingest edge.',
  COMMENT COLUMN `organization_id` 'Organization the record belongs to, from the provenance stamped at the ingest edge.';
ALTER TABLE `gram`.`organization_metadata_staging`
  COMMENT COLUMN `disabled_at` 'When the organization was disabled.',
  COMMENT COLUMN `updated_at` 'When the organization metadata was last updated in Gram.',
  COMMENT COLUMN `created_at` 'When the organization was created in Gram.',
  COMMENT COLUMN `trial_updated_at` 'When the enterprise trial lifecycle was last updated.',
  COMMENT COLUMN `trial_created_at` 'When the enterprise trial lifecycle was created.',
  COMMENT COLUMN `trial_demoted_at` 'When the enterprise trial was demoted.',
  COMMENT COLUMN `trial_converted_at` 'When the enterprise trial converted.',
  COMMENT COLUMN `trial_ends_at` 'Current enterprise trial end time.',
  COMMENT COLUMN `trial_tier` 'Enterprise trial tier from the trials lifecycle table.',
  COMMENT COLUMN `free_trial_ends_at` 'End of the organization metadata free-trial window.',
  COMMENT COLUMN `free_trial_started_at` 'Start of the organization metadata free-trial window.',
  COMMENT COLUMN `whitelisted` 'Whether the organization is allowed to use Gram.',
  COMMENT COLUMN `sso_enabled` 'Whether SSO is enabled. Null means not recorded.',
  COMMENT COLUMN `scim_enabled` 'Whether SCIM directory sync is enabled. Null means not recorded.',
  COMMENT COLUMN `webhooks_enabled` 'Whether outbound organization webhooks are enabled. Null means not recorded.',
  COMMENT COLUMN `workos_updated_at` 'Timestamp of the latest applied WorkOS organization update.',
  COMMENT COLUMN `workos_id` 'WorkOS organization identifier used for cross-system reporting.',
  COMMENT COLUMN `account_type` 'Gram account type, sourced from Postgres gram_account_type.',
  COMMENT COLUMN `slug` 'Current Gram organization slug.',
  COMMENT COLUMN `id` 'Gram organization identifier.';
ALTER TABLE `gram`.`organization_metadata`
  COMMENT COLUMN `disabled_at` 'When the organization was disabled.',
  COMMENT COLUMN `updated_at` 'When the organization metadata was last updated in Gram.',
  COMMENT COLUMN `created_at` 'When the organization was created in Gram.',
  COMMENT COLUMN `trial_updated_at` 'When the enterprise trial lifecycle was last updated.',
  COMMENT COLUMN `trial_created_at` 'When the enterprise trial lifecycle was created.',
  COMMENT COLUMN `trial_demoted_at` 'When the enterprise trial was demoted.',
  COMMENT COLUMN `trial_converted_at` 'When the enterprise trial converted.',
  COMMENT COLUMN `trial_ends_at` 'Current enterprise trial end time.',
  COMMENT COLUMN `trial_tier` 'Enterprise trial tier from the trials lifecycle table.',
  COMMENT COLUMN `free_trial_ends_at` 'End of the organization metadata free-trial window.',
  COMMENT COLUMN `free_trial_started_at` 'Start of the organization metadata free-trial window.',
  COMMENT COLUMN `whitelisted` 'Whether the organization is allowed to use Gram.',
  COMMENT COLUMN `sso_enabled` 'Whether SSO is enabled. Null means not recorded.',
  COMMENT COLUMN `scim_enabled` 'Whether SCIM directory sync is enabled. Null means not recorded.',
  COMMENT COLUMN `webhooks_enabled` 'Whether outbound organization webhooks are enabled. Null means not recorded.',
  COMMENT COLUMN `workos_updated_at` 'Timestamp of the latest applied WorkOS organization update.',
  COMMENT COLUMN `workos_id` 'WorkOS organization identifier used for cross-system reporting.',
  COMMENT COLUMN `account_type` 'Gram account type, sourced from Postgres gram_account_type.',
  COMMENT COLUMN `slug` 'Current Gram organization slug.',
  COMMENT COLUMN `id` 'Gram organization identifier.';
ALTER TABLE `gram`.`metrics_summaries`
  MODIFY COLUMN `total_cost` REMOVE COMMENT,
  MODIFY COLUMN `cache_creation_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `cache_read_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `avg_resolution_time_ms` REMOVE COMMENT,
  MODIFY COLUMN `failed_chats` REMOVE COMMENT,
  MODIFY COLUMN `resolved_chats` REMOVE COMMENT,
  MODIFY COLUMN `evaluated_chats` REMOVE COMMENT,
  MODIFY COLUMN `tool_failure_counts` REMOVE COMMENT,
  MODIFY COLUMN `tool_success_counts` REMOVE COMMENT,
  MODIFY COLUMN `tool_counts` REMOVE COMMENT,
  MODIFY COLUMN `models` REMOVE COMMENT,
  MODIFY COLUMN `avg_chat_resolution_score` REMOVE COMMENT,
  MODIFY COLUMN `chat_resolution_abandoned` REMOVE COMMENT,
  MODIFY COLUMN `chat_resolution_partial` REMOVE COMMENT,
  MODIFY COLUMN `chat_resolution_failure` REMOVE COMMENT,
  MODIFY COLUMN `chat_resolution_success` REMOVE COMMENT,
  MODIFY COLUMN `avg_tool_duration_ms` REMOVE COMMENT,
  MODIFY COLUMN `tool_call_failure` REMOVE COMMENT,
  MODIFY COLUMN `tool_call_success` REMOVE COMMENT,
  MODIFY COLUMN `total_tool_calls` REMOVE COMMENT,
  MODIFY COLUMN `finish_reason_tool_calls` REMOVE COMMENT,
  MODIFY COLUMN `finish_reason_stop` REMOVE COMMENT,
  MODIFY COLUMN `avg_chat_duration_ms` REMOVE COMMENT,
  MODIFY COLUMN `total_chat_requests` REMOVE COMMENT,
  MODIFY COLUMN `avg_tokens_per_request` REMOVE COMMENT,
  MODIFY COLUMN `total_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_output_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `distinct_providers` REMOVE COMMENT,
  MODIFY COLUMN `distinct_models` REMOVE COMMENT,
  MODIFY COLUMN `total_chats` REMOVE COMMENT,
  MODIFY COLUMN `last_seen_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `first_seen_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `time_bucket` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`mcp_network_traffic_hourly_summaries`
  MODIFY COLUMN `last_seen` REMOVE COMMENT,
  MODIFY COLUMN `request_count` REMOVE COMMENT,
  COMMENT COLUMN `surface` 'Network surface: public or private.',
  COMMENT COLUMN `server_id` 'ID of the MCP server or meta MCP server.',
  COMMENT COLUMN `server_kind` 'MCP server kind: mcp or meta.',
  COMMENT COLUMN `hour` 'UTC hour containing the observed request.',
  COMMENT COLUMN `gram_project_id` 'Project that received the inbound MCP request.';
ALTER TABLE `gram`.`identity_map_staging`
  COMMENT COLUMN `canonical_email` 'Normalized directory email of the owning user - the fold target for analytics.',
  COMMENT COLUMN `canonical_user_id` 'Directory user id the email resolves to.',
  COMMENT COLUMN `email_lower` 'Normalized (lowercased, trimmed) email observed in telemetry.',
  COMMENT COLUMN `org_id` 'Organization the identity belongs to.';
ALTER TABLE `gram`.`identity_map`
  COMMENT COLUMN `canonical_email` 'Normalized directory email of the owning user - the fold target for analytics.',
  COMMENT COLUMN `canonical_user_id` 'Directory user id the email resolves to.',
  COMMENT COLUMN `email_lower` 'Normalized (lowercased, trimmed) email observed in telemetry.',
  COMMENT COLUMN `org_id` 'Organization the identity belongs to.';
ALTER TABLE `gram`.`chat_token_summaries`
  MODIFY COLUMN `hook_source` REMOVE COMMENT,
  MODIFY COLUMN `stored_event_count` REMOVE COMMENT,
  MODIFY COLUMN `total_tokens` REMOVE COMMENT,
  MODIFY COLUMN `time_bucket` REMOVE COMMENT,
  MODIFY COLUMN `chat_id` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`chat_session_summaries`
  MODIFY COLUMN `attribution_tuples` REMOVE COMMENT,
  MODIFY COLUMN `groups` REMOVE COMMENT,
  MODIFY COLUMN `roles` REMOVE COMMENT,
  MODIFY COLUMN `billing_modes` REMOVE COMMENT,
  MODIFY COLUMN `providers` REMOVE COMMENT,
  MODIFY COLUMN `account_types` REMOVE COMMENT,
  MODIFY COLUMN `hook_sources` REMOVE COMMENT,
  MODIFY COLUMN `models` REMOVE COMMENT,
  MODIFY COLUMN `hostnames` REMOVE COMMENT,
  MODIFY COLUMN `emails` REMOVE COMMENT,
  MODIFY COLUMN `cost_center_names` REMOVE COMMENT,
  MODIFY COLUMN `division_names` REMOVE COMMENT,
  MODIFY COLUMN `employee_types` REMOVE COMMENT,
  MODIFY COLUMN `job_titles` REMOVE COMMENT,
  MODIFY COLUMN `department_names` REMOVE COMMENT,
  MODIFY COLUMN `total_cost` REMOVE COMMENT,
  MODIFY COLUMN `cache_creation_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `cache_read_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_output_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `failed_tool_call_count` REMOVE COMMENT,
  MODIFY COLUMN `tool_call_count` REMOVE COMMENT,
  MODIFY COLUMN `message_count` REMOVE COMMENT,
  MODIFY COLUMN `end_time_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `start_time_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `session_model` REMOVE COMMENT,
  MODIFY COLUMN `session_hook_source` REMOVE COMMENT,
  MODIFY COLUMN `session_user_email` REMOVE COMMENT,
  MODIFY COLUMN `chat_id` REMOVE COMMENT,
  MODIFY COLUMN `time_bucket` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`chat_analysis_scores`
  COMMENT COLUMN `judge_prompt_version` 'Judge prompt version.',
  COMMENT COLUMN `judge_model` 'Model used to judge the session.',
  COMMENT COLUMN `detail` 'Full structured verdict as JSON, shape defined per judge.',
  COMMENT COLUMN `score` 'Headline metric of the verdict, meaning defined per judge.',
  COMMENT COLUMN `judge` 'Name of the analysis judge that produced the score.',
  COMMENT COLUMN `chat_id` 'Gram chat identifier of the analyzed session.',
  COMMENT COLUMN `project_id` 'Project the score belongs to when known.',
  COMMENT COLUMN `organization_id` 'Organization the score belongs to.',
  COMMENT COLUMN `inserted_at` 'Time the score was inserted.',
  COMMENT COLUMN `created_at` 'Time the score was completed.',
  COMMENT COLUMN `id` 'Producer-supplied score identifier, the queue evaluation id.';
ALTER TABLE `gram`.`billing_meter_readings_by_time`
  COMMENT COLUMN `tokenizer_codec` 'Tokenizer codec promoted from attributes for billing analysis.',
  COMMENT COLUMN `attributes` 'Additional producer-supplied reading dimensions frozen at acceptance.',
  COMMENT COLUMN `reading_kind` 'Derived row kind based on whether the reading corrects an earlier reading.',
  COMMENT COLUMN `corrects_reading_id` 'Original reading corrected by this immutable adjustment.',
  COMMENT COLUMN `inserted_at` 'UTC time when ClickHouse received the row for delivery-lag diagnostics.',
  COMMENT COLUMN `produced_at` 'UTC time when the producer created the accepted reading.',
  COMMENT COLUMN `occurred_at` 'Usage-effective UTC time when the metered work executed and the timestamp used for billing periods.',
  COMMENT COLUMN `value` 'Signed workload value where usage is positive and adjustments may be positive or negative.',
  COMMENT COLUMN `measurement_method` 'Rating-critical measurement implementation.',
  COMMENT COLUMN `unit` 'Measurement unit.',
  COMMENT COLUMN `operation_id` 'Domain operation that produced the reading.',
  COMMENT COLUMN `meter_id` 'Registered workload meter identifier.',
  COMMENT COLUMN `project_id` 'Project that owns the workload.',
  COMMENT COLUMN `organization_id` 'Organization that owns the workload.',
  COMMENT COLUMN `id` 'Deterministic reading UUID stable across redelivery.';
ALTER TABLE `gram`.`billing_meter_readings`
  COMMENT COLUMN `measurement_method` 'Rating-critical measurement implementation.',
  COMMENT COLUMN `tokenizer_codec` 'Tokenizer codec promoted from attributes for billing analysis.',
  COMMENT COLUMN `attributes` 'Additional producer-supplied reading dimensions.',
  COMMENT COLUMN `reading_kind` 'Derived row kind based on whether the reading corrects an earlier reading.',
  COMMENT COLUMN `corrects_reading_id` 'Original reading corrected by this immutable adjustment.',
  COMMENT COLUMN `inserted_at` 'UTC time when ClickHouse received the row for delivery-lag diagnostics.',
  COMMENT COLUMN `produced_at` 'UTC time when the producer created this reading variant and the ReplacingMergeTree version.',
  COMMENT COLUMN `occurred_at` 'Usage-effective UTC time when the metered work executed and the timestamp used for billing periods.',
  COMMENT COLUMN `value` 'Signed workload value where usage is positive and adjustments may be positive or negative.',
  COMMENT COLUMN `unit` 'Measurement unit.',
  COMMENT COLUMN `operation_id` 'Domain operation that produced the reading.',
  COMMENT COLUMN `meter_id` 'Registered workload meter identifier.',
  COMMENT COLUMN `project_id` 'Project that owns the workload.',
  COMMENT COLUMN `organization_id` 'Organization that owns the workload.',
  COMMENT COLUMN `id` 'Deterministic reading UUID stable across redelivery.';
ALTER TABLE `gram`.`billing_meter_daily_summaries`
  MODIFY COLUMN `reading_count` REMOVE COMMENT,
  MODIFY COLUMN `quantity` REMOVE COMMENT,
  MODIFY COLUMN `measurement_method` REMOVE COMMENT,
  MODIFY COLUMN `unit` REMOVE COMMENT,
  MODIFY COLUMN `label` REMOVE COMMENT,
  MODIFY COLUMN `series_key` REMOVE COMMENT,
  MODIFY COLUMN `series_kind` REMOVE COMMENT,
  MODIFY COLUMN `day` REMOVE COMMENT,
  MODIFY COLUMN `facet` REMOVE COMMENT,
  MODIFY COLUMN `reading_kind` REMOVE COMMENT,
  MODIFY COLUMN `family` REMOVE COMMENT,
  MODIFY COLUMN `organization_id` REMOVE COMMENT;
ALTER TABLE `gram`.`authz_challenges`
  COMMENT COLUMN `filter_allowed_count` 'Number of resource IDs the Filter call returned as allowed.',
  COMMENT COLUMN `filter_candidate_count` 'Number of resource IDs the Filter call considered.',
  COMMENT COLUMN `evaluated_grant_count` 'Total grants the principal had loaded on context at decision time.',
  COMMENT COLUMN `matched_grants.matched_via_check_scope` 'Grants that satisfied at least one requested check. Empty on deny.',
  COMMENT COLUMN `matched_grants.selector` 'Grants that satisfied at least one requested check. Empty on deny.',
  COMMENT COLUMN `matched_grants.scope` 'Grants that satisfied at least one requested check. Empty on deny.',
  COMMENT COLUMN `matched_grants.principal_urn` 'Grants that satisfied at least one requested check. Empty on deny.',
  COMMENT COLUMN `requested_checks.selector` 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  COMMENT COLUMN `requested_checks.resource_id` 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  COMMENT COLUMN `requested_checks.resource_kind` 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  COMMENT COLUMN `requested_checks.scope` 'All checks requested in the call. length(requested_checks.scope) gives the count.',
  COMMENT COLUMN `expanded_scopes` 'Scope hierarchy expansion of the focus check.',
  COMMENT COLUMN `selector` 'JSON selector of the focus check.',
  COMMENT COLUMN `resource_id` 'Resource ID of the focus check.',
  COMMENT COLUMN `resource_kind` 'Resource kind of the focus check.',
  COMMENT COLUMN `scope` 'Scope of the focus check.',
  COMMENT COLUMN `reason` 'Reason: grant_matched | no_grants | scope_unsatisfied | invalid_check | rbac_skipped_apikey | dev_override.',
  COMMENT COLUMN `outcome` 'Decision outcome: allow | deny | error.',
  COMMENT COLUMN `operation` 'Authz operation: require | require_any | filter.',
  COMMENT COLUMN `role_slugs` 'Role principal URNs whose grants were loaded for this principal.',
  COMMENT COLUMN `session_id` 'Session ID for session-authed principals.',
  COMMENT COLUMN `api_key_id` 'API key ID for api_key principals.',
  COMMENT COLUMN `user_email` 'AuthContext.Email when present (session auth path).',
  COMMENT COLUMN `user_external_id` 'Customer-supplied external user identifier.',
  COMMENT COLUMN `user_id` 'AuthContext.UserID at decision time.',
  COMMENT COLUMN `principal_type` 'Principal kind: user | api_key | assistant.',
  COMMENT COLUMN `principal_urn` 'Primary principal URN (e.g. user:<uuid> or api_key:<id>).',
  COMMENT COLUMN `request_id` 'Internal request ID from RequestContext (when set).',
  COMMENT COLUMN `span_id` 'W3C span ID for the specific operation that triggered the challenge.',
  COMMENT COLUMN `trace_id` 'W3C trace ID linking the challenge to the originating request.',
  COMMENT COLUMN `project_id` 'Project the check was scoped to. Empty string when the check is org-level (kept non-nullable so it can sit in the primary key).',
  COMMENT COLUMN `organization_id` 'Organization the principal was acting in.',
  COMMENT COLUMN `timestamp` 'Time the authz decision was made.',
  COMMENT COLUMN `id` 'Unique identifier for the challenge entry.';
ALTER TABLE `gram`.`authz_challenge_bucket_summaries`
  MODIFY COLUMN `last_seen` REMOVE COMMENT,
  MODIFY COLUMN `first_seen` REMOVE COMMENT,
  MODIFY COLUMN `challenge_ids` REMOVE COMMENT,
  MODIFY COLUMN `matched_grant_count` REMOVE COMMENT,
  MODIFY COLUMN `evaluated_grant_count` REMOVE COMMENT,
  MODIFY COLUMN `role_slugs` REMOVE COMMENT,
  MODIFY COLUMN `reason` REMOVE COMMENT,
  MODIFY COLUMN `operation` REMOVE COMMENT,
  MODIFY COLUMN `user_email` REMOVE COMMENT,
  MODIFY COLUMN `user_id` REMOVE COMMENT,
  MODIFY COLUMN `principal_type` REMOVE COMMENT,
  MODIFY COLUMN `representative_id` REMOVE COMMENT,
  COMMENT COLUMN `resource_id` 'Resource ID of the focus check.',
  COMMENT COLUMN `resource_kind` 'Resource kind of the focus check.',
  COMMENT COLUMN `user_id_filter` 'User ID used to suppress principals outside the organization.',
  COMMENT COLUMN `principal_urn` 'Primary principal URN.',
  COMMENT COLUMN `scope` 'Scope of the focus check.',
  COMMENT COLUMN `outcome` 'Decision outcome.',
  COMMENT COLUMN `project_id` 'Project the check was scoped to.',
  COMMENT COLUMN `organization_id` 'Organization the principal was acting in.',
  COMMENT COLUMN `challenge_date` 'UTC date of the summarized challenge rows.';
ALTER TABLE `gram`.`attribute_metrics_summaries`
  MODIFY COLUMN `scored_tokens` REMOVE COMMENT,
  MODIFY COLUMN `scored_cost` REMOVE COMMENT,
  MODIFY COLUMN `total_work_units` REMOVE COMMENT,
  MODIFY COLUMN `hook_hostname` REMOVE COMMENT,
  MODIFY COLUMN `generation` REMOVE COMMENT,
  MODIFY COLUMN `is_active` REMOVE COMMENT,
  MODIFY COLUMN `mcp_tool_name` REMOVE COMMENT,
  MODIFY COLUMN `mcp_server_name` REMOVE COMMENT,
  MODIFY COLUMN `agent_name` REMOVE COMMENT,
  MODIFY COLUMN `skill_name` REMOVE COMMENT,
  MODIFY COLUMN `query_source` REMOVE COMMENT,
  MODIFY COLUMN `billing_mode` REMOVE COMMENT,
  MODIFY COLUMN `provider` REMOVE COMMENT,
  MODIFY COLUMN `account_type` REMOVE COMMENT,
  MODIFY COLUMN `unique_tool_calls` REMOVE COMMENT,
  MODIFY COLUMN `total_tool_calls` REMOVE COMMENT,
  MODIFY COLUMN `total_cost` REMOVE COMMENT,
  MODIFY COLUMN `cache_creation_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `cache_read_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_output_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_input_tokens` REMOVE COMMENT,
  MODIFY COLUMN `total_chats` REMOVE COMMENT,
  MODIFY COLUMN `groups` REMOVE COMMENT,
  MODIFY COLUMN `roles` REMOVE COMMENT,
  MODIFY COLUMN `hook_source` REMOVE COMMENT,
  MODIFY COLUMN `model` REMOVE COMMENT,
  MODIFY COLUMN `user_email` REMOVE COMMENT,
  MODIFY COLUMN `cost_center_name` REMOVE COMMENT,
  MODIFY COLUMN `division_name` REMOVE COMMENT,
  MODIFY COLUMN `employee_type` REMOVE COMMENT,
  MODIFY COLUMN `job_title` REMOVE COMMENT,
  MODIFY COLUMN `department_name` REMOVE COMMENT,
  MODIFY COLUMN `time_bucket` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`attribute_keys`
  MODIFY COLUMN `last_seen_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `first_seen_unix_nano` REMOVE COMMENT,
  MODIFY COLUMN `attribute_key` REMOVE COMMENT,
  MODIFY COLUMN `gram_project_id` REMOVE COMMENT;
ALTER TABLE `gram`.`ai_scan_receipts`
  COMMENT COLUMN `received_at` 'When the server received the report.',
  COMMENT COLUMN `match_count` 'Number of matches reported by the agent. Zero-match scans still post a receipt so coverage is provable.',
  COMMENT COLUMN `target_list_version` 'Version of the target list compiled into the agent binary that ran the scan, echoed as reported.',
  COMMENT COLUMN `scan_completed_at` 'When the agent completed the scan, as reported.',
  COMMENT COLUMN `scan_started_at` 'When the agent started the scan, as reported.',
  COMMENT COLUMN `user_email` 'Normalized email of the enrolled user the scan is attributed to.',
  COMMENT COLUMN `device_serial` 'Normalized hardware serial of the reporting device. Empty when the agent cannot read one.',
  COMMENT COLUMN `organization_id` 'Organization the reporting device agent is enrolled in.';
ALTER TABLE `gram`.`ai_detections`
  COMMENT COLUMN `updated_at` 'Replacing-merge version column. The newest row per key wins.',
  COMMENT COLUMN `last_seen` 'When this signal was most recently reported.',
  COMMENT COLUMN `first_seen` 'When this signal was first reported for this org, target, device, user. Preserved across upserts via read-merge-write.',
  COMMENT COLUMN `version` 'Installed version when the scan could extract one statically. Empty otherwise.',
  COMMENT COLUMN `category` 'Detection category validated by application code. Currently harness or local_model. Known targets use the server catalog, while unknown ids keep a supported reported category.',
  COMMENT COLUMN `signal` 'Scan observation value validated by application code. Currently installed or running.',
  COMMENT COLUMN `user_email` 'Normalized email of the enrolled user the scan is attributed to.',
  COMMENT COLUMN `device_serial` 'Normalized hardware serial of the reporting device. Empty when the agent cannot read one.',
  COMMENT COLUMN `target_id` 'Id of the detected AI tool as reported by the agent. Usually a server/internal/agent/aitargets catalog id, but stored as-is: agent binaries can ship newer target lists than the catalog knows.',
  COMMENT COLUMN `organization_id` 'Organization the reporting device agent is enrolled in.';
ALTER TABLE `gram`.`agent_metrics`
  COMMENT COLUMN `scope_attributes` 'Instrumentation scope attributes.',
  COMMENT COLUMN `resource_attributes` 'Attributes of the resource that produced the data point.',
  COMMENT COLUMN `attributes` 'Data point attributes verbatim, including Gram enrichments.',
  COMMENT COLUMN `groups` 'Directory groups of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `roles` 'Directory roles of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `cost_center_name` 'Directory cost center of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `employee_type` 'Directory employee type of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `job_title` 'Directory job title of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `division_name` 'Directory division of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `department_name` 'Directory department of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `device_id` 'Device the activity came from, when the device agent reported one. Empty otherwise.',
  COMMENT COLUMN `external_org_id` 'Organization id in the provider own account system. Empty when not resolved.',
  COMMENT COLUMN `billing_mode` 'Resolved billing mode. Empty until attribution runs in this pipeline.',
  COMMENT COLUMN `account_type` 'Resolved account type. Empty until attribution runs in this pipeline.',
  COMMENT COLUMN `surface` 'Agent surface the activity happened on. Empty when not stated.',
  COMMENT COLUMN `provider` 'Model provider the measurement concerns. Empty when not stated.',
  COMMENT COLUMN `source` 'Canonicalized producer surface derived from resource service.name at write time. Empty when not stated.',
  COMMENT COLUMN `mcp_tool_name` 'MCP tool involved, when stated. Empty otherwise.',
  COMMENT COLUMN `mcp_server_name` 'MCP server involved, when stated. Empty otherwise.',
  COMMENT COLUMN `agent_name` 'Sub-agent name, when stated. Empty otherwise.',
  COMMENT COLUMN `skill_name` 'Skill invoked, when stated. Empty otherwise.',
  COMMENT COLUMN `query_source` 'Where the request originated inside the agent. Empty when not stated.',
  COMMENT COLUMN `model` 'Model the measurement concerns. Empty when not stated.',
  COMMENT COLUMN `external_user_id` 'User id in the provider own account system. Empty when not stated.',
  COMMENT COLUMN `user_email` 'Producer-stated user email. Empty when not stated.',
  COMMENT COLUMN `user_id` 'Producer-stated user id. Empty when not stated.',
  COMMENT COLUMN `turn_id` 'Turn within the session, when the producer states one.',
  COMMENT COLUMN `session_id` 'Agent session the data point is attributable to. Empty for feeds that report without one.',
  COMMENT COLUMN `unit` 'Unit as declared by the producer. Empty when not declared.',
  COMMENT COLUMN `value` 'The measured value. One column rather than an int/double pair because Float64 is exact to 2^53 and the OTel spec says the numeric representation is not identifying.',
  COMMENT COLUMN `canonical_metric` 'The dialect canonical name for the measure. Discriminating point attributes fold in here, so claude_code.token.usage with type=input becomes its own canonical metric.',
  COMMENT COLUMN `metric_name` 'The producer own metric name, verbatim.',
  COMMENT COLUMN `metric_id` 'Content-derived fingerprint over the OTel identifying set (resource attributes, scope, metric name, unit, data point type, temporality, monotonicity, point attributes) plus the point timestamps. Value is excluded on purpose so a replay reproduces the same fingerprint.',
  COMMENT COLUMN `is_monotonic` '1 when the producer declares the series monotonic, else 0.',
  COMMENT COLUMN `temporality` 'OTLP aggregation temporality: delta | cumulative | unspecified. Without it a reader cannot know whether sum() over a set of rows is valid.',
  COMMENT COLUMN `grain` 'Producer native reporting grain: turn | session | minute | hour | day | point. Gates rollup eligibility.',
  COMMENT COLUMN `window_end_unix_nano` 'End of the interval the data point covers, as Unix time (ns). Equals occurred_at_unix_nano for point observations.',
  COMMENT COLUMN `window_start_unix_nano` 'Start of the interval the data point covers, as Unix time (ns). Equals occurred_at_unix_nano for point observations.',
  COMMENT COLUMN `observed_at_unix_nano` 'Unix time (ns) when the data point reached the ingest edge. The ReplacingMergeTree version column.',
  COMMENT COLUMN `occurred_at_unix_nano` 'The data point own time as Unix time (ns). What every query window filters on.',
  COMMENT COLUMN `project_id` 'Project the data point was ingested under, from the provenance stamped at the ingest edge.',
  COMMENT COLUMN `organization_id` 'Organization the data point belongs to, from the provenance stamped at the ingest edge.';
ALTER TABLE `gram`.`agent_events`
  COMMENT COLUMN `scope_attributes` 'Instrumentation scope attributes.',
  COMMENT COLUMN `resource_attributes` 'Attributes of the resource that produced the record.',
  COMMENT COLUMN `attributes` 'Record attributes verbatim, including Gram enrichments. Anything not typed above survives here.',
  COMMENT COLUMN `cost_usd` 'Cost in USD stated on the record. 0 when not stated.',
  COMMENT COLUMN `cache_write_tokens` 'Cache write tokens stated on the record. 0 when not stated.',
  COMMENT COLUMN `cache_read_tokens` 'Cache read tokens stated on the record. 0 when not stated.',
  COMMENT COLUMN `output_tokens` 'Output tokens stated on the record. 0 when not stated.',
  COMMENT COLUMN `input_tokens` 'Input tokens stated on the record. 0 when not stated.',
  COMMENT COLUMN `output_content` 'Normalized output message JSON. Empty when the record carries none.',
  COMMENT COLUMN `input_content` 'Normalized input message JSON. Empty when the record carries none.',
  COMMENT COLUMN `duration_nano` 'Duration in nanoseconds when the producer states one (span duration, tool call duration). 0 when not stated.',
  COMMENT COLUMN `outcome_message` 'Producer-stated message accompanying an error outcome. Empty otherwise.',
  COMMENT COLUMN `outcome` 'Agent-vocabulary outcome: ok | error | rejected (a tool call the user or a policy refused to run) | refused (a model declining to answer) | empty when not stated. Not a protocol status code.',
  COMMENT COLUMN `text` 'The record in words. Empty where the producer put everything in attributes, in which case raw_event_name is the readable headline.',
  COMMENT COLUMN `tool_name` 'Tool the record concerns, when the record says so. Empty otherwise.',
  COMMENT COLUMN `mcp_tool_name` 'MCP tool involved, when the record says so. Empty otherwise.',
  COMMENT COLUMN `mcp_server_name` 'MCP server involved, when the record says so. Empty otherwise.',
  COMMENT COLUMN `agent_name` 'Sub-agent name, when the record says so. Empty otherwise.',
  COMMENT COLUMN `skill_name` 'Skill invoked, when the record says so. Empty otherwise.',
  COMMENT COLUMN `query_source` 'Where the request originated inside the agent (e.g. user_prompt, tool_result). Empty when not stated.',
  COMMENT COLUMN `model` 'Model named by the record. Empty when not stated.',
  COMMENT COLUMN `groups` 'Directory groups of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `roles` 'Directory roles of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `cost_center_name` 'Directory cost center of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `employee_type` 'Directory employee type of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `job_title` 'Directory job title of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `division_name` 'Directory division of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `department_name` 'Directory department of the user at ingest time. Empty when not enriched.',
  COMMENT COLUMN `device_id` 'Device the activity came from, when the device agent reported one. Empty otherwise.',
  COMMENT COLUMN `external_org_id` 'Organization id in the provider own account system. Empty when not resolved.',
  COMMENT COLUMN `billing_mode` 'Resolved billing mode. Empty until attribution runs in this pipeline.',
  COMMENT COLUMN `account_type` 'Resolved account type. Empty until attribution runs in this pipeline.',
  COMMENT COLUMN `external_user_id` 'User id in the provider own account system. Empty when not stated.',
  COMMENT COLUMN `user_email` 'Producer-stated user email. Empty when not stated.',
  COMMENT COLUMN `user_id` 'Producer-stated user id. Empty when not stated.',
  COMMENT COLUMN `surface` 'Agent surface the activity happened on (e.g. claude-code, codex, cursor). Empty when not stated.',
  COMMENT COLUMN `provider` 'Model provider the record concerns (e.g. anthropic, openai). Empty when not stated.',
  COMMENT COLUMN `source` 'Canonicalized producer surface derived from resource service.name at write time (e.g. claude-code, litellm). Empty when not stated.',
  COMMENT COLUMN `raw_event_name` 'The producer own name for the event. For a span-derived row this is the span name. Kept so an unclassified record stays reclassifiable.',
  COMMENT COLUMN `event_type` 'Canonical event type assigned by the dialect. Says which kind of thing event_id names. Empty for records no dialect classified.',
  COMMENT COLUMN `event_id` 'Natural identity of the subject (the message, the tool call), shared across observations of it by design. A minted id when the producer states none.',
  COMMENT COLUMN `turn_id` 'Turn within the session, when the producer states one. Populated unevenly across producers.',
  COMMENT COLUMN `session_id` 'Agent session the record belongs to, as extracted by the dialect. Rows sharing a session_id are the same session by definition. Empty when the producer states none.',
  COMMENT COLUMN `record_id` 'One delivery key, resolved at ingest: the publisher record id for log-derived records, the span identity for span-derived ones. Readers de-duplicate on this and never branch on how a record arrived.',
  COMMENT COLUMN `observed_at_unix_nano` 'Unix time (ns) when the record reached the ingest edge. Orders competing observations of the same fact.',
  COMMENT COLUMN `occurred_at_unix_nano` 'Producer event time as Unix time (ns). What every query window filters on.',
  COMMENT COLUMN `project_id` 'Project the record was ingested under, from the provenance stamped at the ingest edge.',
  COMMENT COLUMN `organization_id` 'Organization the record belongs to, from the provenance stamped at the ingest edge.';
