ALTER TABLE `gram`.`billing_meter_readings_by_time`
  ADD COLUMN `assistant_id` String MATERIALIZED attributes['assistant_id'] COMMENT 'Frozen reporting attribute for assistant identity.' AFTER `tokenizer_codec`,
  ADD COLUMN `billing_mode` LowCardinality(String) MATERIALIZED attributes['billing_mode'] COMMENT 'Frozen reporting attribute for billing mode.' AFTER `assistant_id`,
  ADD COLUMN `billing_user_cost_center_name` LowCardinality(String) MATERIALIZED attributes['billing_user_cost_center_name'] COMMENT 'Frozen reporting attribute for billing-user cost center.' AFTER `billing_mode`,
  ADD COLUMN `billing_user_department_name` LowCardinality(String) MATERIALIZED attributes['billing_user_department_name'] COMMENT 'Frozen reporting attribute for billing-user department.' AFTER `billing_user_cost_center_name`,
  ADD COLUMN `billing_user_directory_groups` LowCardinality(String) MATERIALIZED attributes['billing_user_directory_groups'] COMMENT 'Frozen JSON directory-group set for reporting.' AFTER `billing_user_department_name`,
  ADD COLUMN `billing_user_division_name` LowCardinality(String) MATERIALIZED attributes['billing_user_division_name'] COMMENT 'Frozen reporting attribute for billing-user division.' AFTER `billing_user_directory_groups`,
  ADD COLUMN `billing_user_employee_type` LowCardinality(String) MATERIALIZED attributes['billing_user_employee_type'] COMMENT 'Frozen reporting attribute for billing-user employee type.' AFTER `billing_user_division_name`,
  ADD COLUMN `billing_user_id` String MATERIALIZED attributes['billing_user_id'] COMMENT 'Frozen reporting identity of the billing user.' AFTER `billing_user_employee_type`,
  ADD COLUMN `billing_user_job_title` LowCardinality(String) MATERIALIZED attributes['billing_user_job_title'] COMMENT 'Frozen reporting attribute for billing-user job title.' AFTER `billing_user_id`,
  ADD COLUMN `mcp_server_id` String MATERIALIZED attributes['mcp_server_id'] COMMENT 'Frozen reporting identity of the MCP server.' AFTER `billing_user_job_title`,
  ADD COLUMN `mcp_server_slug` String MATERIALIZED attributes['mcp_server_slug'] COMMENT 'Frozen reporting label for the MCP server.' AFTER `mcp_server_id`,
  ADD COLUMN `mcp_server_type` LowCardinality(String) MATERIALIZED attributes['mcp_server_type'] COMMENT 'Frozen reporting namespace for the MCP server.' AFTER `mcp_server_slug`,
  ADD COLUMN `model` LowCardinality(String) MATERIALIZED attributes['model'] COMMENT 'Frozen reporting attribute for the model.' AFTER `mcp_server_type`,
  ADD COLUMN `provider` LowCardinality(String) MATERIALIZED attributes['provider'] COMMENT 'Frozen reporting attribute for the provider.' AFTER `model`,
  ADD COLUMN `risk_policy_id` String MATERIALIZED attributes['risk_policy_id'] COMMENT 'Frozen reporting attribute for risk-policy identity.' AFTER `provider`,
  ADD COLUMN `tool_name` LowCardinality(String) MATERIALIZED attributes['tool_name'] COMMENT 'Frozen reporting attribute for tool name.';
