-- create "attribute_metrics_summaries_backfill" table
CREATE TABLE `attribute_metrics_summaries_backfill` (
  `gram_project_id` UUID,
  `time_bucket` DateTime('UTC'),
  `department_name` String,
  `job_title` String,
  `employee_type` String,
  `division_name` String,
  `cost_center_name` String,
  `user_email` String,
  `model` String,
  `hook_source` String,
  `roles` Array(String),
  `groups` Array(String),
  `total_chats` AggregateFunction(uniqExactIf, String, UInt8),
  `total_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_output_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `cache_read_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `cache_creation_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_cost` AggregateFunction(sumIf, Float64, UInt8),
  `total_tool_calls` AggregateFunction(countIf, UInt8),
  `unique_tool_calls` AggregateFunction(uniqExactIf, String, UInt8),
  `account_type` String,
  `provider` String,
  `billing_mode` String,
  `query_source` String,
  `skill_name` String,
  `agent_name` String,
  `mcp_server_name` String,
  `mcp_tool_name` String
) ENGINE = AggregatingMergeTree
PRIMARY KEY (`gram_project_id`, `time_bucket`, `department_name`, `job_title`, `employee_type`, `division_name`, `cost_center_name`, `user_email`, `model`, `hook_source`, `roles`, `groups`) ORDER BY (`gram_project_id`, `time_bucket`, `department_name`, `job_title`, `employee_type`, `division_name`, `cost_center_name`, `user_email`, `model`, `hook_source`, `roles`, `groups`, `account_type`, `provider`, `billing_mode`, `query_source`, `skill_name`, `agent_name`, `mcp_server_name`, `mcp_tool_name`) TTL time_bucket + toIntervalDay(730) SETTINGS index_granularity = 8192 COMMENT 'Staging target for tenant-scoped attribute_metrics_summaries backfills. Populated via telemetry_logs_backfill_feed, validated, then swapped into the live table.';
-- create "attribute_metrics_summaries_backfill_archive" table
CREATE TABLE `attribute_metrics_summaries_backfill_archive` (
  `backfill_run_id` String,
  `archived_at` DateTime('UTC') DEFAULT now('UTC'),
  `gram_project_id` UUID,
  `time_bucket` DateTime('UTC'),
  `department_name` String,
  `job_title` String,
  `employee_type` String,
  `division_name` String,
  `cost_center_name` String,
  `user_email` String,
  `model` String,
  `hook_source` String,
  `roles` Array(String),
  `groups` Array(String),
  `total_chats` AggregateFunction(uniqExactIf, String, UInt8),
  `total_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_output_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `cache_read_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `cache_creation_input_tokens` AggregateFunction(sumIf, Int64, UInt8),
  `total_cost` AggregateFunction(sumIf, Float64, UInt8),
  `total_tool_calls` AggregateFunction(countIf, UInt8),
  `unique_tool_calls` AggregateFunction(uniqExactIf, String, UInt8),
  `account_type` String,
  `provider` String,
  `billing_mode` String,
  `query_source` String,
  `skill_name` String,
  `agent_name` String,
  `mcp_server_name` String,
  `mcp_tool_name` String
) ENGINE = MergeTree
PRIMARY KEY (`backfill_run_id`, `gram_project_id`, `time_bucket`) ORDER BY (`backfill_run_id`, `gram_project_id`, `time_bucket`) TTL archived_at + toIntervalDay(90) SETTINGS index_granularity = 8192 COMMENT 'Pre-delete snapshots of attribute_metrics_summaries rows replaced by tenant backfills, keyed by Temporal workflow run id for post-commit rollback.';
-- create "telemetry_logs_backfill_feed" table
CREATE TABLE `telemetry_logs_backfill_feed` (
  `id` UUID DEFAULT generateUUIDv7(),
  `time_unix_nano` Int64,
  `observed_time_unix_nano` Int64,
  `observed_timestamp` DateTime64(9) DEFAULT fromUnixTimestamp64Nano(observed_time_unix_nano),
  `severity_text` LowCardinality(Nullable(String)),
  `body` String,
  `trace_id` Nullable(FixedString(32)),
  `span_id` Nullable(FixedString(16)),
  `attributes` JSON,
  `resource_attributes` JSON,
  `gram_project_id` UUID,
  `gram_deployment_id` Nullable(UUID),
  `gram_function_id` Nullable(UUID),
  `gram_urn` String,
  `service_name` LowCardinality(String),
  `service_version` Nullable(String),
  `gram_chat_id` Nullable(String),
  `project_id` String MATERIALIZED toString(attributes.gram.project.id),
  `deployment_id` String MATERIALIZED toString(resource_attributes.gram.deployment.id),
  `function_id` String MATERIALIZED toString(attributes.gram.function.id),
  `urn` String MATERIALIZED toString(attributes.gram.tool.urn),
  `chat_id` String MATERIALIZED toString(attributes.gen_ai.conversation.id),
  `user_id` String MATERIALIZED toString(attributes.user.id),
  `external_user_id` String MATERIALIZED toString(attributes.gram.external_user.id),
  `api_key_id` String MATERIALIZED toString(attributes.gram.api_key.id),
  `evaluation_score_label` String MATERIALIZED toString(attributes.gen_ai.evaluation.score.label),
  `tool_name` String MATERIALIZED toString(attributes.gram.tool.name),
  `tool_source` String MATERIALIZED toString(attributes.gram.tool_call.source),
  `event_source` String MATERIALIZED toString(attributes.gram.event.source),
  `toolset_slug` String MATERIALIZED toString(attributes.gram.toolset.slug),
  `user_email` String MATERIALIZED toString(attributes.user.email),
  `hook_source` String MATERIALIZED toString(attributes.gram.hook.source),
  `hook_block_reason` String MATERIALIZED toString(attributes.gram.hook.block_reason),
  `remote_mcp_server_id` String MATERIALIZED toString(attributes.gram.remote_mcp_server.id),
  `mcp_server_id` String MATERIALIZED toString(attributes.gram.mcp_server.id),
  `skill_name` String MATERIALIZED if(toString(attributes.gram.tool.name) = 'Skill', JSONExtractString(toString(attributes.gen_ai.tool.call.arguments), 'skill'), ''),
  `provider` String MATERIALIZED toString(attributes.gram.provider),
  `external_org_id` String MATERIALIZED toString(attributes.gram.external_org_id),
  `account_type` String MATERIALIZED toString(attributes.gram.account_type),
  `billing_mode` String MATERIALIZED toString(attributes.gram.billing_mode)
) ENGINE = `Null` COMMENT 'Null-engine replay feed for telemetry_logs backfills. Inserts store nothing and only flow through attached backfill materialized views.';
-- create "attribute_metrics_summaries_backfill_mv" view
CREATE MATERIALIZED VIEW `attribute_metrics_summaries_backfill_mv` TO `attribute_metrics_summaries_backfill` AS WITH gram_urn = 'claude-code:otel:logs' AS is_claude_otel_row, is_claude_otel_row AND (chat_id != '') AND (toString(attributes.prompt.id) != '') AND ((toString(attributes.event.name) = 'api_request') OR (body = 'claude_code.api_request')) AS is_claude_api_request, is_claude_otel_row AND ((toString(attributes.event.name) = 'tool_result') OR (body = 'claude_code.tool_result')) AS is_claude_tool_result, startsWith(gram_urn, 'codex:usage') OR startsWith(gram_urn, 'cursor:usage') AS is_agent_usage_row, (toString(attributes.gram.hook.source) IN ('codex', 'cursor')) AND (toString(attributes.gram.tool.name) != '') AND (toString(attributes.gram.tool.name) NOT IN ('claude-code', 'codex', 'cursor')) AND (toString(attributes.gram.hook.event) IN ('PostToolUse', 'PostToolUseFailure')) AS is_agent_tool_call, is_claude_tool_result OR is_agent_tool_call AS is_counted_tool_call, multiIf(toString(attributes.tool_use_id) != '', toString(attributes.tool_use_id), toString(attributes.gen_ai.tool.call.id) != '', toString(attributes.gen_ai.tool.call.id), toString(id)) AS tool_call_dedup_id SELECT gram_project_id, toStartOfHour(fromUnixTimestamp64Nano(time_unix_nano)) AS time_bucket, toString(attributes.user.attributes.department_name) AS department_name, toString(attributes.user.attributes.job_title) AS job_title, toString(attributes.user.attributes.employee_type) AS employee_type, toString(attributes.user.attributes.division_name) AS division_name, toString(attributes.user.attributes.cost_center_name) AS cost_center_name, user_email AS user_email, multiIf(is_claude_api_request AND (toString(attributes.model) != ''), toString(attributes.model), is_claude_api_request AND (toString(attributes.gen_ai.request.model) != ''), toString(attributes.gen_ai.request.model), toString(attributes.gen_ai.response.model)) AS model, hook_source, arraySort(JSONExtract(ifNull(toJSONString(attributes.user.roles), '[]'), 'Array(String)')) AS roles, arraySort(JSONExtract(ifNull(toJSONString(attributes.user.groups), '[]'), 'Array(String)')) AS groups, uniqExactIfState(toString(attributes.gen_ai.conversation.id), (toString(attributes.gen_ai.conversation.id) != '') AND (is_claude_api_request OR is_agent_usage_row)) AS total_chats, sumIfState(if(is_claude_api_request, toInt64OrZero(toString(attributes.input_tokens)), toInt64OrZero(toString(attributes.gen_ai.usage.input_tokens))), is_claude_api_request OR is_agent_usage_row) AS total_input_tokens, sumIfState(if(is_claude_api_request, toInt64OrZero(toString(attributes.output_tokens)), toInt64OrZero(toString(attributes.gen_ai.usage.output_tokens))), is_claude_api_request OR is_agent_usage_row) AS total_output_tokens, sumIfState(if(is_claude_api_request, ((toInt64OrZero(toString(attributes.input_tokens)) + toInt64OrZero(toString(attributes.output_tokens))) + toInt64OrZero(toString(attributes.cache_read_tokens))) + toInt64OrZero(toString(attributes.cache_creation_tokens)), toInt64OrZero(toString(attributes.gen_ai.usage.total_tokens))), is_claude_api_request OR is_agent_usage_row) AS total_tokens, sumIfState(if(is_claude_api_request, toInt64OrZero(toString(attributes.cache_read_tokens)), toInt64OrZero(toString(attributes.gen_ai.usage.cache_read.input_tokens))), is_claude_api_request OR is_agent_usage_row) AS cache_read_input_tokens, sumIfState(if(is_claude_api_request, toInt64OrZero(toString(attributes.cache_creation_tokens)), toInt64OrZero(toString(attributes.gen_ai.usage.cache_creation.input_tokens))), is_claude_api_request OR is_agent_usage_row) AS cache_creation_input_tokens, sumIfState(if(is_claude_api_request, multiIf(toString(attributes.cost_usd) != '', toFloat64OrZero(toString(attributes.cost_usd)), toString(attributes.cost_usd_micros) != '', toFloat64OrZero(toString(attributes.cost_usd_micros)) / 1000000, 0), toFloat64OrZero(toString(attributes.gen_ai.usage.cost))), is_claude_api_request OR is_agent_usage_row) AS total_cost, countIfState(is_counted_tool_call) AS total_tool_calls, uniqExactIfState(tool_call_dedup_id, is_counted_tool_call) AS unique_tool_calls, account_type, provider, billing_mode, if(is_claude_api_request, toString(attributes.query_source), '') AS query_source, if(is_claude_api_request, toString(attributes.skill.name), '') AS skill_name, if(is_claude_api_request, toString(attributes.agent.name), '') AS agent_name, if(is_claude_api_request, toString(attributes.mcp_server.name), '') AS mcp_server_name, if(is_claude_api_request, toString(attributes.mcp_tool.name), '') AS mcp_tool_name FROM telemetry_logs_backfill_feed WHERE is_claude_api_request OR is_claude_tool_result OR is_agent_usage_row OR is_agent_tool_call GROUP BY gram_project_id, time_bucket, department_name, job_title, employee_type, division_name, cost_center_name, user_email, model, hook_source, roles, groups, account_type, provider, billing_mode, query_source, skill_name, agent_name, mcp_server_name, mcp_tool_name;
