-- Add MCP client attribution columns before emission ships so no row misses them
ALTER TABLE `gram`.`telemetry_logs`
  ADD COLUMN `mcp_client_name` String MATERIALIZED toString(attributes.gram.mcp.client.name) COMMENT 'MCP client name self-reported at the initialize handshake or in the per-request _meta hint. Untrusted, attribution only. Empty for hook-observed and non-MCP traffic (materialized from attributes.gram.mcp.client.name).' AFTER `meta_mcp_server_id`,
  ADD COLUMN `mcp_client_version` String MATERIALIZED toString(attributes.gram.mcp.client.version) COMMENT 'MCP client version reported alongside mcp_client_name. Empty when the client reported a name but no version (materialized from attributes.gram.mcp.client.version).',
  ADD INDEX `idx_telemetry_logs_mat_mcp_client_name` ((mcp_client_name)) TYPE bloom_filter(0.01);
-- materialize index "idx_telemetry_logs_mat_mcp_client_name" for existing data
ALTER TABLE `gram`.`telemetry_logs` MATERIALIZE INDEX `idx_telemetry_logs_mat_mcp_client_name`;
ALTER TABLE `gram`.`trace_summaries`
  ADD COLUMN `mcp_client_name` SimpleAggregateFunction(max, String) AFTER `meta_mcp_server_id`,
  ADD COLUMN `mcp_client_version` SimpleAggregateFunction(max, String);
-- MODIFY QUERY swaps the view definition in place. Dropping and recreating
-- the view would stop feeding trace_summaries for the gap between the two
-- statements, losing every trace that arrived in it.
ALTER TABLE `gram`.`trace_summaries_mv` MODIFY QUERY SELECT trace_id, gram_project_id, any(gram_deployment_id) AS gram_deployment_id, any(gram_function_id) AS gram_function_id, any(gram_urn) AS gram_urn, max(tool_name) AS tool_name, any(tool_source) AS tool_source, any(event_source) AS event_source, any(user_email) AS user_email, any(hook_source) AS hook_source, any(skill_name) AS skill_name, anyIf(toolset_slug, toolset_slug != '') AS toolset_slug, anyIf(external_user_id, external_user_id != '') AS external_user_id, anyIf(user_id, user_id != '') AS user_id, max(if((telemetry_logs.event_source IN ('tool_call', 'resource_read', 'meta_discovery')) AND (toString(attributes.gram.authorization.actor.type) = 'agent'), toString(attributes.gram.authorization.actor.id), '')) AS agent_id, anyIf(toString(attributes.gram.mcp.match), toString(attributes.gram.mcp.match) != '') AS mcp_match, anyIf(toString(attributes.gram.mcp.server_url), toString(attributes.gram.mcp.server_url) != '') AS mcp_server_url, min(time_unix_nano) AS start_time_unix_nano, toUInt64(count(*)) AS log_count, anyIfState(toInt32OrNull(toString(attributes.http.response.status_code)), toString(attributes.http.response.status_code) != '') AS http_status_code, max(if(toString(attributes.gen_ai.tool.call.result) != '', 1, 0)) AS has_result, max(if(toString(attributes.gram.hook.error) != '', 1, 0)) AS has_error, max(if(toString(attributes.gram.hook.block_reason) != '', 1, 0)) AS has_block, anyIf(toString(attributes.gram.hook.block_reason), toString(attributes.gram.hook.block_reason) != '') AS block_reason, anyIf(account_type, account_type != '') AS account_type, anyIf(provider, provider != '') AS provider, anyIf(meta_mcp_server_id, meta_mcp_server_id != '') AS meta_mcp_server_id, anyIf(mcp_client_name, mcp_client_name != '') AS mcp_client_name, anyIf(mcp_client_version, mcp_client_version != '') AS mcp_client_version FROM gram.telemetry_logs WHERE (trace_id IS NOT NULL) AND (trace_id != '') AND (NOT startsWith(telemetry_logs.gram_urn, 'urn:uuid:')) GROUP BY trace_id, gram_project_id;
