// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stub.sql

package database

import (
	"context"
)

const stubQuery = `-- name: StubQuery :one
select 1
`

func (q *Queries) StubQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, stubQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
