/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AdminHooksRolloutChange,
  AdminHooksRolloutChange$inboundSchema,
} from "./adminhooksrolloutchange.js";
import {
  AdminHooksRolloutOverride,
  AdminHooksRolloutOverride$inboundSchema,
} from "./adminhooksrolloutoverride.js";
import {
  AdminHooksRolloutPin,
  AdminHooksRolloutPin$inboundSchema,
} from "./adminhooksrolloutpin.js";

/**
 * Platform-wide hooks version rollout state.
 */
export type AdminHooksRollout = {
  /**
   * Organizations that always receive current_version and ignore pins.
   */
  canaryOrganizationSlugs: Array<string>;
  /**
   * The hooks generator version this server build publishes to an organization once its pin reaches it.
   */
  currentVersion: number;
  /**
   * A hooks version rollout pin: the highest hooks generator version its scope is cleared to receive.
   */
  defaultPin?: AdminHooksRolloutPin | undefined;
  /**
   * Organizations with an override, by slug.
   */
  overrides: Array<AdminHooksRolloutOverride>;
  /**
   * The most recent pin changes, newest first.
   */
  recentChanges: Array<AdminHooksRolloutChange>;
};

/** @internal */
export const AdminHooksRollout$inboundSchema: z.ZodMiniType<
  AdminHooksRollout,
  unknown
> = z.pipe(
  z.object({
    canary_organization_slugs: z.array(z.string()),
    current_version: z.int(),
    default_pin: z.optional(AdminHooksRolloutPin$inboundSchema),
    overrides: z.array(AdminHooksRolloutOverride$inboundSchema),
    recent_changes: z.array(AdminHooksRolloutChange$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "canary_organization_slugs": "canaryOrganizationSlugs",
      "current_version": "currentVersion",
      "default_pin": "defaultPin",
      "recent_changes": "recentChanges",
    });
  }),
);

export function adminHooksRolloutFromJSON(
  jsonString: string,
): SafeParseResult<AdminHooksRollout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminHooksRollout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminHooksRollout' from JSON`,
  );
}
