/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Full project detail surfaced to admin operators, including aggregated counts of child resources.
 */
export type AdminProjectDetail = {
  /**
   * Number of active API keys in the project.
   */
  apiKeyCount: number;
  /**
   * Number of active assistants in the project.
   */
  assistantCount: number;
  createdAt: Date;
  /**
   * Total number of deployments in the project.
   */
  deploymentCount: number;
  /**
   * Number of active environments in the project.
   */
  environmentCount: number;
  /**
   * Functions runner version pin, if set.
   */
  functionsRunnerVersion?: string | undefined;
  /**
   * Number of active HTTP tool definitions in the project.
   */
  httpToolCount: number;
  /**
   * Project ID.
   */
  id: string;
  /**
   * Project logo asset ID, if set.
   */
  logoAssetId?: string | undefined;
  /**
   * Project name.
   */
  name: string;
  /**
   * Owning organization ID.
   */
  organizationId: string;
  /**
   * Project slug.
   */
  slug: string;
  /**
   * Number of active toolsets in the project.
   */
  toolsetCount: number;
  updatedAt: Date;
};

/** @internal */
export const AdminProjectDetail$inboundSchema: z.ZodMiniType<
  AdminProjectDetail,
  unknown
> = z.pipe(
  z.object({
    api_key_count: z.int(),
    assistant_count: z.int(),
    created_at: z.pipe(
      z.iso.datetime({ offset: true }),
      z.transform(v => new Date(v)),
    ),
    deployment_count: z.int(),
    environment_count: z.int(),
    functions_runner_version: z.optional(z.string()),
    http_tool_count: z.int(),
    id: z.string(),
    logo_asset_id: z.optional(z.string()),
    name: z.string(),
    organization_id: z.string(),
    slug: z.string(),
    toolset_count: z.int(),
    updated_at: z.pipe(
      z.iso.datetime({ offset: true }),
      z.transform(v => new Date(v)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key_count": "apiKeyCount",
      "assistant_count": "assistantCount",
      "created_at": "createdAt",
      "deployment_count": "deploymentCount",
      "environment_count": "environmentCount",
      "functions_runner_version": "functionsRunnerVersion",
      "http_tool_count": "httpToolCount",
      "logo_asset_id": "logoAssetId",
      "organization_id": "organizationId",
      "toolset_count": "toolsetCount",
      "updated_at": "updatedAt",
    });
  }),
);

export function adminProjectDetailFromJSON(
  jsonString: string,
): SafeParseResult<AdminProjectDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminProjectDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminProjectDetail' from JSON`,
  );
}
