/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Capability the cell reports on.
 */
export const Capability = {
  Session: "session",
  Blocking: "blocking",
  Identity: "identity",
  Cost: "cost",
  Shadow: "shadow",
} as const;
/**
 * Capability the cell reports on.
 */
export type Capability = ClosedEnum<typeof Capability>;

/**
 * Whether evidence was found, absent, not answerable yet, or impossible for this pair.
 */
export const SupportCoverageCellStatus = {
  Observed: "observed",
  None: "none",
  Pending: "pending",
  Na: "na",
} as const;
/**
 * Whether evidence was found, absent, not answerable yet, or impossible for this pair.
 */
export type SupportCoverageCellStatus = ClosedEnum<
  typeof SupportCoverageCellStatus
>;

/**
 * Surface the cell reports on: Gram's own MCP gateway, or a consuming agent surface.
 */
export const Surface = {
  McpGateway: "mcp_gateway",
  ClaudeCode: "claude_code",
  ClaudeChat: "claude_chat",
  Cowork: "cowork",
  Codex: "codex",
  Cursor: "cursor",
  Other: "other",
} as const;
/**
 * Surface the cell reports on: Gram's own MCP gateway, or a consuming agent surface.
 */
export type Surface = ClosedEnum<typeof Surface>;

/**
 * Observed evidence for one capability on one surface.
 */
export type SupportCoverageCell = {
  /**
   * Capability the cell reports on.
   */
  capability: Capability;
  /**
   * Short qualifier rendered under the value. Empty when there is nothing to qualify.
   */
  detail: string;
  /**
   * RFC3339 timestamp of the most recent supporting evidence. Absent unless observed.
   */
  lastSeen?: Date | undefined;
  /**
   * Whether evidence was found, absent, not answerable yet, or impossible for this pair.
   */
  status: SupportCoverageCellStatus;
  /**
   * Surface the cell reports on: Gram's own MCP gateway, or a consuming agent surface.
   */
  surface: Surface;
  /**
   * Singular noun the value counts, when the capability's own unit does not apply. The gateway is measured in tool calls where an agent surface is measured in sessions. Empty when the capability's default unit stands.
   */
  unit: string;
  /**
   * Primary measure: sessions, tokens, blocks, attributed sessions or distinct shadow servers depending on the capability. Zero unless observed.
   */
  value: number;
};

/** @internal */
export const Capability$inboundSchema: z.ZodMiniEnum<typeof Capability> = z
  .enum(Capability);

/** @internal */
export const SupportCoverageCellStatus$inboundSchema: z.ZodMiniEnum<
  typeof SupportCoverageCellStatus
> = z.enum(SupportCoverageCellStatus);

/** @internal */
export const Surface$inboundSchema: z.ZodMiniEnum<typeof Surface> = z.enum(
  Surface,
);

/** @internal */
export const SupportCoverageCell$inboundSchema: z.ZodMiniType<
  SupportCoverageCell,
  unknown
> = z.pipe(
  z.object({
    capability: Capability$inboundSchema,
    detail: z.string(),
    last_seen: z.optional(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    status: SupportCoverageCellStatus$inboundSchema,
    surface: Surface$inboundSchema,
    unit: z.string(),
    value: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "last_seen": "lastSeen",
    });
  }),
);

export function supportCoverageCellFromJSON(
  jsonString: string,
): SafeParseResult<SupportCoverageCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportCoverageCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportCoverageCell' from JSON`,
  );
}
