import type { IdpProvider } from "./types";

export const IDP_PROVIDERS: IdpProvider[] = [
  {
    id: "okta-saml",
    name: "Okta",
    providerType: "OktaSAML",
    iconSlug: "okta",
    protocol: "SAML 2.0",
  },
  {
    id: "azure-saml",
    name: "Entra ID (Azure AD)",
    providerType: "AzureSAML",
    iconSlug: "azure",
    protocol: "SAML 2.0",
  },
  {
    id: "google-saml",
    name: "Google Workspace",
    providerType: "GoogleSAML",
    iconSlug: "google",
    protocol: "SAML 2.0",
  },
  {
    id: "onelogin-saml",
    name: "OneLogin",
    providerType: "OneLoginSAML",
    iconSlug: "onelogin",
    protocol: "SAML 2.0",
  },
  {
    id: "jumpcloud-saml",
    name: "JumpCloud",
    providerType: "JumpCloudSAML",
    iconSlug: "jumpcloud",
    protocol: "SAML 2.0",
  },
  {
    id: "pingfederate-saml",
    name: "PingFederate",
    providerType: "PingFederateSAML",
    iconSlug: "ping-identity",
    protocol: "SAML 2.0",
  },
  {
    id: "cyberark-saml",
    name: "CyberArk",
    providerType: "CyberArkSAML",
    iconSlug: "cyberark",
    protocol: "SAML 2.0",
  },
  {
    id: "duo-saml",
    name: "Duo",
    providerType: "DuoSAML",
    iconSlug: "duo",
    protocol: "SAML 2.0",
  },
  {
    id: "keycloak-saml",
    name: "Keycloak",
    providerType: "KeycloakSAML",
    iconSlug: "keycloak",
    protocol: "SAML 2.0",
  },
  {
    id: "rippling-saml",
    name: "Rippling",
    providerType: "RipplingSAML",
    iconSlug: "rippling",
    protocol: "SAML 2.0",
  },
  {
    id: "salesforce-saml",
    name: "Salesforce",
    providerType: "SalesforceSAML",
    iconSlug: "salesforce",
    protocol: "SAML 2.0",
  },
  {
    id: "vmware-saml",
    name: "VMware",
    providerType: "VMwareSAML",
    iconSlug: "vmware",
    protocol: "SAML 2.0",
  },
  {
    id: "cloudflare-saml",
    name: "Cloudflare",
    providerType: "CloudflareSAML",
    iconSlug: "cloudflare",
    protocol: "SAML 2.0",
  },
  {
    id: "oracle-saml",
    name: "Oracle",
    providerType: "OracleSAML",
    iconSlug: "oracle",
    protocol: "SAML 2.0",
  },
  {
    id: "lastpass-saml",
    name: "LastPass",
    providerType: "LastPassSAML",
    iconSlug: "lastpass",
    protocol: "SAML 2.0",
  },
  {
    id: "miniorange-saml",
    name: "miniOrange",
    providerType: "MiniOrangeSAML",
    iconSlug: "miniorange",
    protocol: "SAML 2.0",
  },
  {
    id: "auth0-saml",
    name: "Auth0",
    providerType: "Auth0SAML",
    iconSlug: "auth0",
    protocol: "SAML 2.0",
  },
  {
    id: "cas-saml",
    name: "CAS",
    providerType: "CasSAML",
    iconSlug: "cas",
    protocol: "SAML 2.0",
  },
  {
    id: "netiq-saml",
    name: "NetIQ",
    providerType: "NetIqSAML",
    iconSlug: "net-iq",
    protocol: "SAML 2.0",
  },
  {
    id: "shibboleth-saml",
    name: "Shibboleth",
    providerType: "ShibbolethGenericSAML",
    iconSlug: "shibboleth",
    protocol: "SAML 2.0",
  },
  {
    id: "simplesamlphp-saml",
    name: "SimpleSAMLphp",
    providerType: "SimpleSamlPhpSAML",
    iconSlug: "simple-saml-php",
    protocol: "SAML 2.0",
  },
  {
    id: "generic-oidc",
    name: "Generic OIDC",
    providerType: "GenericOidc",
    iconSlug: "generic-oidc",
    protocol: "OIDC",
  },
];
