/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { CaptureEventPayload$outboundSchema } from "../components/captureeventpayload.js";
/** @internal */
export const CaptureEventSecurityOption1$outboundSchema = z.pipe(
  z.object({
    apikeyHeaderGramKey: z.string(),
    projectSlugHeaderGramProject: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      apikeyHeaderGramKey: "apikey_header_Gram-Key",
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
    });
  }),
);
export function captureEventSecurityOption1ToJSON(captureEventSecurityOption1) {
  return JSON.stringify(
    CaptureEventSecurityOption1$outboundSchema.parse(
      captureEventSecurityOption1,
    ),
  );
}
/** @internal */
export const CaptureEventSecurityOption2$outboundSchema = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.string(),
    sessionHeaderGramSession: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);
export function captureEventSecurityOption2ToJSON(captureEventSecurityOption2) {
  return JSON.stringify(
    CaptureEventSecurityOption2$outboundSchema.parse(
      captureEventSecurityOption2,
    ),
  );
}
/** @internal */
export const CaptureEventSecurityOption3$outboundSchema = z.pipe(
  z.object({
    chatSessionsTokenHeaderGramChatSession: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatSessionsTokenHeaderGramChatSession:
        "chat_sessions_token_header_Gram-Chat-Session",
    });
  }),
);
export function captureEventSecurityOption3ToJSON(captureEventSecurityOption3) {
  return JSON.stringify(
    CaptureEventSecurityOption3$outboundSchema.parse(
      captureEventSecurityOption3,
    ),
  );
}
/** @internal */
export const CaptureEventSecurity$outboundSchema = z.pipe(
  z.object({
    option1: z.optional(
      z.lazy(() => CaptureEventSecurityOption1$outboundSchema),
    ),
    option2: z.optional(
      z.lazy(() => CaptureEventSecurityOption2$outboundSchema),
    ),
    option3: z.optional(
      z.lazy(() => CaptureEventSecurityOption3$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      option1: "Option1",
      option2: "Option2",
      option3: "Option3",
    });
  }),
);
export function captureEventSecurityToJSON(captureEventSecurity) {
  return JSON.stringify(
    CaptureEventSecurity$outboundSchema.parse(captureEventSecurity),
  );
}
/** @internal */
export const CaptureEventRequest$outboundSchema = z.pipe(
  z.object({
    gramKey: z.optional(z.string()),
    gramSession: z.optional(z.string()),
    gramProject: z.optional(z.string()),
    gramChatSession: z.optional(z.string()),
    captureEventPayload: CaptureEventPayload$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      gramKey: "Gram-Key",
      gramSession: "Gram-Session",
      gramProject: "Gram-Project",
      gramChatSession: "Gram-Chat-Session",
      captureEventPayload: "CaptureEventPayload",
    });
  }),
);
export function captureEventRequestToJSON(captureEventRequest) {
  return JSON.stringify(
    CaptureEventRequest$outboundSchema.parse(captureEventRequest),
  );
}
//# sourceMappingURL=captureevent.js.map
