/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
/** @internal */
export const RemoveOAuthServerSecurityOption1$outboundSchema = z.pipe(
  z.object({
    projectSlugHeaderGramProject: z.string(),
    sessionHeaderGramSession: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
      sessionHeaderGramSession: "session_header_Gram-Session",
    });
  }),
);
export function removeOAuthServerSecurityOption1ToJSON(
  removeOAuthServerSecurityOption1,
) {
  return JSON.stringify(
    RemoveOAuthServerSecurityOption1$outboundSchema.parse(
      removeOAuthServerSecurityOption1,
    ),
  );
}
/** @internal */
export const RemoveOAuthServerSecurityOption2$outboundSchema = z.pipe(
  z.object({
    apikeyHeaderGramKey: z.string(),
    projectSlugHeaderGramProject: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      apikeyHeaderGramKey: "apikey_header_Gram-Key",
      projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
    });
  }),
);
export function removeOAuthServerSecurityOption2ToJSON(
  removeOAuthServerSecurityOption2,
) {
  return JSON.stringify(
    RemoveOAuthServerSecurityOption2$outboundSchema.parse(
      removeOAuthServerSecurityOption2,
    ),
  );
}
/** @internal */
export const RemoveOAuthServerSecurity$outboundSchema = z.pipe(
  z.object({
    option1: z.optional(
      z.lazy(() => RemoveOAuthServerSecurityOption1$outboundSchema),
    ),
    option2: z.optional(
      z.lazy(() => RemoveOAuthServerSecurityOption2$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      option1: "Option1",
      option2: "Option2",
    });
  }),
);
export function removeOAuthServerSecurityToJSON(removeOAuthServerSecurity) {
  return JSON.stringify(
    RemoveOAuthServerSecurity$outboundSchema.parse(removeOAuthServerSecurity),
  );
}
/** @internal */
export const RemoveOAuthServerRequest$outboundSchema = z.pipe(
  z.object({
    slug: z.string(),
    gramSession: z.optional(z.string()),
    gramKey: z.optional(z.string()),
    gramProject: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      gramSession: "Gram-Session",
      gramKey: "Gram-Key",
      gramProject: "Gram-Project",
    });
  }),
);
export function removeOAuthServerRequestToJSON(removeOAuthServerRequest) {
  return JSON.stringify(
    RemoveOAuthServerRequest$outboundSchema.parse(removeOAuthServerRequest),
  );
}
//# sourceMappingURL=removeoauthserver.js.map
