/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
/** @internal */
export const UploadFunctionsSecurityOption1$outboundSchema = z.pipe(z.object({
    apikeyHeaderGramKey: z.string(),
    projectSlugHeaderGramProject: z.string(),
}), z.transform((v) => {
    return remap$(v, {
        apikeyHeaderGramKey: "apikey_header_Gram-Key",
        projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
    });
}));
export function uploadFunctionsSecurityOption1ToJSON(uploadFunctionsSecurityOption1) {
    return JSON.stringify(UploadFunctionsSecurityOption1$outboundSchema.parse(uploadFunctionsSecurityOption1));
}
/** @internal */
export const UploadFunctionsSecurityOption2$outboundSchema = z.pipe(z.object({
    projectSlugHeaderGramProject: z.string(),
    sessionHeaderGramSession: z.string(),
}), z.transform((v) => {
    return remap$(v, {
        projectSlugHeaderGramProject: "project_slug_header_Gram-Project",
        sessionHeaderGramSession: "session_header_Gram-Session",
    });
}));
export function uploadFunctionsSecurityOption2ToJSON(uploadFunctionsSecurityOption2) {
    return JSON.stringify(UploadFunctionsSecurityOption2$outboundSchema.parse(uploadFunctionsSecurityOption2));
}
/** @internal */
export const UploadFunctionsSecurity$outboundSchema = z.pipe(z.object({
    option1: z.optional(z.lazy(() => UploadFunctionsSecurityOption1$outboundSchema)),
    option2: z.optional(z.lazy(() => UploadFunctionsSecurityOption2$outboundSchema)),
}), z.transform((v) => {
    return remap$(v, {
        option1: "Option1",
        option2: "Option2",
    });
}));
export function uploadFunctionsSecurityToJSON(uploadFunctionsSecurity) {
    return JSON.stringify(UploadFunctionsSecurity$outboundSchema.parse(uploadFunctionsSecurity));
}
/** @internal */
export const UploadFunctionsRequest$outboundSchema = z.pipe(z.object({
    contentLength: z.int(),
    gramKey: z.optional(z.string()),
    gramProject: z.optional(z.string()),
    gramSession: z.optional(z.string()),
    requestBody: z.union([
        z.custom(x => x instanceof ReadableStream),
        z.custom(x => x instanceof Blob),
        z.custom(x => x instanceof ArrayBuffer),
        z.custom(x => x instanceof Uint8Array),
    ]),
}), z.transform((v) => {
    return remap$(v, {
        contentLength: "Content-Length",
        gramKey: "Gram-Key",
        gramProject: "Gram-Project",
        gramSession: "Gram-Session",
        requestBody: "RequestBody",
    });
}));
export function uploadFunctionsRequestToJSON(uploadFunctionsRequest) {
    return JSON.stringify(UploadFunctionsRequest$outboundSchema.parse(uploadFunctionsRequest));
}
//# sourceMappingURL=uploadfunctions.js.map