name: Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  REGISTRY: gcr.io/linen-analyst-344721 #gcr for speakeasy-common gcr registry
  DOCKER_REPOSITORY_OWNER: ${{github.repository_owner}}
jobs:
  changes:
    name: Tag branch changes
    runs-on: ubicloud-standard-4
    permissions:
      contents: "read"
      pull-requests: read
    outputs:
      server: ${{ steps.gates.outputs.server }}
      client: ${{ steps.gates.outputs.client }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        name: Check for changed packages
        id: filter
        with:
          filters: .github/filters.yaml
      - id: gates
        name: Set outputs
        run: |
          if [[ "${{ steps.filter.outputs.server }}" == "true" || "${{ github.ref }}" ==  "refs/heads/main" ]]; then
            echo "server=true" >> $GITHUB_OUTPUT
            echo "Server jobs will run."
          else
            echo "Server jobs will be skipped."
          fi

          if [[ "${{ steps.filter.outputs.client }}" == "true" || "${{ github.ref }}" ==  "refs/heads/main" ]]; then
            echo "client=true" >> $GITHUB_OUTPUT
            echo "Client jobs will run."
          else
            echo "Client jobs will be skipped."
          fi

  docker-build-server:
    runs-on: ubicloud-standard-4
    needs: changes
    env:
      GOMAXPROCS: 4
    steps:
      - name: Skip if no server changes exist
        if: ${{ needs.changes.outputs.server != 'true' }}
        run: echo "No server changes detected — skipping server-build-lint job."

      - name: Checkout
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: "auth"
        if: ${{ needs.changes.outputs.server == 'true' }}
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/409661704476/locations/global/workloadIdentityPools/ga-pool/providers/github-oidc-provider"
          service_account: "speakeasy-registry-ga-ci@linen-analyst-344721.iam.gserviceaccount.com"
      - name: Login to GCR
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: gcr.io/linen-analyst-344721
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and Push Registry image to GCR
        id: build
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: ./.github/workflows/composite/build-push
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          image: ${{ env.DOCKER_REPOSITORY_OWNER }}/gram
          context: ./server
          file: server/Dockerfile
          git-auth-token: ${{ secrets.BOT_REPO_TOKEN }}
          build-args: |
            GIT_USERNAME=speakeasybot
      - name: Pull and Run Image
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: |
          echo "Pulling image: ${{ steps.build.outputs.image-tag }}"
          docker pull ${{ steps.build.outputs.image-tag }}
          echo "Running image..."
          docker run --rm ${{ steps.build.outputs.image-tag }} version

  server-build-lint:
    runs-on: ubicloud-standard-4
    needs: changes
    env:
      GOMAXPROCS: 4
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: gram
          POSTGRES_PASSWORD: gram
          POSTGRES_DB: gram
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5439:5432
    steps:
      - name: Skip if no server changes exist
        if: ${{ needs.changes.outputs.server != 'true' }}
        run: echo "No server changes detected — skipping server-build-lint job."

      - name: Checkout
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Mise
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - name: Prepare GitHub Actions environment
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run github

      - name: Cache Go
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}

      - name: Build
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run build:server --readonly

      - name: Lint with golangci-lint
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          install-mode: none
          working-directory: server

      - name: Install Go tools
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: go install tool
        working-directory: server

        # TODO add speakeasy cli so the sdk can be generated
      - name: Run code generators
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run "gen:server"

      - name: Run "go mod tidy"
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run go:tidy

      - name: Check for dirty files
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run git:porcelain

  server-test:
    runs-on: ubicloud-standard-4
    needs: changes
    env:
      GOMAXPROCS: 4
    steps:
      - name: Skip if no server changes exist
        if: ${{ needs.changes.outputs.server != 'true' }}
        run: echo "No server changes detected — skipping server-test job."

      - name: Checkout
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Mise
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - name: Prepare GitHub Actions environment
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run github

      - name: Cache Go
        if: ${{ needs.changes.outputs.server == 'true' }}
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}

      - name: Install Go deps
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run install:go

      - name: Test
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: mise run test:server

  client-build-lint-test:
    runs-on: ubicloud-standard-4
    needs: changes
    env:
      GRAM_GIT_SHA: "${{ github.sha }}"
    steps:
      - name: Skip if no client changes exist
        if: ${{ needs.changes.outputs.client != 'true' }}
        run: echo "No client changes detected — skipping client-build-lint-test job."

      - name: Checkout
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Mise
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - name: Prepare GitHub Actions environment
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: mise run github

      - name: Cache PNPM
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}

      - name: Install dependencies
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ needs.changes.outputs.client == 'true' }}
        env:
          NODE_ENV: production
        run: mise exec --env viteprod -- pnpm build

      - name: Upload source maps to DataDog
        if: ${{ needs.changes.outputs.client == 'true' }}
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: mise run datadog:sourcemaps --git-sha "${{ github.sha }}"

      - name: Lint
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: pnpm lint
        working-directory: client/dashboard

      - name: Check for dirty files
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: mise run git:porcelain

      - id: "auth"
        if: needs.changes.outputs.client == 'true'
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/409661704476/locations/global/workloadIdentityPools/ga-pool/providers/github-oidc-provider"
          service_account: "speakeasy-registry-ga-ci@linen-analyst-344721.iam.gserviceaccount.com"
      - name: Login to GCR
        if: needs.changes.outputs.client == 'true'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: gcr.io/linen-analyst-344721
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and Push Registry image to GCR
        id: build
        if: needs.changes.outputs.client == 'true'
        uses: ./.github/workflows/composite/build-push
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          image: ${{ env.DOCKER_REPOSITORY_OWNER }}/gram-dashboard
          context: ./client/dashboard
          file: client/dashboard/Dockerfile
          git-auth-token: ${{ secrets.BOT_REPO_TOKEN }}

      - name: Prune PNPM store
        if: ${{ needs.changes.outputs.client == 'true' && success() }}
        run: pnpm store prune

  ts-sdk-build-lint:
    strategy:
      matrix:
        target: ["client/sdk"]
    runs-on: ubicloud-standard-4
    needs: changes
    steps:
      - name: Skip if no client changes exist
        if: ${{ needs.changes.outputs.client != 'true' }}
        run: echo "No client changes detected — skipping ts-sdk-build-lint."

      - name: Checkout
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Mise
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - name: Prepare GitHub Actions environment
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: mise run github

      - name: Cache PNPM
        if: ${{ needs.changes.outputs.client == 'true' }}
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}

      - name: Install dependencies
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: pnpm build
        working-directory: ${{ matrix.target }}

      - name: Lint
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: pnpm lint
        working-directory: ${{ matrix.target }}

      - name: Prune PNPM store
        if: ${{ needs.changes.outputs.client == 'true' && success() }}
        run: pnpm store prune

      - name: Check for dirty files
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: mise run git:porcelain
